TH1D* hist_bveto_njetrw_correction = new TH1D("hist_bveto_njetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1D* hist_bveto_nbjetrw_correction = new TH1D("hist_bveto_nbjetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1D* hist_bveto_ptrw_correction = new TH1D("hist_bveto_ptrw_correction","Z/photon correction",bin_size,bphys_pt_bin);
TH1D* hist_bveto_ptsmrw_correction = new TH1D("hist_bveto_ptsmrw_correction","Z/photon correction",bin_size,bphys_pt_bin);
TH1D* hist_bveto_etrw_correction = new TH1D("hist_bveto_etrw_correction","Z/photon correction",bin_size,et_bin);
TH1D* hist_bveto_etsmrw_correction = new TH1D("hist_bveto_etsmrw_correction","Z/photon correction",bin_size,et_bin);
TH1D* hist_bveto_htrw_correction = new TH1D("hist_bveto_htrw_correction","Z/photon correction",bin_size,ht_bin);

TH1D* hist_bveto_z_njet = new TH1D("hist_bveto_z_njet","",bin_size,njet_bin);
TH1D* hist_bveto_z_nbjet = new TH1D("hist_bveto_z_nbjet","",bin_size,njet_bin);
TH1D* hist_bveto_z_pt = new TH1D("hist_bveto_z_pt","",bin_size,bphys_pt_bin);
TH1D* hist_bveto_z_et = new TH1D("hist_bveto_z_et","",bin_size,et_bin);
TH1D* hist_bveto_z_ht = new TH1D("hist_bveto_z_ht","",bin_size,ht_bin);
TH1D* hist_bveto_tt_njet = new TH1D("hist_bveto_tt_njet","",bin_size,njet_bin);
TH1D* hist_bveto_tt_nbjet = new TH1D("hist_bveto_tt_nbjet","",bin_size,njet_bin);
TH1D* hist_bveto_tt_pt = new TH1D("hist_bveto_tt_pt","",bin_size,bphys_pt_bin);
TH1D* hist_bveto_tt_et = new TH1D("hist_bveto_tt_et","",bin_size,et_bin);
TH1D* hist_bveto_tt_ht = new TH1D("hist_bveto_tt_ht","",bin_size,ht_bin);
TH1D* hist_bveto_vv_njet = new TH1D("hist_bveto_vv_njet","",bin_size,njet_bin);
TH1D* hist_bveto_vv_nbjet = new TH1D("hist_bveto_vv_nbjet","",bin_size,njet_bin);
TH1D* hist_bveto_vv_pt = new TH1D("hist_bveto_vv_pt","",bin_size,bphys_pt_bin);
TH1D* hist_bveto_vv_et = new TH1D("hist_bveto_vv_et","",bin_size,et_bin);
TH1D* hist_bveto_vv_ht = new TH1D("hist_bveto_vv_ht","",bin_size,ht_bin);
TH1D* hist_bveto_photon_njet = new TH1D("hist_bveto_photon_njet","",bin_size,njet_bin);
TH1D* hist_bveto_photon_nbjet = new TH1D("hist_bveto_photon_nbjet","",bin_size,njet_bin);
TH1D* hist_bveto_photon_pt = new TH1D("hist_bveto_photon_pt","",bin_size,bphys_pt_bin);
TH1D* hist_bveto_photon_ptsm = new TH1D("hist_bveto_photon_ptsm","",bin_size,bphys_pt_bin);
TH1D* hist_bveto_photon_et = new TH1D("hist_bveto_photon_et","",bin_size,et_bin);
TH1D* hist_bveto_photon_etsm = new TH1D("hist_bveto_photon_etsm","",bin_size,et_bin);
TH1D* hist_bveto_photon_ht = new TH1D("hist_bveto_photon_ht","",bin_size,ht_bin);

double totalWeight = 0.;
int jet_n = 0;
int bjet_n = 0;
double Z_pt = 0.;
double Jpsi_pt = 0.;
double Jpsi_pt_smear = 0.;
double HT = 0.;
double mll = 0.;
double MET = 0.;
double mj0j1 = 0.;
float MT2W = 0.;
double DPhi_METJetLeading = 0.;
double DPhi_METJetSecond = 0.;

std::vector<double>* lep_pT = new std::vector<double>(10);
std::vector<double>* jet_pT = new std::vector<double>(10);

void GetJpsiReweightingHistogram(string ch, int isData, double lumi, string photon_tag) {

	string  filename;
	if (isData!=-1) {
		cout << "Opening file           : " << TString(outputPath)+"data/data_"+TString(ch)+".root"  << endl;
		TFile fZ( TString(outputPath)+"data/data_"+TString(ch)+".root" );
		TTree*  tZ              = (TTree*)fZ.Get("BaselineTree");
		tZ->SetBranchStatus("*", 0);
		tZ->SetBranchStatus("totalWeight", 1);
		tZ->SetBranchStatus("jet_n", 1);
		tZ->SetBranchStatus("bjet_n", 1);
		tZ->SetBranchStatus("Z_pt", 1);
		tZ->SetBranchStatus("DPhi_METJetLeading", 1);
		tZ->SetBranchStatus("DPhi_METJetSecond", 1);
		tZ->SetBranchStatus("HT", 1);
		tZ->SetBranchStatus("mll", 1);
		tZ->SetBranchStatus("lep_pT"                 ,1);
		tZ->SetBranchStatus("jet_pT"                 ,1);
		tZ->SetBranchStatus("mj0j1", 1);
		tZ->SetBranchStatus("MT2W", 1);
		tZ->SetBranchAddress("totalWeight" ,&totalWeight);
		tZ->SetBranchAddress("jet_n" ,&jet_n);
		tZ->SetBranchAddress("bjet_n" ,&bjet_n);
		tZ->SetBranchAddress("Z_pt" ,&Z_pt);
		tZ->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tZ->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tZ->SetBranchAddress("HT" ,&HT);
		tZ->SetBranchAddress("mll" ,&mll);
		tZ->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tZ->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tZ->SetBranchAddress("mj0j1" ,&mj0j1);
		tZ->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (Z_pt>40) continue;
			if (Z_pt<2) continue;
			hist_bveto_z_njet->Fill(jet_n,totalWeight);
			hist_bveto_z_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_z_pt->Fill(Z_pt,totalWeight);
			hist_bveto_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_bveto_z_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Add(hist_bveto_z_njet);
		hist_bveto_nbjetrw_correction->Add(hist_bveto_z_nbjet);
		hist_bveto_ptrw_correction->Add(hist_bveto_z_pt);
		hist_bveto_ptsmrw_correction->Add(hist_bveto_z_pt);
		hist_bveto_etrw_correction->Add(hist_bveto_z_et);
		hist_bveto_etsmrw_correction->Add(hist_bveto_z_et);
		hist_bveto_htrw_correction->Add(hist_bveto_z_ht);
		fZ.Close();
		//cout << "Opening file           : " << TString(outputPath)+"tt/tt"+TString(ch)+".root"        << endl;
		//TFile ftt( TString(outputPath)+"tt/tt"+TString(ch)+".root" );
		//TTree*  ttt              = (TTree*)ftt.Get("BaselineTree");
		//ttt->SetBranchStatus("*", 0);
		//ttt->SetBranchStatus("totalWeight", 1);
		//ttt->SetBranchStatus("jet_n", 1);
		//ttt->SetBranchStatus("bjet_n", 1);
		//ttt->SetBranchStatus("Z_pt", 1);
		//ttt->SetBranchStatus("DPhi_METJetLeading", 1);
		//ttt->SetBranchStatus("DPhi_METJetSecond", 1);
		//ttt->SetBranchStatus("HT", 1);
		//ttt->SetBranchStatus("mll", 1);
		//ttt->SetBranchStatus("lep_pT"                 ,1);
		//ttt->SetBranchStatus("jet_pT"                 ,1);
		//ttt->SetBranchStatus("mj0j1", 1);
		//ttt->SetBranchStatus("MT2W", 1);
		//ttt->SetBranchAddress("totalWeight" ,&totalWeight);
		//ttt->SetBranchAddress("jet_n" ,&jet_n);
		//ttt->SetBranchAddress("bjet_n" ,&bjet_n);
		//ttt->SetBranchAddress("Z_pt" ,&Z_pt);
		//ttt->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		//ttt->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		//ttt->SetBranchAddress("HT" ,&HT);
		//ttt->SetBranchAddress("mll" ,&mll);
		//ttt->SetBranchAddress("lep_pT"          ,&lep_pT           );
		//ttt->SetBranchAddress("jet_pT"          ,&jet_pT           );
		//ttt->SetBranchAddress("mj0j1" ,&mj0j1);
		//ttt->SetBranchAddress("MT2W" ,&MT2W);
		//for (int entry=0;entry<ttt->GetEntries();entry++) {
		//	ttt->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (Z_pt>40) continue;
		//	hist_bveto_tt_njet->Fill(jet_n,totalWeight);
		//	hist_bveto_tt_nbjet->Fill(bjet_n,totalWeight);
		//	hist_bveto_tt_pt->Fill(Z_pt,totalWeight);
		//	hist_bveto_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_bveto_tt_ht->Fill(HT,totalWeight);
		//}
		//hist_bveto_njetrw_correction->Add(hist_bveto_tt_njet,-1.*lumi);
		//hist_bveto_nbjetrw_correction->Add(hist_bveto_tt_nbjet,-1.*lumi);
		//hist_bveto_ptrw_correction->Add(hist_bveto_tt_pt,-1.*lumi);
		//hist_bveto_ptsmrw_correction->Add(hist_bveto_tt_pt,-1.*lumi);
		//hist_bveto_etrw_correction->Add(hist_bveto_tt_et,-1.*lumi);
		//hist_bveto_etsmrw_correction->Add(hist_bveto_tt_et,-1.*lumi);
		//hist_bveto_htrw_correction->Add(hist_bveto_tt_ht,-1.*lumi);
		//ftt.Close();
		//cout << "Opening file           : " << TString(outputPath)+"vv/vv"+TString(ch)+".root"       << endl;
		//TFile fvv( TString(outputPath)+"vv/vv"+TString(ch)+".root" );
		//TTree*  tvv              = (TTree*)fvv.Get("BaselineTree");
		//tvv->SetBranchStatus("*", 0);
		//tvv->SetBranchStatus("totalWeight", 1);
		//tvv->SetBranchStatus("jet_n", 1);
		//tvv->SetBranchStatus("bjet_n", 1);
		//tvv->SetBranchStatus("Z_pt", 1);
		//tvv->SetBranchStatus("DPhi_METJetLeading", 1);
		//tvv->SetBranchStatus("DPhi_METJetSecond", 1);
		//tvv->SetBranchStatus("HT", 1);
		//tvv->SetBranchStatus("mll", 1);
		//tvv->SetBranchStatus("lep_pT"                 ,1);
		//tvv->SetBranchStatus("jet_pT"                 ,1);
		//tvv->SetBranchStatus("mj0j1", 1);
		//tvv->SetBranchStatus("MT2W", 1);
		//tvv->SetBranchAddress("totalWeight" ,&totalWeight);
		//tvv->SetBranchAddress("jet_n" ,&jet_n);
		//tvv->SetBranchAddress("bjet_n" ,&bjet_n);
		//tvv->SetBranchAddress("Z_pt" ,&Z_pt);
		//tvv->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		//tvv->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		//tvv->SetBranchAddress("HT" ,&HT);
		//tvv->SetBranchAddress("mll" ,&mll);
		//tvv->SetBranchAddress("lep_pT"          ,&lep_pT           );
		//tvv->SetBranchAddress("jet_pT"          ,&jet_pT           );
		//tvv->SetBranchAddress("mj0j1" ,&mj0j1);
		//tvv->SetBranchAddress("MT2W" ,&MT2W);
		//for (int entry=0;entry<tvv->GetEntries();entry++) {
		//	tvv->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (Z_pt>40) continue;
		//	hist_bveto_vv_njet->Fill(jet_n,totalWeight);
		//	hist_bveto_vv_nbjet->Fill(bjet_n,totalWeight);
		//	hist_bveto_vv_pt->Fill(Z_pt,totalWeight);
		//	hist_bveto_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_bveto_vv_ht->Fill(HT,totalWeight);
		//}
		//hist_bveto_njetrw_correction->Add(hist_bveto_vv_njet,-1.*lumi);
		//hist_bveto_nbjetrw_correction->Add(hist_bveto_vv_nbjet,-1.*lumi);
		//hist_bveto_ptrw_correction->Add(hist_bveto_vv_pt,-1.*lumi);
		//hist_bveto_ptsmrw_correction->Add(hist_bveto_vv_pt,-1.*lumi);
		//hist_bveto_etrw_correction->Add(hist_bveto_vv_et,-1.*lumi);
		//hist_bveto_etsmrw_correction->Add(hist_bveto_vv_et,-1.*lumi);
		//hist_bveto_htrw_correction->Add(hist_bveto_vv_ht,-1.*lumi);
		//fvv.Close();
		if (isData==0) filename = TString(TString(outputPath)+"bphys/bdata_"+TString(ch)+TString(photon_tag)+".root"); 
		if (isData==1) filename = TString(TString(outputPath)+"bphys/jpsidata_"+TString(ch)+TString(photon_tag)+".root"); 
		if (isData==2) filename = TString(TString(outputPath)+"bphys/upsidata_"+TString(ch)+TString(photon_tag)+".root"); 
		TFile fPhoton(filename.c_str());
		TTree*  tPhoton              = (TTree*)fPhoton.Get("BaselineTree");
		tPhoton->SetBranchStatus("*", 0);
		tPhoton->SetBranchStatus("totalWeight", 1);
		tPhoton->SetBranchStatus("jet_n", 1);
		tPhoton->SetBranchStatus("bjet_n", 1);
		tPhoton->SetBranchStatus("Jpsi_pt", 1);
		tPhoton->SetBranchStatus("Z_pt", 1);
		tPhoton->SetBranchStatus("DPhi_METJetLeading", 1);
		tPhoton->SetBranchStatus("DPhi_METJetSecond", 1);
		tPhoton->SetBranchStatus("HT", 1);
		tPhoton->SetBranchStatus("mll", 1);
		tPhoton->SetBranchStatus("lep_pT"                 ,1);
		tPhoton->SetBranchStatus("jet_pT"                 ,1);
		tPhoton->SetBranchStatus("mj0j1", 1);
		tPhoton->SetBranchStatus("MT2W", 1);
		tPhoton->SetBranchAddress("totalWeight" ,&totalWeight);
		tPhoton->SetBranchAddress("jet_n" ,&jet_n);
		tPhoton->SetBranchAddress("bjet_n" ,&bjet_n);
		tPhoton->SetBranchAddress("Jpsi_pt" ,&Jpsi_pt);
		tPhoton->SetBranchAddress("Z_pt" ,&Jpsi_pt_smear);
		tPhoton->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tPhoton->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tPhoton->SetBranchAddress("HT" ,&HT);
		tPhoton->SetBranchAddress("mll" ,&mll);
		tPhoton->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tPhoton->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tPhoton->SetBranchAddress("mj0j1" ,&mj0j1);
		tPhoton->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (Jpsi_pt>40) continue;
			if (Jpsi_pt<2) continue;
			hist_bveto_photon_njet->Fill(jet_n,totalWeight);
			hist_bveto_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_photon_pt->Fill(Jpsi_pt,totalWeight);
			hist_bveto_photon_et->Fill(pow(Jpsi_pt*Jpsi_pt+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ptsm->Fill(Jpsi_pt_smear,totalWeight);
			hist_bveto_photon_etsm->Fill(pow(Jpsi_pt_smear*Jpsi_pt_smear+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Divide(hist_bveto_photon_njet);
		hist_bveto_nbjetrw_correction->Divide(hist_bveto_photon_nbjet);
		hist_bveto_ptrw_correction->Divide(hist_bveto_photon_pt);
		hist_bveto_ptsmrw_correction->Divide(hist_bveto_photon_ptsm);
		hist_bveto_etrw_correction->Divide(hist_bveto_photon_et);
		hist_bveto_etsmrw_correction->Divide(hist_bveto_photon_etsm);
		hist_bveto_htrw_correction->Divide(hist_bveto_photon_ht);
		fPhoton.Close();
	}
	else {
		TFile fZ( TString(outputPath)+"zjets/zjets_"+TString(ch)+".root" );
		TTree*  tZ              = (TTree*)fZ.Get("BaselineTree");
		tZ->SetBranchStatus("*", 0);
		tZ->SetBranchStatus("totalWeight", 1);
		tZ->SetBranchStatus("jet_n", 1);
		tZ->SetBranchStatus("bjet_n", 1);
		tZ->SetBranchStatus("Z_pt", 1);
		tZ->SetBranchStatus("DPhi_METJetLeading", 1);
		tZ->SetBranchStatus("DPhi_METJetSecond", 1);
		tZ->SetBranchStatus("HT", 1);
		tZ->SetBranchStatus("mll", 1);
		tZ->SetBranchStatus("lep_pT"                 ,1);
		tZ->SetBranchStatus("jet_pT"                 ,1);
		tZ->SetBranchStatus("mj0j1", 1);
		tZ->SetBranchStatus("MT2W", 1);
		tZ->SetBranchAddress("totalWeight" ,&totalWeight);
		tZ->SetBranchAddress("jet_n" ,&jet_n);
		tZ->SetBranchAddress("bjet_n" ,&bjet_n);
		tZ->SetBranchAddress("Z_pt" ,&Z_pt);
		tZ->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tZ->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tZ->SetBranchAddress("HT" ,&HT);
		tZ->SetBranchAddress("mll" ,&mll);
		tZ->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tZ->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tZ->SetBranchAddress("mj0j1" ,&mj0j1);
		tZ->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (Z_pt>40) continue;
			hist_bveto_z_njet->Fill(jet_n,totalWeight);
			hist_bveto_z_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_z_pt->Fill(Z_pt,totalWeight);
			hist_bveto_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_bveto_z_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Add(hist_bveto_z_njet);
		hist_bveto_nbjetrw_correction->Add(hist_bveto_z_nbjet);
		hist_bveto_ptrw_correction->Add(hist_bveto_z_pt);
		hist_bveto_ptsmrw_correction->Add(hist_bveto_z_pt);
		hist_bveto_etrw_correction->Add(hist_bveto_z_et);
		hist_bveto_etsmrw_correction->Add(hist_bveto_z_et);
		hist_bveto_htrw_correction->Add(hist_bveto_z_ht);
		fZ.Close();
		TFile fPhoton( TString(outputPath)+"bphys/bdata_"+TString(ch)+TString(photon_tag)+".root" );
		TTree*  tPhoton              = (TTree*)fPhoton.Get("BaselineTree");
		tPhoton->SetBranchStatus("*", 0);
		tPhoton->SetBranchStatus("totalWeight", 1);
		tPhoton->SetBranchStatus("jet_n", 1);
		tPhoton->SetBranchStatus("bjet_n", 1);
		tPhoton->SetBranchStatus("Jpsi_pt", 1);
		tPhoton->SetBranchStatus("Z_pt", 1);
		tPhoton->SetBranchStatus("DPhi_METJetLeading", 1);
		tPhoton->SetBranchStatus("DPhi_METJetSecond", 1);
		tPhoton->SetBranchStatus("HT", 1);
		tPhoton->SetBranchStatus("mll", 1);
		tPhoton->SetBranchStatus("lep_pT"                 ,1);
		tPhoton->SetBranchStatus("jet_pT"                 ,1);
		tPhoton->SetBranchStatus("mj0j1", 1);
		tPhoton->SetBranchStatus("MT2W", 1);
		tPhoton->SetBranchAddress("totalWeight" ,&totalWeight);
		tPhoton->SetBranchAddress("jet_n" ,&jet_n);
		tPhoton->SetBranchAddress("bjet_n" ,&bjet_n);
		tPhoton->SetBranchAddress("Jpsi_pt" ,&Jpsi_pt);
		tPhoton->SetBranchAddress("Z_pt" ,&Jpsi_pt_smear);
		tPhoton->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tPhoton->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tPhoton->SetBranchAddress("HT" ,&HT);
		tPhoton->SetBranchAddress("mll" ,&mll);
		tPhoton->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tPhoton->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tPhoton->SetBranchAddress("mj0j1" ,&mj0j1);
		tPhoton->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (Jpsi_pt>40) continue;
			hist_bveto_photon_njet->Fill(jet_n,totalWeight);
			hist_bveto_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_photon_pt->Fill(Jpsi_pt,totalWeight);
			hist_bveto_photon_et->Fill(pow(Jpsi_pt*Jpsi_pt+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ptsm->Fill(Jpsi_pt_smear,totalWeight);
			hist_bveto_photon_etsm->Fill(pow(Jpsi_pt_smear*Jpsi_pt_smear+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Divide(hist_bveto_photon_njet);
		hist_bveto_nbjetrw_correction->Divide(hist_bveto_photon_nbjet);
		hist_bveto_ptrw_correction->Divide(hist_bveto_photon_pt);
		hist_bveto_ptsmrw_correction->Divide(hist_bveto_photon_ptsm);
		hist_bveto_etrw_correction->Divide(hist_bveto_photon_et);
		hist_bveto_etsmrw_correction->Divide(hist_bveto_photon_etsm);
		hist_bveto_htrw_correction->Divide(hist_bveto_photon_ht);
		fPhoton.Close();
	}

}
