TH1F* hist_bveto_njetrw_correction = new TH1F("hist_bveto_njetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_bveto_nbjetrw_correction = new TH1F("hist_bveto_nbjetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_bveto_ptrw_correction = new TH1F("hist_bveto_ptrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_bveto_ptsmrw_correction = new TH1F("hist_bveto_ptsmrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_bveto_etrw_correction = new TH1F("hist_bveto_etrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_bveto_etsmrw_correction = new TH1F("hist_bveto_etsmrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_bveto_htrw_correction = new TH1F("hist_bveto_htrw_correction","Z/photon correction",bin_size,ht_bin);
TH1F* hist_37_bveto_met_correction = new TH1F("hist_37_bveto_met_correction","Z/photon correction",bin_size,met_bin);
TH1F* hist_37_bveto_lpt_correction = new TH1F("hist_37_bveto_lpt_correction","Z/photon correction",bin_size,lpt_bin);
TH1F* hist_incl_bveto_met = new TH1F("hist_incl_bveto_met","inclusive MET",bin_size,met_bin);
TH1F* hist_gt37_bveto_met = new TH1F("hist_gt37_bveto_met","pT>37 GeV MET",bin_size,met_bin);
TH1F* hist_incl_bveto_lpt = new TH1F("hist_incl_bveto_lpt","inclusive lep pT",bin_size,lpt_bin);
TH1F* hist_gt37_bveto_lpt = new TH1F("hist_gt37_bveto_lpt","pT>37 GeV lep pT",bin_size,lpt_bin);

TH1F* hist_2j30_njetrw_correction = new TH1F("hist_2j30_njetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_2j30_nbjetrw_correction = new TH1F("hist_2j30_nbjetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_2j30_ptrw_correction = new TH1F("hist_2j30_ptrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_2j30_ptsmrw_correction = new TH1F("hist_2j30_ptsmrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_2j30_etrw_correction = new TH1F("hist_2j30_etrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_2j30_etsmrw_correction = new TH1F("hist_2j30_etsmrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_2j30_htrw_correction = new TH1F("hist_2j30_htrw_correction","Z/photon correction",bin_size,ht_bin);
TH1F* hist_37_2j30_met_correction = new TH1F("hist_37_2j30_met_correction","Z/photon correction",bin_size,met_bin);
TH1F* hist_37_2j30_lpt_correction = new TH1F("hist_37_2j30_lpt_correction","Z/photon correction",bin_size,lpt_bin);
TH1F* hist_incl_2j30_met = new TH1F("hist_incl_2j30_met","inclusive MET",bin_size,met_bin);
TH1F* hist_gt37_2j30_met = new TH1F("hist_gt37_2j30_met","pT>37 GeV MET",bin_size,met_bin);
TH1F* hist_incl_2j30_lpt = new TH1F("hist_incl_2j30_lpt","inclusive lep pT",bin_size,lpt_bin);
TH1F* hist_gt37_2j30_lpt = new TH1F("hist_gt37_2j30_lpt","pT>37 GeV lep pT",bin_size,lpt_bin);

TH1F* hist_ht200_njetrw_correction = new TH1F("hist_ht200_njetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_ht200_nbjetrw_correction = new TH1F("hist_ht200_nbjetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_ht200_ptrw_correction = new TH1F("hist_ht200_ptrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_ht200_ptsmrw_correction = new TH1F("hist_ht200_ptsmrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_ht200_etrw_correction = new TH1F("hist_ht200_etrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_ht200_etsmrw_correction = new TH1F("hist_ht200_etsmrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_ht200_htrw_correction = new TH1F("hist_ht200_htrw_correction","Z/photon correction",bin_size,ht_bin);
TH1F* hist_37_ht200_met_correction = new TH1F("hist_37_ht200_met_correction","Z/photon correction",bin_size,met_bin);
TH1F* hist_37_ht200_lpt_correction = new TH1F("hist_37_ht200_lpt_correction","Z/photon correction",bin_size,lpt_bin);
TH1F* hist_incl_ht200_met = new TH1F("hist_incl_ht200_met","inclusive MET",bin_size,met_bin);
TH1F* hist_gt37_ht200_met = new TH1F("hist_gt37_ht200_met","pT>37 GeV MET",bin_size,met_bin);
TH1F* hist_incl_ht200_lpt = new TH1F("hist_incl_ht200_lpt","inclusive lep pT",bin_size,lpt_bin);
TH1F* hist_gt37_ht200_lpt = new TH1F("hist_gt37_ht200_lpt","pT>37 GeV lep pT",bin_size,lpt_bin);

TH1F* hist_ht400_njetrw_correction = new TH1F("hist_ht400_njetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_ht400_nbjetrw_correction = new TH1F("hist_ht400_nbjetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_ht400_ptrw_correction = new TH1F("hist_ht400_ptrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_ht400_ptsmrw_correction = new TH1F("hist_ht400_ptsmrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_ht400_etrw_correction = new TH1F("hist_ht400_etrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_ht400_etsmrw_correction = new TH1F("hist_ht400_etsmrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_ht400_htrw_correction = new TH1F("hist_ht400_htrw_correction","Z/photon correction",bin_size,ht_bin);
TH1F* hist_37_ht400_met_correction = new TH1F("hist_37_ht400_met_correction","Z/photon correction",bin_size,met_bin);
TH1F* hist_37_ht400_lpt_correction = new TH1F("hist_37_ht400_lpt_correction","Z/photon correction",bin_size,lpt_bin);
TH1F* hist_incl_ht400_met = new TH1F("hist_incl_ht400_met","inclusive MET",bin_size,met_bin);
TH1F* hist_gt37_ht400_met = new TH1F("hist_gt37_ht400_met","pT>37 GeV MET",bin_size,met_bin);
TH1F* hist_incl_ht400_lpt = new TH1F("hist_incl_ht400_lpt","inclusive lep pT",bin_size,lpt_bin);
TH1F* hist_gt37_ht400_lpt = new TH1F("hist_gt37_ht400_lpt","pT>37 GeV lep pT",bin_size,lpt_bin);

TH1F* hist_ht1200_njetrw_correction = new TH1F("hist_ht1200_njetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_ht1200_nbjetrw_correction = new TH1F("hist_ht1200_nbjetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_ht1200_ptrw_correction = new TH1F("hist_ht1200_ptrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_ht1200_ptsmrw_correction = new TH1F("hist_ht1200_ptsmrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_ht1200_etrw_correction = new TH1F("hist_ht1200_etrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_ht1200_etsmrw_correction = new TH1F("hist_ht1200_etsmrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_ht1200_htrw_correction = new TH1F("hist_ht1200_htrw_correction","Z/photon correction",bin_size,ht_bin);
TH1F* hist_37_ht1200_met_correction = new TH1F("hist_37_ht1200_met_correction","Z/photon correction",bin_size,met_bin);
TH1F* hist_37_ht1200_lpt_correction = new TH1F("hist_37_ht1200_lpt_correction","Z/photon correction",bin_size,lpt_bin);
TH1F* hist_incl_ht1200_met = new TH1F("hist_incl_ht1200_met","inclusive MET",bin_size,met_bin);
TH1F* hist_gt37_ht1200_met = new TH1F("hist_gt37_ht1200_met","pT>37 GeV MET",bin_size,met_bin);
TH1F* hist_incl_ht1200_lpt = new TH1F("hist_incl_ht1200_lpt","inclusive lep pT",bin_size,lpt_bin);
TH1F* hist_gt37_ht1200_lpt = new TH1F("hist_gt37_ht1200_lpt","pT>37 GeV lep pT",bin_size,lpt_bin);

TH1F* hist_srhigh_njetrw_correction = new TH1F("hist_srhigh_njetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_srhigh_nbjetrw_correction = new TH1F("hist_srhigh_nbjetrw_correction","Z/photon correction",bin_size,njet_bin);
TH1F* hist_srhigh_ptrw_correction = new TH1F("hist_srhigh_ptrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_srhigh_ptsmrw_correction = new TH1F("hist_srhigh_ptsmrw_correction","Z/photon correction",bin_size,pt_bin);
TH1F* hist_srhigh_etrw_correction = new TH1F("hist_srhigh_etrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_srhigh_etsmrw_correction = new TH1F("hist_srhigh_etsmrw_correction","Z/photon correction",bin_size,et_bin);
TH1F* hist_srhigh_htrw_correction = new TH1F("hist_srhigh_htrw_correction","Z/photon correction",bin_size,ht_bin);
TH1F* hist_37_srhigh_met_correction = new TH1F("hist_37_srhigh_met_correction","Z/photon correction",bin_size,met_bin);
TH1F* hist_incl_srhigh_met = new TH1F("hist_incl_srhigh_met","inclusive MET",bin_size,met_bin);
TH1F* hist_gt37_srhigh_met = new TH1F("hist_gt37_srhigh_met","pT>37 GeV MET",bin_size,met_bin);

TH1F* hist_bveto_z_njet = new TH1F("hist_bveto_z_njet","",bin_size,njet_bin);
TH1F* hist_bveto_z_nbjet = new TH1F("hist_bveto_z_nbjet","",bin_size,njet_bin);
TH1F* hist_bveto_z_pt = new TH1F("hist_bveto_z_pt","",bin_size,pt_bin);
TH1F* hist_bveto_z_et = new TH1F("hist_bveto_z_et","",bin_size,et_bin);
TH1F* hist_bveto_z_ht = new TH1F("hist_bveto_z_ht","",bin_size,ht_bin);
TH1F* hist_bveto_tt_njet = new TH1F("hist_bveto_tt_njet","",bin_size,njet_bin);
TH1F* hist_bveto_tt_nbjet = new TH1F("hist_bveto_tt_nbjet","",bin_size,njet_bin);
TH1F* hist_bveto_tt_pt = new TH1F("hist_bveto_tt_pt","",bin_size,pt_bin);
TH1F* hist_bveto_tt_et = new TH1F("hist_bveto_tt_et","",bin_size,et_bin);
TH1F* hist_bveto_tt_ht = new TH1F("hist_bveto_tt_ht","",bin_size,ht_bin);
TH1F* hist_bveto_vv_njet = new TH1F("hist_bveto_vv_njet","",bin_size,njet_bin);
TH1F* hist_bveto_vv_nbjet = new TH1F("hist_bveto_vv_nbjet","",bin_size,njet_bin);
TH1F* hist_bveto_vv_pt = new TH1F("hist_bveto_vv_pt","",bin_size,pt_bin);
TH1F* hist_bveto_vv_et = new TH1F("hist_bveto_vv_et","",bin_size,et_bin);
TH1F* hist_bveto_vv_ht = new TH1F("hist_bveto_vv_ht","",bin_size,ht_bin);
TH1F* hist_bveto_photon_njet = new TH1F("hist_bveto_photon_njet","",bin_size,njet_bin);
TH1F* hist_bveto_photon_nbjet = new TH1F("hist_bveto_photon_nbjet","",bin_size,njet_bin);
TH1F* hist_bveto_photon_pt = new TH1F("hist_bveto_photon_pt","",bin_size,pt_bin);
TH1F* hist_bveto_photon_ptsm = new TH1F("hist_bveto_photon_ptsm","",bin_size,pt_bin);
TH1F* hist_bveto_photon_et = new TH1F("hist_bveto_photon_et","",bin_size,et_bin);
TH1F* hist_bveto_photon_etsm = new TH1F("hist_bveto_photon_etsm","",bin_size,et_bin);
TH1F* hist_bveto_photon_ht = new TH1F("hist_bveto_photon_ht","",bin_size,ht_bin);

TH1F* hist_2j30_z_njet = new TH1F("hist_2j30_z_njet","",bin_size,njet_bin);
TH1F* hist_2j30_z_nbjet = new TH1F("hist_2j30_z_nbjet","",bin_size,njet_bin);
TH1F* hist_2j30_z_pt = new TH1F("hist_2j30_z_pt","",bin_size,pt_bin);
TH1F* hist_2j30_z_et = new TH1F("hist_2j30_z_et","",bin_size,et_bin);
TH1F* hist_2j30_z_ht = new TH1F("hist_2j30_z_ht","",bin_size,ht_bin);
TH1F* hist_2j30_tt_njet = new TH1F("hist_2j30_tt_njet","",bin_size,njet_bin);
TH1F* hist_2j30_tt_nbjet = new TH1F("hist_2j30_tt_nbjet","",bin_size,njet_bin);
TH1F* hist_2j30_tt_pt = new TH1F("hist_2j30_tt_pt","",bin_size,pt_bin);
TH1F* hist_2j30_tt_et = new TH1F("hist_2j30_tt_et","",bin_size,et_bin);
TH1F* hist_2j30_tt_ht = new TH1F("hist_2j30_tt_ht","",bin_size,ht_bin);
TH1F* hist_2j30_vv_njet = new TH1F("hist_2j30_vv_njet","",bin_size,njet_bin);
TH1F* hist_2j30_vv_nbjet = new TH1F("hist_2j30_vv_nbjet","",bin_size,njet_bin);
TH1F* hist_2j30_vv_pt = new TH1F("hist_2j30_vv_pt","",bin_size,pt_bin);
TH1F* hist_2j30_vv_et = new TH1F("hist_2j30_vv_et","",bin_size,et_bin);
TH1F* hist_2j30_vv_ht = new TH1F("hist_2j30_vv_ht","",bin_size,ht_bin);
TH1F* hist_2j30_photon_njet = new TH1F("hist_2j30_photon_njet","",bin_size,njet_bin);
TH1F* hist_2j30_photon_nbjet = new TH1F("hist_2j30_photon_nbjet","",bin_size,njet_bin);
TH1F* hist_2j30_photon_pt = new TH1F("hist_2j30_photon_pt","",bin_size,pt_bin);
TH1F* hist_2j30_photon_ptsm = new TH1F("hist_2j30_photon_ptsm","",bin_size,pt_bin);
TH1F* hist_2j30_photon_et = new TH1F("hist_2j30_photon_et","",bin_size,et_bin);
TH1F* hist_2j30_photon_etsm = new TH1F("hist_2j30_photon_etsm","",bin_size,et_bin);
TH1F* hist_2j30_photon_ht = new TH1F("hist_2j30_photon_ht","",bin_size,ht_bin);

TH1F* hist_ht200_z_njet = new TH1F("hist_ht200_z_njet","",bin_size,njet_bin);
TH1F* hist_ht200_z_nbjet = new TH1F("hist_ht200_z_nbjet","",bin_size,njet_bin);
TH1F* hist_ht200_z_pt = new TH1F("hist_ht200_z_pt","",bin_size,pt_bin);
TH1F* hist_ht200_z_et = new TH1F("hist_ht200_z_et","",bin_size,et_bin);
TH1F* hist_ht200_z_ht = new TH1F("hist_ht200_z_ht","",bin_size,ht_bin);
TH1F* hist_ht200_tt_njet = new TH1F("hist_ht200_tt_njet","",bin_size,njet_bin);
TH1F* hist_ht200_tt_nbjet = new TH1F("hist_ht200_tt_nbjet","",bin_size,njet_bin);
TH1F* hist_ht200_tt_pt = new TH1F("hist_ht200_tt_pt","",bin_size,pt_bin);
TH1F* hist_ht200_tt_et = new TH1F("hist_ht200_tt_et","",bin_size,et_bin);
TH1F* hist_ht200_tt_ht = new TH1F("hist_ht200_tt_ht","",bin_size,ht_bin);
TH1F* hist_ht200_vv_njet = new TH1F("hist_ht200_vv_njet","",bin_size,njet_bin);
TH1F* hist_ht200_vv_nbjet = new TH1F("hist_ht200_vv_nbjet","",bin_size,njet_bin);
TH1F* hist_ht200_vv_pt = new TH1F("hist_ht200_vv_pt","",bin_size,pt_bin);
TH1F* hist_ht200_vv_et = new TH1F("hist_ht200_vv_et","",bin_size,et_bin);
TH1F* hist_ht200_vv_ht = new TH1F("hist_ht200_vv_ht","",bin_size,ht_bin);
TH1F* hist_ht200_photon_njet = new TH1F("hist_ht200_photon_njet","",bin_size,njet_bin);
TH1F* hist_ht200_photon_nbjet = new TH1F("hist_ht200_photon_nbjet","",bin_size,njet_bin);
TH1F* hist_ht200_photon_pt = new TH1F("hist_ht200_photon_pt","",bin_size,pt_bin);
TH1F* hist_ht200_photon_ptsm = new TH1F("hist_ht200_photon_ptsm","",bin_size,pt_bin);
TH1F* hist_ht200_photon_et = new TH1F("hist_ht200_photon_et","",bin_size,et_bin);
TH1F* hist_ht200_photon_etsm = new TH1F("hist_ht200_photon_etsm","",bin_size,et_bin);
TH1F* hist_ht200_photon_ht = new TH1F("hist_ht200_photon_ht","",bin_size,ht_bin);

TH1F* hist_ht400_z_njet = new TH1F("hist_ht400_z_njet","",bin_size,njet_bin);
TH1F* hist_ht400_z_nbjet = new TH1F("hist_ht400_z_nbjet","",bin_size,njet_bin);
TH1F* hist_ht400_z_pt = new TH1F("hist_ht400_z_pt","",bin_size,pt_bin);
TH1F* hist_ht400_z_et = new TH1F("hist_ht400_z_et","",bin_size,et_bin);
TH1F* hist_ht400_z_ht = new TH1F("hist_ht400_z_ht","",bin_size,ht_bin);
TH1F* hist_ht400_tt_njet = new TH1F("hist_ht400_tt_njet","",bin_size,njet_bin);
TH1F* hist_ht400_tt_nbjet = new TH1F("hist_ht400_tt_nbjet","",bin_size,njet_bin);
TH1F* hist_ht400_tt_pt = new TH1F("hist_ht400_tt_pt","",bin_size,pt_bin);
TH1F* hist_ht400_tt_et = new TH1F("hist_ht400_tt_et","",bin_size,et_bin);
TH1F* hist_ht400_tt_ht = new TH1F("hist_ht400_tt_ht","",bin_size,ht_bin);
TH1F* hist_ht400_vv_njet = new TH1F("hist_ht400_vv_njet","",bin_size,njet_bin);
TH1F* hist_ht400_vv_nbjet = new TH1F("hist_ht400_vv_nbjet","",bin_size,njet_bin);
TH1F* hist_ht400_vv_pt = new TH1F("hist_ht400_vv_pt","",bin_size,pt_bin);
TH1F* hist_ht400_vv_et = new TH1F("hist_ht400_vv_et","",bin_size,et_bin);
TH1F* hist_ht400_vv_ht = new TH1F("hist_ht400_vv_ht","",bin_size,ht_bin);
TH1F* hist_ht400_photon_njet = new TH1F("hist_ht400_photon_njet","",bin_size,njet_bin);
TH1F* hist_ht400_photon_nbjet = new TH1F("hist_ht400_photon_nbjet","",bin_size,njet_bin);
TH1F* hist_ht400_photon_pt = new TH1F("hist_ht400_photon_pt","",bin_size,pt_bin);
TH1F* hist_ht400_photon_ptsm = new TH1F("hist_ht400_photon_ptsm","",bin_size,pt_bin);
TH1F* hist_ht400_photon_et = new TH1F("hist_ht400_photon_et","",bin_size,et_bin);
TH1F* hist_ht400_photon_etsm = new TH1F("hist_ht400_photon_etsm","",bin_size,et_bin);
TH1F* hist_ht400_photon_ht = new TH1F("hist_ht400_photon_ht","",bin_size,ht_bin);

TH1F* hist_ht1200_z_njet = new TH1F("hist_ht1200_z_njet","",bin_size,njet_bin);
TH1F* hist_ht1200_z_nbjet = new TH1F("hist_ht1200_z_nbjet","",bin_size,njet_bin);
TH1F* hist_ht1200_z_pt = new TH1F("hist_ht1200_z_pt","",bin_size,pt_bin);
TH1F* hist_ht1200_z_et = new TH1F("hist_ht1200_z_et","",bin_size,et_bin);
TH1F* hist_ht1200_z_ht = new TH1F("hist_ht1200_z_ht","",bin_size,ht_bin);
TH1F* hist_ht1200_tt_njet = new TH1F("hist_ht1200_tt_njet","",bin_size,njet_bin);
TH1F* hist_ht1200_tt_nbjet = new TH1F("hist_ht1200_tt_nbjet","",bin_size,njet_bin);
TH1F* hist_ht1200_tt_pt = new TH1F("hist_ht1200_tt_pt","",bin_size,pt_bin);
TH1F* hist_ht1200_tt_et = new TH1F("hist_ht1200_tt_et","",bin_size,et_bin);
TH1F* hist_ht1200_tt_ht = new TH1F("hist_ht1200_tt_ht","",bin_size,ht_bin);
TH1F* hist_ht1200_vv_njet = new TH1F("hist_ht1200_vv_njet","",bin_size,njet_bin);
TH1F* hist_ht1200_vv_nbjet = new TH1F("hist_ht1200_vv_nbjet","",bin_size,njet_bin);
TH1F* hist_ht1200_vv_pt = new TH1F("hist_ht1200_vv_pt","",bin_size,pt_bin);
TH1F* hist_ht1200_vv_et = new TH1F("hist_ht1200_vv_et","",bin_size,et_bin);
TH1F* hist_ht1200_vv_ht = new TH1F("hist_ht1200_vv_ht","",bin_size,ht_bin);
TH1F* hist_ht1200_photon_njet = new TH1F("hist_ht1200_photon_njet","",bin_size,njet_bin);
TH1F* hist_ht1200_photon_nbjet = new TH1F("hist_ht1200_photon_nbjet","",bin_size,njet_bin);
TH1F* hist_ht1200_photon_pt = new TH1F("hist_ht1200_photon_pt","",bin_size,pt_bin);
TH1F* hist_ht1200_photon_ptsm = new TH1F("hist_ht1200_photon_ptsm","",bin_size,pt_bin);
TH1F* hist_ht1200_photon_et = new TH1F("hist_ht1200_photon_et","",bin_size,et_bin);
TH1F* hist_ht1200_photon_etsm = new TH1F("hist_ht1200_photon_etsm","",bin_size,et_bin);
TH1F* hist_ht1200_photon_ht = new TH1F("hist_ht1200_photon_ht","",bin_size,ht_bin);

TH1F* hist_srhigh_z_njet = new TH1F("hist_srhigh_z_njet","",bin_size,njet_bin);
TH1F* hist_srhigh_z_nbjet = new TH1F("hist_srhigh_z_nbjet","",bin_size,njet_bin);
TH1F* hist_srhigh_z_pt = new TH1F("hist_srhigh_z_pt","",bin_size,pt_bin);
TH1F* hist_srhigh_z_et = new TH1F("hist_srhigh_z_et","",bin_size,et_bin);
TH1F* hist_srhigh_z_ht = new TH1F("hist_srhigh_z_ht","",bin_size,ht_bin);
TH1F* hist_srhigh_tt_njet = new TH1F("hist_srhigh_tt_njet","",bin_size,njet_bin);
TH1F* hist_srhigh_tt_nbjet = new TH1F("hist_srhigh_tt_nbjet","",bin_size,njet_bin);
TH1F* hist_srhigh_tt_pt = new TH1F("hist_srhigh_tt_pt","",bin_size,pt_bin);
TH1F* hist_srhigh_tt_et = new TH1F("hist_srhigh_tt_et","",bin_size,et_bin);
TH1F* hist_srhigh_tt_ht = new TH1F("hist_srhigh_tt_ht","",bin_size,ht_bin);
TH1F* hist_srhigh_vv_njet = new TH1F("hist_srhigh_vv_njet","",bin_size,njet_bin);
TH1F* hist_srhigh_vv_nbjet = new TH1F("hist_srhigh_vv_nbjet","",bin_size,njet_bin);
TH1F* hist_srhigh_vv_pt = new TH1F("hist_srhigh_vv_pt","",bin_size,pt_bin);
TH1F* hist_srhigh_vv_et = new TH1F("hist_srhigh_vv_et","",bin_size,et_bin);
TH1F* hist_srhigh_vv_ht = new TH1F("hist_srhigh_vv_ht","",bin_size,ht_bin);
TH1F* hist_srhigh_photon_njet = new TH1F("hist_srhigh_photon_njet","",bin_size,njet_bin);
TH1F* hist_srhigh_photon_nbjet = new TH1F("hist_srhigh_photon_nbjet","",bin_size,njet_bin);
TH1F* hist_srhigh_photon_pt = new TH1F("hist_srhigh_photon_pt","",bin_size,pt_bin);
TH1F* hist_srhigh_photon_ptsm = new TH1F("hist_srhigh_photon_ptsm","",bin_size,pt_bin);
TH1F* hist_srhigh_photon_et = new TH1F("hist_srhigh_photon_et","",bin_size,et_bin);
TH1F* hist_srhigh_photon_etsm = new TH1F("hist_srhigh_photon_etsm","",bin_size,et_bin);
TH1F* hist_srhigh_photon_ht = new TH1F("hist_srhigh_photon_ht","",bin_size,ht_bin);

float totalWeight = 0.;
int jet_n = 0;
int bjet_n = 0;
float Z_pt = 0.;
float gamma_pt = 0.;
float gamma_pt_smear = 0.;
float HT = 0.;
float mll = 0.;
float MET = 0.;
float mj0j1 = 0.;
float MT2W = 0.;
float DPhi_METJetLeading = 0.;
float DPhi_METJetSecond = 0.;

std::vector<float>* lep_pT = new std::vector<float>(10);
std::vector<float>* jet_pT = new std::vector<float>(10);

void GetReweightingHistogram(string ch, int isData, float lumi, string photon_tag) {

	TFile fZ( TString(smearingPath)+"zjets/zjets_"+TString(ch)+".root" );
	TTree*  tZ              = (TTree*)fZ.Get("BaselineTree");
	tZ->SetBranchStatus("*", 0);
	tZ->SetBranchStatus("totalWeight", 1);
	tZ->SetBranchStatus("jet_n", 1);
	tZ->SetBranchStatus("bjet_n", 1);
	tZ->SetBranchStatus("Z_pt", 1);
	tZ->SetBranchStatus("DPhi_METJetLeading", 1);
	tZ->SetBranchStatus("DPhi_METJetSecond", 1);
	tZ->SetBranchStatus("HT", 1);
	tZ->SetBranchStatus("MET", 1);
	tZ->SetBranchStatus("mll", 1);
	tZ->SetBranchStatus("lep_pT"                 ,1);
	tZ->SetBranchStatus("jet_pT"                 ,1);
	tZ->SetBranchStatus("mj0j1", 1);
	tZ->SetBranchStatus("MT2W", 1);
	tZ->SetBranchAddress("totalWeight" ,&totalWeight);
	tZ->SetBranchAddress("jet_n" ,&jet_n);
	tZ->SetBranchAddress("bjet_n" ,&bjet_n);
	tZ->SetBranchAddress("Z_pt" ,&Z_pt);
	tZ->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
	tZ->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
	tZ->SetBranchAddress("HT" ,&HT);
	tZ->SetBranchAddress("MET" ,&MET);
	tZ->SetBranchAddress("mll" ,&mll);
	tZ->SetBranchAddress("lep_pT"          ,&lep_pT           );
	tZ->SetBranchAddress("jet_pT"          ,&jet_pT           );
	tZ->SetBranchAddress("mj0j1" ,&mj0j1);
	tZ->SetBranchAddress("MT2W" ,&MT2W);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		hist_incl_bveto_met->Fill(MET,totalWeight);
		hist_incl_bveto_lpt->Fill(lep_pT->at(0),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_bveto_met->Fill(MET,totalWeight);
		hist_gt37_bveto_lpt->Fill(lep_pT->at(0),totalWeight);
	}
	hist_37_bveto_met_correction->Add(hist_incl_bveto_met);
	hist_37_bveto_met_correction->Divide(hist_gt37_bveto_met);
	hist_37_bveto_lpt_correction->Add(hist_incl_bveto_lpt);
	hist_37_bveto_lpt_correction->Divide(hist_gt37_bveto_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (jet_pT->at(0)<30.) continue;
		if (jet_pT->at(1)<30.) continue;
		hist_incl_2j30_met->Fill(MET,totalWeight);
		hist_incl_2j30_lpt->Fill(lep_pT->at(1),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_2j30_met->Fill(MET,totalWeight);
		hist_gt37_2j30_lpt->Fill(lep_pT->at(1),totalWeight);
	}
	hist_37_2j30_met_correction->Add(hist_incl_2j30_met);
	hist_37_2j30_met_correction->Divide(hist_gt37_2j30_met);
	hist_37_2j30_lpt_correction->Add(hist_incl_2j30_lpt);
	hist_37_2j30_lpt_correction->Divide(hist_gt37_2j30_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (HT<200.) continue;
		//if (DPhi_METJetLeading<0.4) continue;
		//if (DPhi_METJetSecond<0.4) continue;
		hist_incl_ht200_met->Fill(MET,totalWeight);
		hist_incl_ht200_lpt->Fill(lep_pT->at(1),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_ht200_met->Fill(MET,totalWeight);
		hist_gt37_ht200_lpt->Fill(lep_pT->at(1),totalWeight);
	}
	hist_37_ht200_met_correction->Add(hist_incl_ht200_met);
	hist_37_ht200_met_correction->Divide(hist_gt37_ht200_met);
	hist_37_ht200_lpt_correction->Add(hist_incl_ht200_lpt);
	hist_37_ht200_lpt_correction->Divide(hist_gt37_ht200_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (HT<400.) continue;
		//if (DPhi_METJetLeading<0.4) continue;
		//if (DPhi_METJetSecond<0.4) continue;
		hist_incl_ht400_met->Fill(MET,totalWeight);
		hist_incl_ht400_lpt->Fill(lep_pT->at(1),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_ht400_met->Fill(MET,totalWeight);
		hist_gt37_ht400_lpt->Fill(lep_pT->at(1),totalWeight);
	}
	hist_37_ht400_met_correction->Add(hist_incl_ht400_met);
	hist_37_ht400_met_correction->Divide(hist_gt37_ht400_met);
	hist_37_ht400_lpt_correction->Add(hist_incl_ht400_lpt);
	hist_37_ht400_lpt_correction->Divide(hist_gt37_ht400_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (HT<1200.) continue;
		//if (DPhi_METJetLeading<0.4) continue;
		//if (DPhi_METJetSecond<0.4) continue;
		hist_incl_ht1200_met->Fill(MET,totalWeight);
		hist_incl_ht1200_lpt->Fill(lep_pT->at(1),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_ht1200_met->Fill(MET,totalWeight);
		hist_gt37_ht1200_lpt->Fill(lep_pT->at(1),totalWeight);
	}
	hist_37_ht1200_met_correction->Add(hist_incl_ht1200_met);
	hist_37_ht1200_met_correction->Divide(hist_gt37_ht1200_met);
	hist_37_ht1200_lpt_correction->Add(hist_incl_ht1200_lpt);
	hist_37_ht1200_lpt_correction->Divide(hist_gt37_ht1200_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (jet_pT->at(0)<30.) continue;
		if (jet_pT->at(1)<30.) continue;
		if (mj0j1<60.) continue;
		if (mj0j1>100.) continue;
		if (MT2W<100.) continue;
		hist_incl_srhigh_met->Fill(MET,totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_srhigh_met->Fill(MET,totalWeight);
	}
	hist_37_srhigh_met_correction->Add(hist_incl_srhigh_met);
	hist_37_srhigh_met_correction->Divide(hist_gt37_srhigh_met);
	fZ.Close();

	if (isData==1) {
		cout << "Opening file           : " << TString(smearingPath)+"data/data_"+TString(ch)+".root"  << endl;
		TFile fZ( TString(smearingPath)+"data/data_"+TString(ch)+".root" );
		TTree*  tZ              = (TTree*)fZ.Get("BaselineTree");
		tZ->SetBranchStatus("*", 0);
		tZ->SetBranchStatus("totalWeight", 1);
		tZ->SetBranchStatus("jet_n", 1);
		tZ->SetBranchStatus("bjet_n", 1);
		tZ->SetBranchStatus("Z_pt", 1);
		tZ->SetBranchStatus("DPhi_METJetLeading", 1);
		tZ->SetBranchStatus("DPhi_METJetSecond", 1);
		tZ->SetBranchStatus("HT", 1);
		tZ->SetBranchStatus("mll", 1);
		tZ->SetBranchStatus("lep_pT"                 ,1);
		tZ->SetBranchStatus("jet_pT"                 ,1);
		tZ->SetBranchStatus("mj0j1", 1);
		tZ->SetBranchStatus("MT2W", 1);
		tZ->SetBranchAddress("totalWeight" ,&totalWeight);
		tZ->SetBranchAddress("jet_n" ,&jet_n);
		tZ->SetBranchAddress("bjet_n" ,&bjet_n);
		tZ->SetBranchAddress("Z_pt" ,&Z_pt);
		tZ->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tZ->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tZ->SetBranchAddress("HT" ,&HT);
		tZ->SetBranchAddress("mll" ,&mll);
		tZ->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tZ->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tZ->SetBranchAddress("mj0j1" ,&mj0j1);
		tZ->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_z_njet->Fill(jet_n,totalWeight);
			hist_bveto_z_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_z_pt->Fill(Z_pt,totalWeight);
			hist_bveto_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_bveto_z_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Add(hist_bveto_z_njet);
		hist_bveto_nbjetrw_correction->Add(hist_bveto_z_nbjet);
		hist_bveto_ptrw_correction->Add(hist_bveto_z_pt);
		hist_bveto_ptsmrw_correction->Add(hist_bveto_z_pt);
		hist_bveto_etrw_correction->Add(hist_bveto_z_et);
		hist_bveto_etsmrw_correction->Add(hist_bveto_z_et);
		hist_bveto_htrw_correction->Add(hist_bveto_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_z_njet->Fill(jet_n,totalWeight);
			hist_2j30_z_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_z_pt->Fill(Z_pt,totalWeight);
			hist_2j30_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_2j30_z_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Add(hist_2j30_z_njet);
		hist_2j30_nbjetrw_correction->Add(hist_2j30_z_nbjet);
		hist_2j30_ptrw_correction->Add(hist_2j30_z_pt);
		hist_2j30_ptsmrw_correction->Add(hist_2j30_z_pt);
		hist_2j30_etrw_correction->Add(hist_2j30_z_et);
		hist_2j30_etsmrw_correction->Add(hist_2j30_z_et);
		hist_2j30_htrw_correction->Add(hist_2j30_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_z_njet->Fill(jet_n,totalWeight);
			hist_ht200_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_z_pt->Fill(Z_pt,totalWeight);
			hist_ht200_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht200_z_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Add(hist_ht200_z_njet);
		hist_ht200_nbjetrw_correction->Add(hist_ht200_z_nbjet);
		hist_ht200_ptrw_correction->Add(hist_ht200_z_pt);
		hist_ht200_ptsmrw_correction->Add(hist_ht200_z_pt);
		hist_ht200_etrw_correction->Add(hist_ht200_z_et);
		hist_ht200_etsmrw_correction->Add(hist_ht200_z_et);
		hist_ht200_htrw_correction->Add(hist_ht200_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_z_njet->Fill(jet_n,totalWeight);
			hist_ht400_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_z_pt->Fill(Z_pt,totalWeight);
			hist_ht400_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht400_z_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Add(hist_ht400_z_njet);
		hist_ht400_nbjetrw_correction->Add(hist_ht400_z_nbjet);
		hist_ht400_ptrw_correction->Add(hist_ht400_z_pt);
		hist_ht400_ptsmrw_correction->Add(hist_ht400_z_pt);
		hist_ht400_etrw_correction->Add(hist_ht400_z_et);
		hist_ht400_etsmrw_correction->Add(hist_ht400_z_et);
		hist_ht400_htrw_correction->Add(hist_ht400_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_z_njet->Fill(jet_n,totalWeight);
			hist_ht1200_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_z_pt->Fill(Z_pt,totalWeight);
			hist_ht1200_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_z_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Add(hist_ht1200_z_njet);
		hist_ht1200_nbjetrw_correction->Add(hist_ht1200_z_nbjet);
		hist_ht1200_ptrw_correction->Add(hist_ht1200_z_pt);
		hist_ht1200_ptsmrw_correction->Add(hist_ht1200_z_pt);
		hist_ht1200_etrw_correction->Add(hist_ht1200_z_et);
		hist_ht1200_etsmrw_correction->Add(hist_ht1200_z_et);
		hist_ht1200_htrw_correction->Add(hist_ht1200_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_z_njet->Fill(jet_n,totalWeight);
			hist_srhigh_z_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_z_pt->Fill(Z_pt,totalWeight);
			hist_srhigh_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_z_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Add(hist_srhigh_z_njet);
		hist_srhigh_nbjetrw_correction->Add(hist_srhigh_z_nbjet);
		hist_srhigh_ptrw_correction->Add(hist_srhigh_z_pt);
		hist_srhigh_ptsmrw_correction->Add(hist_srhigh_z_pt);
		hist_srhigh_etrw_correction->Add(hist_srhigh_z_et);
		hist_srhigh_etsmrw_correction->Add(hist_srhigh_z_et);
		hist_srhigh_htrw_correction->Add(hist_srhigh_z_ht);
		fZ.Close();
		//cout << "Opening file           : " << TString(smearingPath)+"tt/tt"+TString(ch)+".root"        << endl;
		//TFile ftt( TString(smearingPath)+"tt/tt"+TString(ch)+".root" );
		//TTree*  ttt              = (TTree*)ftt.Get("BaselineTree");
		//ttt->SetBranchStatus("*", 0);
		//ttt->SetBranchStatus("totalWeight", 1);
		//ttt->SetBranchStatus("jet_n", 1);
		//ttt->SetBranchStatus("bjet_n", 1);
		//ttt->SetBranchStatus("Z_pt", 1);
		//ttt->SetBranchStatus("DPhi_METJetLeading", 1);
		//ttt->SetBranchStatus("DPhi_METJetSecond", 1);
		//ttt->SetBranchStatus("HT", 1);
		//ttt->SetBranchStatus("mll", 1);
		//ttt->SetBranchStatus("lep_pT"                 ,1);
		//ttt->SetBranchStatus("jet_pT"                 ,1);
		//ttt->SetBranchStatus("mj0j1", 1);
		//ttt->SetBranchStatus("MT2W", 1);
		//ttt->SetBranchAddress("totalWeight" ,&totalWeight);
		//ttt->SetBranchAddress("jet_n" ,&jet_n);
		//ttt->SetBranchAddress("bjet_n" ,&bjet_n);
		//ttt->SetBranchAddress("Z_pt" ,&Z_pt);
		//ttt->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		//ttt->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		//ttt->SetBranchAddress("HT" ,&HT);
		//ttt->SetBranchAddress("mll" ,&mll);
		//ttt->SetBranchAddress("lep_pT"          ,&lep_pT           );
		//ttt->SetBranchAddress("jet_pT"          ,&jet_pT           );
		//ttt->SetBranchAddress("mj0j1" ,&mj0j1);
		//ttt->SetBranchAddress("MT2W" ,&MT2W);
		//for (int entry=0;entry<ttt->GetEntries();entry++) {
		//	ttt->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	hist_bveto_tt_njet->Fill(jet_n,totalWeight);
		//	hist_bveto_tt_nbjet->Fill(bjet_n,totalWeight);
		//	hist_bveto_tt_pt->Fill(Z_pt,totalWeight);
		//	hist_bveto_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_bveto_tt_ht->Fill(HT,totalWeight);
		//}
		//hist_bveto_njetrw_correction->Add(hist_bveto_tt_njet,-1.*lumi);
		//hist_bveto_nbjetrw_correction->Add(hist_bveto_tt_nbjet,-1.*lumi);
		//hist_bveto_ptrw_correction->Add(hist_bveto_tt_pt,-1.*lumi);
		//hist_bveto_ptsmrw_correction->Add(hist_bveto_tt_pt,-1.*lumi);
		//hist_bveto_etrw_correction->Add(hist_bveto_tt_et,-1.*lumi);
		//hist_bveto_etsmrw_correction->Add(hist_bveto_tt_et,-1.*lumi);
		//hist_bveto_htrw_correction->Add(hist_bveto_tt_ht,-1.*lumi);
		//for (int entry=0;entry<ttt->GetEntries();entry++) {
		//	ttt->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (jet_pT->at(0)<30.) continue;
		//	if (jet_pT->at(1)<30.) continue;
		//	hist_2j30_tt_njet->Fill(jet_n,totalWeight);
		//	hist_2j30_tt_nbjet->Fill(bjet_n,totalWeight);
		//	hist_2j30_tt_pt->Fill(Z_pt,totalWeight);
		//	hist_2j30_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_2j30_tt_ht->Fill(HT,totalWeight);
		//}
		//hist_2j30_njetrw_correction->Add(hist_2j30_tt_njet,-1.*lumi);
		//hist_2j30_nbjetrw_correction->Add(hist_2j30_tt_nbjet,-1.*lumi);
		//hist_2j30_ptrw_correction->Add(hist_2j30_tt_pt,-1.*lumi);
		//hist_2j30_ptsmrw_correction->Add(hist_2j30_tt_pt,-1.*lumi);
		//hist_2j30_etrw_correction->Add(hist_2j30_tt_et,-1.*lumi);
		//hist_2j30_etsmrw_correction->Add(hist_2j30_tt_et,-1.*lumi);
		//hist_2j30_htrw_correction->Add(hist_2j30_tt_ht,-1.*lumi);
		//for (int entry=0;entry<ttt->GetEntries();entry++) {
		//	ttt->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (HT<200.) continue;
		//	//if (DPhi_METJetLeading<0.4) continue;
		//	//if (DPhi_METJetSecond<0.4) continue;
		//	hist_ht200_tt_njet->Fill(jet_n,totalWeight);
		//	hist_ht200_tt_nbjet->Fill(bjet_n,totalWeight);
		//	hist_ht200_tt_pt->Fill(Z_pt,totalWeight);
		//	hist_ht200_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_ht200_tt_ht->Fill(HT,totalWeight);
		//}
		//hist_ht200_njetrw_correction->Add(hist_ht200_tt_njet,-1.*lumi);
		//hist_ht200_nbjetrw_correction->Add(hist_ht200_tt_nbjet,-1.*lumi);
		//hist_ht200_ptrw_correction->Add(hist_ht200_tt_pt,-1.*lumi);
		//hist_ht200_ptsmrw_correction->Add(hist_ht200_tt_pt,-1.*lumi);
		//hist_ht200_etrw_correction->Add(hist_ht200_tt_et,-1.*lumi);
		//hist_ht200_etsmrw_correction->Add(hist_ht200_tt_et,-1.*lumi);
		//hist_ht200_htrw_correction->Add(hist_ht200_tt_ht,-1.*lumi);
		//for (int entry=0;entry<ttt->GetEntries();entry++) {
		//	ttt->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (HT<400.) continue;
		//	//if (DPhi_METJetLeading<0.4) continue;
		//	//if (DPhi_METJetSecond<0.4) continue;
		//	hist_ht400_tt_njet->Fill(jet_n,totalWeight);
		//	hist_ht400_tt_nbjet->Fill(bjet_n,totalWeight);
		//	hist_ht400_tt_pt->Fill(Z_pt,totalWeight);
		//	hist_ht400_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_ht400_tt_ht->Fill(HT,totalWeight);
		//}
		//hist_ht400_njetrw_correction->Add(hist_ht400_tt_njet,-1.*lumi);
		//hist_ht400_nbjetrw_correction->Add(hist_ht400_tt_nbjet,-1.*lumi);
		//hist_ht400_ptrw_correction->Add(hist_ht400_tt_pt,-1.*lumi);
		//hist_ht400_ptsmrw_correction->Add(hist_ht400_tt_pt,-1.*lumi);
		//hist_ht400_etrw_correction->Add(hist_ht400_tt_et,-1.*lumi);
		//hist_ht400_etsmrw_correction->Add(hist_ht400_tt_et,-1.*lumi);
		//hist_ht400_htrw_correction->Add(hist_ht400_tt_ht,-1.*lumi);
		//for (int entry=0;entry<ttt->GetEntries();entry++) {
		//	ttt->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (HT<1200.) continue;
		//	//if (DPhi_METJetLeading<0.4) continue;
		//	//if (DPhi_METJetSecond<0.4) continue;
		//	hist_ht1200_tt_njet->Fill(jet_n,totalWeight);
		//	hist_ht1200_tt_nbjet->Fill(bjet_n,totalWeight);
		//	hist_ht1200_tt_pt->Fill(Z_pt,totalWeight);
		//	hist_ht1200_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_ht1200_tt_ht->Fill(HT,totalWeight);
		//}
		//hist_ht1200_njetrw_correction->Add(hist_ht1200_tt_njet,-1.*lumi);
		//hist_ht1200_nbjetrw_correction->Add(hist_ht1200_tt_nbjet,-1.*lumi);
		//hist_ht1200_ptrw_correction->Add(hist_ht1200_tt_pt,-1.*lumi);
		//hist_ht1200_ptsmrw_correction->Add(hist_ht1200_tt_pt,-1.*lumi);
		//hist_ht1200_etrw_correction->Add(hist_ht1200_tt_et,-1.*lumi);
		//hist_ht1200_etsmrw_correction->Add(hist_ht1200_tt_et,-1.*lumi);
		//hist_ht1200_htrw_correction->Add(hist_ht1200_tt_ht,-1.*lumi);
		//for (int entry=0;entry<ttt->GetEntries();entry++) {
		//	ttt->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (jet_pT->at(0)<30.) continue;
		//	if (jet_pT->at(1)<30.) continue;
		//	if (mj0j1<60.) continue;
		//	if (mj0j1>100.) continue;
		//	if (MT2W<100.) continue;
		//	hist_srhigh_tt_njet->Fill(jet_n,totalWeight);
		//	hist_srhigh_tt_nbjet->Fill(bjet_n,totalWeight);
		//	hist_srhigh_tt_pt->Fill(Z_pt,totalWeight);
		//	hist_srhigh_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_srhigh_tt_ht->Fill(HT,totalWeight);
		//}
		//hist_srhigh_njetrw_correction->Add(hist_srhigh_tt_njet,-1.*lumi);
		//hist_srhigh_nbjetrw_correction->Add(hist_srhigh_tt_nbjet,-1.*lumi);
		//hist_srhigh_ptrw_correction->Add(hist_srhigh_tt_pt,-1.*lumi);
		//hist_srhigh_ptsmrw_correction->Add(hist_srhigh_tt_pt,-1.*lumi);
		//hist_srhigh_etrw_correction->Add(hist_srhigh_tt_et,-1.*lumi);
		//hist_srhigh_etsmrw_correction->Add(hist_srhigh_tt_et,-1.*lumi);
		//hist_srhigh_htrw_correction->Add(hist_srhigh_tt_ht,-1.*lumi);
		//ftt.Close();
		//cout << "Opening file           : " << TString(smearingPath)+"vv/vv"+TString(ch)+".root"       << endl;
		//TFile fvv( TString(smearingPath)+"vv/vv"+TString(ch)+".root" );
		//TTree*  tvv              = (TTree*)fvv.Get("BaselineTree");
		//tvv->SetBranchStatus("*", 0);
		//tvv->SetBranchStatus("totalWeight", 1);
		//tvv->SetBranchStatus("jet_n", 1);
		//tvv->SetBranchStatus("bjet_n", 1);
		//tvv->SetBranchStatus("Z_pt", 1);
		//tvv->SetBranchStatus("DPhi_METJetLeading", 1);
		//tvv->SetBranchStatus("DPhi_METJetSecond", 1);
		//tvv->SetBranchStatus("HT", 1);
		//tvv->SetBranchStatus("mll", 1);
		//tvv->SetBranchStatus("lep_pT"                 ,1);
		//tvv->SetBranchStatus("jet_pT"                 ,1);
		//tvv->SetBranchStatus("mj0j1", 1);
		//tvv->SetBranchStatus("MT2W", 1);
		//tvv->SetBranchAddress("totalWeight" ,&totalWeight);
		//tvv->SetBranchAddress("jet_n" ,&jet_n);
		//tvv->SetBranchAddress("bjet_n" ,&bjet_n);
		//tvv->SetBranchAddress("Z_pt" ,&Z_pt);
		//tvv->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		//tvv->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		//tvv->SetBranchAddress("HT" ,&HT);
		//tvv->SetBranchAddress("mll" ,&mll);
		//tvv->SetBranchAddress("lep_pT"          ,&lep_pT           );
		//tvv->SetBranchAddress("jet_pT"          ,&jet_pT           );
		//tvv->SetBranchAddress("mj0j1" ,&mj0j1);
		//tvv->SetBranchAddress("MT2W" ,&MT2W);
		//for (int entry=0;entry<tvv->GetEntries();entry++) {
		//	tvv->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	hist_bveto_vv_njet->Fill(jet_n,totalWeight);
		//	hist_bveto_vv_nbjet->Fill(bjet_n,totalWeight);
		//	hist_bveto_vv_pt->Fill(Z_pt,totalWeight);
		//	hist_bveto_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_bveto_vv_ht->Fill(HT,totalWeight);
		//}
		//hist_bveto_njetrw_correction->Add(hist_bveto_vv_njet,-1.*lumi);
		//hist_bveto_nbjetrw_correction->Add(hist_bveto_vv_nbjet,-1.*lumi);
		//hist_bveto_ptrw_correction->Add(hist_bveto_vv_pt,-1.*lumi);
		//hist_bveto_ptsmrw_correction->Add(hist_bveto_vv_pt,-1.*lumi);
		//hist_bveto_etrw_correction->Add(hist_bveto_vv_et,-1.*lumi);
		//hist_bveto_etsmrw_correction->Add(hist_bveto_vv_et,-1.*lumi);
		//hist_bveto_htrw_correction->Add(hist_bveto_vv_ht,-1.*lumi);
		//for (int entry=0;entry<tvv->GetEntries();entry++) {
		//	tvv->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (jet_pT->at(0)<30.) continue;
		//	if (jet_pT->at(1)<30.) continue;
		//	hist_2j30_vv_njet->Fill(jet_n,totalWeight);
		//	hist_2j30_vv_nbjet->Fill(bjet_n,totalWeight);
		//	hist_2j30_vv_pt->Fill(Z_pt,totalWeight);
		//	hist_2j30_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_2j30_vv_ht->Fill(HT,totalWeight);
		//}
		//hist_2j30_njetrw_correction->Add(hist_2j30_vv_njet,-1.*lumi);
		//hist_2j30_nbjetrw_correction->Add(hist_2j30_vv_nbjet,-1.*lumi);
		//hist_2j30_ptrw_correction->Add(hist_2j30_vv_pt,-1.*lumi);
		//hist_2j30_ptsmrw_correction->Add(hist_2j30_vv_pt,-1.*lumi);
		//hist_2j30_etrw_correction->Add(hist_2j30_vv_et,-1.*lumi);
		//hist_2j30_etsmrw_correction->Add(hist_2j30_vv_et,-1.*lumi);
		//hist_2j30_htrw_correction->Add(hist_2j30_vv_ht,-1.*lumi);
		//for (int entry=0;entry<tvv->GetEntries();entry++) {
		//	tvv->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (HT<200.) continue;
		//	//if (DPhi_METJetLeading<0.4) continue;
		//	//if (DPhi_METJetSecond<0.4) continue;
		//	hist_ht200_vv_njet->Fill(jet_n,totalWeight);
		//	hist_ht200_vv_nbjet->Fill(bjet_n,totalWeight);
		//	hist_ht200_vv_pt->Fill(Z_pt,totalWeight);
		//	hist_ht200_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_ht200_vv_ht->Fill(HT,totalWeight);
		//}
		//hist_ht200_njetrw_correction->Add(hist_ht200_vv_njet,-1.*lumi);
		//hist_ht200_nbjetrw_correction->Add(hist_ht200_vv_nbjet,-1.*lumi);
		//hist_ht200_ptrw_correction->Add(hist_ht200_vv_pt,-1.*lumi);
		//hist_ht200_ptsmrw_correction->Add(hist_ht200_vv_pt,-1.*lumi);
		//hist_ht200_etrw_correction->Add(hist_ht200_vv_et,-1.*lumi);
		//hist_ht200_etsmrw_correction->Add(hist_ht200_vv_et,-1.*lumi);
		//hist_ht200_htrw_correction->Add(hist_ht200_vv_ht,-1.*lumi);
		//for (int entry=0;entry<tvv->GetEntries();entry++) {
		//	tvv->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (HT<400.) continue;
		//	//if (DPhi_METJetLeading<0.4) continue;
		//	//if (DPhi_METJetSecond<0.4) continue;
		//	hist_ht400_vv_njet->Fill(jet_n,totalWeight);
		//	hist_ht400_vv_nbjet->Fill(bjet_n,totalWeight);
		//	hist_ht400_vv_pt->Fill(Z_pt,totalWeight);
		//	hist_ht400_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_ht400_vv_ht->Fill(HT,totalWeight);
		//}
		//hist_ht400_njetrw_correction->Add(hist_ht400_vv_njet,-1.*lumi);
		//hist_ht400_nbjetrw_correction->Add(hist_ht400_vv_nbjet,-1.*lumi);
		//hist_ht400_ptrw_correction->Add(hist_ht400_vv_pt,-1.*lumi);
		//hist_ht400_ptsmrw_correction->Add(hist_ht400_vv_pt,-1.*lumi);
		//hist_ht400_etrw_correction->Add(hist_ht400_vv_et,-1.*lumi);
		//hist_ht400_etsmrw_correction->Add(hist_ht400_vv_et,-1.*lumi);
		//hist_ht400_htrw_correction->Add(hist_ht400_vv_ht,-1.*lumi);
		//for (int entry=0;entry<tvv->GetEntries();entry++) {
		//	tvv->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (HT<1200.) continue;
		//	//if (DPhi_METJetLeading<0.4) continue;
		//	//if (DPhi_METJetSecond<0.4) continue;
		//	hist_ht1200_vv_njet->Fill(jet_n,totalWeight);
		//	hist_ht1200_vv_nbjet->Fill(bjet_n,totalWeight);
		//	hist_ht1200_vv_pt->Fill(Z_pt,totalWeight);
		//	hist_ht1200_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_ht1200_vv_ht->Fill(HT,totalWeight);
		//}
		//hist_ht1200_njetrw_correction->Add(hist_ht1200_vv_njet,-1.*lumi);
		//hist_ht1200_nbjetrw_correction->Add(hist_ht1200_vv_nbjet,-1.*lumi);
		//hist_ht1200_ptrw_correction->Add(hist_ht1200_vv_pt,-1.*lumi);
		//hist_ht1200_ptsmrw_correction->Add(hist_ht1200_vv_pt,-1.*lumi);
		//hist_ht1200_etrw_correction->Add(hist_ht1200_vv_et,-1.*lumi);
		//hist_ht1200_etsmrw_correction->Add(hist_ht1200_vv_et,-1.*lumi);
		//hist_ht1200_htrw_correction->Add(hist_ht1200_vv_ht,-1.*lumi);
		//for (int entry=0;entry<tvv->GetEntries();entry++) {
		//	tvv->GetEntry(entry);
		//	if (jet_n==0) continue;
		//	if (jet_n==1) continue;
		//	if (bjet_n!=0) continue;
		//	if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		//	if (lep_pT->at(1)<second_lep_pt_cut) continue;
		//	if (jet_pT->at(0)<30.) continue;
		//	if (jet_pT->at(1)<30.) continue;
		//	if (mj0j1<60.) continue;
		//	if (mj0j1>100.) continue;
		//	if (MT2W<100.) continue;
		//	hist_srhigh_vv_njet->Fill(jet_n,totalWeight);
		//	hist_srhigh_vv_nbjet->Fill(bjet_n,totalWeight);
		//	hist_srhigh_vv_pt->Fill(Z_pt,totalWeight);
		//	hist_srhigh_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
		//	hist_srhigh_vv_ht->Fill(HT,totalWeight);
		//}
		//hist_srhigh_njetrw_correction->Add(hist_srhigh_vv_njet,-1.*lumi);
		//hist_srhigh_nbjetrw_correction->Add(hist_srhigh_vv_nbjet,-1.*lumi);
		//hist_srhigh_ptrw_correction->Add(hist_srhigh_vv_pt,-1.*lumi);
		//hist_srhigh_ptsmrw_correction->Add(hist_srhigh_vv_pt,-1.*lumi);
		//hist_srhigh_etrw_correction->Add(hist_srhigh_vv_et,-1.*lumi);
		//hist_srhigh_etsmrw_correction->Add(hist_srhigh_vv_et,-1.*lumi);
		//hist_srhigh_htrw_correction->Add(hist_srhigh_vv_ht,-1.*lumi);
		//fvv.Close();
		TFile fPhoton( TString(outputPath)+"gdata/gdata_"+TString(ch)+TString(photon_tag)+".root" );
		TTree*  tPhoton              = (TTree*)fPhoton.Get("BaselineTree");
		tPhoton->SetBranchStatus("*", 0);
		tPhoton->SetBranchStatus("totalWeight", 1);
		tPhoton->SetBranchStatus("jet_n", 1);
		tPhoton->SetBranchStatus("bjet_n", 1);
		tPhoton->SetBranchStatus("gamma_pt", 1);
		tPhoton->SetBranchStatus("Z_pt", 1);
		tPhoton->SetBranchStatus("DPhi_METJetLeading", 1);
		tPhoton->SetBranchStatus("DPhi_METJetSecond", 1);
		tPhoton->SetBranchStatus("HT", 1);
		tPhoton->SetBranchStatus("mll", 1);
		tPhoton->SetBranchStatus("lep_pT"                 ,1);
		tPhoton->SetBranchStatus("jet_pT"                 ,1);
		tPhoton->SetBranchStatus("mj0j1", 1);
		tPhoton->SetBranchStatus("MT2W", 1);
		tPhoton->SetBranchAddress("totalWeight" ,&totalWeight);
		tPhoton->SetBranchAddress("jet_n" ,&jet_n);
		tPhoton->SetBranchAddress("bjet_n" ,&bjet_n);
		tPhoton->SetBranchAddress("gamma_pt" ,&gamma_pt);
		tPhoton->SetBranchAddress("Z_pt" ,&gamma_pt_smear);
		tPhoton->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tPhoton->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tPhoton->SetBranchAddress("HT" ,&HT);
		tPhoton->SetBranchAddress("mll" ,&mll);
		tPhoton->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tPhoton->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tPhoton->SetBranchAddress("mj0j1" ,&mj0j1);
		tPhoton->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_photon_njet->Fill(jet_n,totalWeight);
			hist_bveto_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_photon_pt->Fill(gamma_pt,totalWeight);
			hist_bveto_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_bveto_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Divide(hist_bveto_photon_njet);
		hist_bveto_nbjetrw_correction->Divide(hist_bveto_photon_nbjet);
		hist_bveto_ptrw_correction->Divide(hist_bveto_photon_pt);
		hist_bveto_ptsmrw_correction->Divide(hist_bveto_photon_ptsm);
		hist_bveto_etrw_correction->Divide(hist_bveto_photon_et);
		hist_bveto_etsmrw_correction->Divide(hist_bveto_photon_etsm);
		hist_bveto_htrw_correction->Divide(hist_bveto_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_photon_njet->Fill(jet_n,totalWeight);
			hist_2j30_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_photon_pt->Fill(gamma_pt,totalWeight);
			hist_2j30_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_2j30_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_2j30_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_2j30_photon_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Divide(hist_2j30_photon_njet);
		hist_2j30_nbjetrw_correction->Divide(hist_2j30_photon_nbjet);
		hist_2j30_ptrw_correction->Divide(hist_2j30_photon_pt);
		hist_2j30_ptsmrw_correction->Divide(hist_2j30_photon_ptsm);
		hist_2j30_etrw_correction->Divide(hist_2j30_photon_et);
		hist_2j30_etsmrw_correction->Divide(hist_2j30_photon_etsm);
		hist_2j30_htrw_correction->Divide(hist_2j30_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_photon_njet->Fill(jet_n,totalWeight);
			hist_ht200_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht200_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht200_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht200_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht200_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Divide(hist_ht200_photon_njet);
		hist_ht200_nbjetrw_correction->Divide(hist_ht200_photon_nbjet);
		hist_ht200_ptrw_correction->Divide(hist_ht200_photon_pt);
		hist_ht200_ptsmrw_correction->Divide(hist_ht200_photon_ptsm);
		hist_ht200_etrw_correction->Divide(hist_ht200_photon_et);
		hist_ht200_etsmrw_correction->Divide(hist_ht200_photon_etsm);
		hist_ht200_htrw_correction->Divide(hist_ht200_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_photon_njet->Fill(jet_n,totalWeight);
			hist_ht400_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht400_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht400_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht400_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht400_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Divide(hist_ht400_photon_njet);
		hist_ht400_nbjetrw_correction->Divide(hist_ht400_photon_nbjet);
		hist_ht400_ptrw_correction->Divide(hist_ht400_photon_pt);
		hist_ht400_ptsmrw_correction->Divide(hist_ht400_photon_ptsm);
		hist_ht400_etrw_correction->Divide(hist_ht400_photon_et);
		hist_ht400_etsmrw_correction->Divide(hist_ht400_photon_etsm);
		hist_ht400_htrw_correction->Divide(hist_ht400_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_photon_njet->Fill(jet_n,totalWeight);
			hist_ht1200_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht1200_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht1200_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht1200_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Divide(hist_ht1200_photon_njet);
		hist_ht1200_nbjetrw_correction->Divide(hist_ht1200_photon_nbjet);
		hist_ht1200_ptrw_correction->Divide(hist_ht1200_photon_pt);
		hist_ht1200_ptsmrw_correction->Divide(hist_ht1200_photon_ptsm);
		hist_ht1200_etrw_correction->Divide(hist_ht1200_photon_et);
		hist_ht1200_etsmrw_correction->Divide(hist_ht1200_photon_etsm);
		hist_ht1200_htrw_correction->Divide(hist_ht1200_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_photon_njet->Fill(jet_n,totalWeight);
			hist_srhigh_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_photon_pt->Fill(gamma_pt,totalWeight);
			hist_srhigh_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_srhigh_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_srhigh_photon_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Divide(hist_srhigh_photon_njet);
		hist_srhigh_nbjetrw_correction->Divide(hist_srhigh_photon_nbjet);
		hist_srhigh_ptrw_correction->Divide(hist_srhigh_photon_pt);
		hist_srhigh_ptsmrw_correction->Divide(hist_srhigh_photon_ptsm);
		hist_srhigh_etrw_correction->Divide(hist_srhigh_photon_et);
		hist_srhigh_etsmrw_correction->Divide(hist_srhigh_photon_etsm);
		hist_srhigh_htrw_correction->Divide(hist_srhigh_photon_ht);
		fPhoton.Close();
	}
	else {
		TFile fZ( TString(smearingPath)+"zjets/zjets_"+TString(ch)+".root" );
		TTree*  tZ              = (TTree*)fZ.Get("BaselineTree");
		tZ->SetBranchStatus("*", 0);
		tZ->SetBranchStatus("totalWeight", 1);
		tZ->SetBranchStatus("jet_n", 1);
		tZ->SetBranchStatus("bjet_n", 1);
		tZ->SetBranchStatus("Z_pt", 1);
		tZ->SetBranchStatus("DPhi_METJetLeading", 1);
		tZ->SetBranchStatus("DPhi_METJetSecond", 1);
		tZ->SetBranchStatus("HT", 1);
		tZ->SetBranchStatus("mll", 1);
		tZ->SetBranchStatus("lep_pT"                 ,1);
		tZ->SetBranchStatus("jet_pT"                 ,1);
		tZ->SetBranchStatus("mj0j1", 1);
		tZ->SetBranchStatus("MT2W", 1);
		tZ->SetBranchAddress("totalWeight" ,&totalWeight);
		tZ->SetBranchAddress("jet_n" ,&jet_n);
		tZ->SetBranchAddress("bjet_n" ,&bjet_n);
		tZ->SetBranchAddress("Z_pt" ,&Z_pt);
		tZ->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tZ->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tZ->SetBranchAddress("HT" ,&HT);
		tZ->SetBranchAddress("mll" ,&mll);
		tZ->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tZ->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tZ->SetBranchAddress("mj0j1" ,&mj0j1);
		tZ->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_z_njet->Fill(jet_n,totalWeight);
			hist_bveto_z_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_z_pt->Fill(Z_pt,totalWeight);
			hist_bveto_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_bveto_z_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Add(hist_bveto_z_njet);
		hist_bveto_nbjetrw_correction->Add(hist_bveto_z_nbjet);
		hist_bveto_ptrw_correction->Add(hist_bveto_z_pt);
		hist_bveto_ptsmrw_correction->Add(hist_bveto_z_pt);
		hist_bveto_etrw_correction->Add(hist_bveto_z_et);
		hist_bveto_etsmrw_correction->Add(hist_bveto_z_et);
		hist_bveto_htrw_correction->Add(hist_bveto_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_z_njet->Fill(jet_n,totalWeight);
			hist_2j30_z_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_z_pt->Fill(Z_pt,totalWeight);
			hist_2j30_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_2j30_z_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Add(hist_2j30_z_njet);
		hist_2j30_nbjetrw_correction->Add(hist_2j30_z_nbjet);
		hist_2j30_ptrw_correction->Add(hist_2j30_z_pt);
		hist_2j30_ptsmrw_correction->Add(hist_2j30_z_pt);
		hist_2j30_etrw_correction->Add(hist_2j30_z_et);
		hist_2j30_etsmrw_correction->Add(hist_2j30_z_et);
		hist_2j30_htrw_correction->Add(hist_2j30_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_z_njet->Fill(jet_n,totalWeight);
			hist_ht200_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_z_pt->Fill(Z_pt,totalWeight);
			hist_ht200_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht200_z_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Add(hist_ht200_z_njet);
		hist_ht200_nbjetrw_correction->Add(hist_ht200_z_nbjet);
		hist_ht200_ptrw_correction->Add(hist_ht200_z_pt);
		hist_ht200_ptsmrw_correction->Add(hist_ht200_z_pt);
		hist_ht200_etrw_correction->Add(hist_ht200_z_et);
		hist_ht200_etsmrw_correction->Add(hist_ht200_z_et);
		hist_ht200_htrw_correction->Add(hist_ht200_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_z_njet->Fill(jet_n,totalWeight);
			hist_ht400_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_z_pt->Fill(Z_pt,totalWeight);
			hist_ht400_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht400_z_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Add(hist_ht400_z_njet);
		hist_ht400_nbjetrw_correction->Add(hist_ht400_z_nbjet);
		hist_ht400_ptrw_correction->Add(hist_ht400_z_pt);
		hist_ht400_ptsmrw_correction->Add(hist_ht400_z_pt);
		hist_ht400_etrw_correction->Add(hist_ht400_z_et);
		hist_ht400_etsmrw_correction->Add(hist_ht400_z_et);
		hist_ht400_htrw_correction->Add(hist_ht400_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_z_njet->Fill(jet_n,totalWeight);
			hist_ht1200_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_z_pt->Fill(Z_pt,totalWeight);
			hist_ht1200_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_z_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Add(hist_ht1200_z_njet);
		hist_ht1200_nbjetrw_correction->Add(hist_ht1200_z_nbjet);
		hist_ht1200_ptrw_correction->Add(hist_ht1200_z_pt);
		hist_ht1200_ptsmrw_correction->Add(hist_ht1200_z_pt);
		hist_ht1200_etrw_correction->Add(hist_ht1200_z_et);
		hist_ht1200_etsmrw_correction->Add(hist_ht1200_z_et);
		hist_ht1200_htrw_correction->Add(hist_ht1200_z_ht);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_z_njet->Fill(jet_n,totalWeight);
			hist_srhigh_z_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_z_pt->Fill(Z_pt,totalWeight);
			hist_srhigh_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_z_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Add(hist_srhigh_z_njet);
		hist_srhigh_nbjetrw_correction->Add(hist_srhigh_z_nbjet);
		hist_srhigh_ptrw_correction->Add(hist_srhigh_z_pt);
		hist_srhigh_ptsmrw_correction->Add(hist_srhigh_z_pt);
		hist_srhigh_etrw_correction->Add(hist_srhigh_z_et);
		hist_srhigh_etsmrw_correction->Add(hist_srhigh_z_et);
		hist_srhigh_htrw_correction->Add(hist_srhigh_z_ht);
		fZ.Close();
		TFile fPhoton( TString(outputPath)+"gmc/gmc_"+TString(ch)+TString(photon_tag)+".root" );
		TTree*  tPhoton              = (TTree*)fPhoton.Get("BaselineTree");
		tPhoton->SetBranchStatus("*", 0);
		tPhoton->SetBranchStatus("totalWeight", 1);
		tPhoton->SetBranchStatus("jet_n", 1);
		tPhoton->SetBranchStatus("bjet_n", 1);
		tPhoton->SetBranchStatus("gamma_pt", 1);
		tPhoton->SetBranchStatus("Z_pt", 1);
		tPhoton->SetBranchStatus("DPhi_METJetLeading", 1);
		tPhoton->SetBranchStatus("DPhi_METJetSecond", 1);
		tPhoton->SetBranchStatus("HT", 1);
		tPhoton->SetBranchStatus("mll", 1);
		tPhoton->SetBranchStatus("lep_pT"                 ,1);
		tPhoton->SetBranchStatus("jet_pT"                 ,1);
		tPhoton->SetBranchStatus("mj0j1", 1);
		tPhoton->SetBranchStatus("MT2W", 1);
		tPhoton->SetBranchAddress("totalWeight" ,&totalWeight);
		tPhoton->SetBranchAddress("jet_n" ,&jet_n);
		tPhoton->SetBranchAddress("bjet_n" ,&bjet_n);
		tPhoton->SetBranchAddress("gamma_pt" ,&gamma_pt);
		tPhoton->SetBranchAddress("Z_pt" ,&gamma_pt_smear);
		tPhoton->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tPhoton->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tPhoton->SetBranchAddress("HT" ,&HT);
		tPhoton->SetBranchAddress("mll" ,&mll);
		tPhoton->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tPhoton->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tPhoton->SetBranchAddress("mj0j1" ,&mj0j1);
		tPhoton->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_photon_njet->Fill(jet_n,totalWeight);
			hist_bveto_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_photon_pt->Fill(gamma_pt,totalWeight);
			hist_bveto_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_bveto_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Divide(hist_bveto_photon_njet);
		hist_bveto_nbjetrw_correction->Divide(hist_bveto_photon_nbjet);
		hist_bveto_ptrw_correction->Divide(hist_bveto_photon_pt);
		hist_bveto_ptsmrw_correction->Divide(hist_bveto_photon_ptsm);
		hist_bveto_etrw_correction->Divide(hist_bveto_photon_et);
		hist_bveto_etsmrw_correction->Divide(hist_bveto_photon_etsm);
		hist_bveto_htrw_correction->Divide(hist_bveto_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_photon_njet->Fill(jet_n,totalWeight);
			hist_2j30_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_photon_pt->Fill(gamma_pt,totalWeight);
			hist_2j30_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_2j30_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_2j30_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_2j30_photon_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Divide(hist_2j30_photon_njet);
		hist_2j30_nbjetrw_correction->Divide(hist_2j30_photon_nbjet);
		hist_2j30_ptrw_correction->Divide(hist_2j30_photon_pt);
		hist_2j30_ptsmrw_correction->Divide(hist_2j30_photon_ptsm);
		hist_2j30_etrw_correction->Divide(hist_2j30_photon_et);
		hist_2j30_etsmrw_correction->Divide(hist_2j30_photon_etsm);
		hist_2j30_htrw_correction->Divide(hist_2j30_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//std::cout << "totalWeight = " << totalWeight << std::endl;
			//std::cout << "gamma_pt = " << gamma_pt << std::endl;
			//std::cout << "lep_pT->at(0) = " << lep_pT->at(0) << std::endl;
			//std::cout << "lep_pT->at(1) = " << lep_pT->at(1) << std::endl;
			//std::cout << "HT = " << HT << std::endl;
			//std::cout << "jet_n = " << jet_n << std::endl;
			//std::cout << "bjet_n = " << bjet_n << std::endl;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_photon_njet->Fill(jet_n,totalWeight);
			hist_ht200_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht200_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht200_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht200_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht200_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Divide(hist_ht200_photon_njet);
		hist_ht200_nbjetrw_correction->Divide(hist_ht200_photon_nbjet);
		hist_ht200_ptrw_correction->Divide(hist_ht200_photon_pt);
		hist_ht200_ptsmrw_correction->Divide(hist_ht200_photon_ptsm);
		hist_ht200_etrw_correction->Divide(hist_ht200_photon_et);
		hist_ht200_etsmrw_correction->Divide(hist_ht200_photon_etsm);
		hist_ht200_htrw_correction->Divide(hist_ht200_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_photon_njet->Fill(jet_n,totalWeight);
			hist_ht400_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht400_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht400_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht400_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht400_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Divide(hist_ht400_photon_njet);
		hist_ht400_nbjetrw_correction->Divide(hist_ht400_photon_nbjet);
		hist_ht400_ptrw_correction->Divide(hist_ht400_photon_pt);
		hist_ht400_ptsmrw_correction->Divide(hist_ht400_photon_ptsm);
		hist_ht400_etrw_correction->Divide(hist_ht400_photon_et);
		hist_ht400_etsmrw_correction->Divide(hist_ht400_photon_etsm);
		hist_ht400_htrw_correction->Divide(hist_ht400_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_photon_njet->Fill(jet_n,totalWeight);
			hist_ht1200_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht1200_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht1200_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht1200_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Divide(hist_ht1200_photon_njet);
		hist_ht1200_nbjetrw_correction->Divide(hist_ht1200_photon_nbjet);
		hist_ht1200_ptrw_correction->Divide(hist_ht1200_photon_pt);
		hist_ht1200_ptsmrw_correction->Divide(hist_ht1200_photon_ptsm);
		hist_ht1200_etrw_correction->Divide(hist_ht1200_photon_et);
		hist_ht1200_etsmrw_correction->Divide(hist_ht1200_photon_etsm);
		hist_ht1200_htrw_correction->Divide(hist_ht1200_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_photon_njet->Fill(jet_n,totalWeight);
			hist_srhigh_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_photon_pt->Fill(gamma_pt,totalWeight);
			hist_srhigh_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_srhigh_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_srhigh_photon_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Divide(hist_srhigh_photon_njet);
		hist_srhigh_nbjetrw_correction->Divide(hist_srhigh_photon_nbjet);
		hist_srhigh_ptrw_correction->Divide(hist_srhigh_photon_pt);
		hist_srhigh_ptsmrw_correction->Divide(hist_srhigh_photon_ptsm);
		hist_srhigh_etrw_correction->Divide(hist_srhigh_photon_et);
		hist_srhigh_etsmrw_correction->Divide(hist_srhigh_photon_etsm);
		hist_srhigh_htrw_correction->Divide(hist_srhigh_photon_ht);
		fPhoton.Close();
	}

}
