
void GetReweightingHistogram_SF(string ch, int isData, double lumi, string photon_tag) {

	TFile fZ( TString(outputPath)+"zjets/zsf.root" );
	TTree*  tZ              = (TTree*)fZ.Get("BaselineTree");
	tZ->SetBranchStatus("*", 0);
	tZ->SetBranchStatus("totalWeight", 1);
	tZ->SetBranchStatus("jet_n", 1);
	tZ->SetBranchStatus("bjet_n", 1);
	tZ->SetBranchStatus("Z_pt", 1);
	tZ->SetBranchStatus("DPhi_METJetLeading", 1);
	tZ->SetBranchStatus("DPhi_METJetSecond", 1);
	tZ->SetBranchStatus("HT", 1);
	tZ->SetBranchStatus("MET", 1);
	tZ->SetBranchStatus("mll", 1);
	tZ->SetBranchStatus("lep_pT"                 ,1);
	tZ->SetBranchStatus("jet_pT"                 ,1);
	tZ->SetBranchStatus("mj0j1", 1);
	tZ->SetBranchStatus("MT2W", 1);
	tZ->SetBranchAddress("totalWeight" ,&totalWeight);
	tZ->SetBranchAddress("jet_n" ,&jet_n);
	tZ->SetBranchAddress("bjet_n" ,&bjet_n);
	tZ->SetBranchAddress("Z_pt" ,&Z_pt);
	tZ->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
	tZ->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
	tZ->SetBranchAddress("HT" ,&HT);
	tZ->SetBranchAddress("MET" ,&MET);
	tZ->SetBranchAddress("mll" ,&mll);
	tZ->SetBranchAddress("lep_pT"          ,&lep_pT           );
	tZ->SetBranchAddress("jet_pT"          ,&jet_pT           );
	tZ->SetBranchAddress("mj0j1" ,&mj0j1);
	tZ->SetBranchAddress("MT2W" ,&MT2W);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		hist_incl_bveto_met->Fill(MET,totalWeight);
		hist_incl_bveto_lpt->Fill(lep_pT->at(0),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_bveto_met->Fill(MET,totalWeight);
		hist_gt37_bveto_lpt->Fill(lep_pT->at(0),totalWeight);
	}
	hist_37_bveto_met_correction->Add(hist_incl_bveto_met);
	hist_37_bveto_met_correction->Divide(hist_gt37_bveto_met);
	hist_37_bveto_lpt_correction->Add(hist_incl_bveto_lpt);
	hist_37_bveto_lpt_correction->Divide(hist_gt37_bveto_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (jet_pT->at(0)<30.) continue;
		if (jet_pT->at(1)<30.) continue;
		hist_incl_2j30_met->Fill(MET,totalWeight);
		hist_incl_2j30_lpt->Fill(lep_pT->at(1),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_2j30_met->Fill(MET,totalWeight);
		hist_gt37_2j30_lpt->Fill(lep_pT->at(1),totalWeight);
	}
	hist_37_2j30_met_correction->Add(hist_incl_2j30_met);
	hist_37_2j30_met_correction->Divide(hist_gt37_2j30_met);
	hist_37_2j30_lpt_correction->Add(hist_incl_2j30_lpt);
	hist_37_2j30_lpt_correction->Divide(hist_gt37_2j30_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (HT<200.) continue;
		//if (DPhi_METJetLeading<0.4) continue;
		//if (DPhi_METJetSecond<0.4) continue;
		hist_incl_ht200_met->Fill(MET,totalWeight);
		hist_incl_ht200_lpt->Fill(lep_pT->at(1),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_ht200_met->Fill(MET,totalWeight);
		hist_gt37_ht200_lpt->Fill(lep_pT->at(1),totalWeight);
	}
	hist_37_ht200_met_correction->Add(hist_incl_ht200_met);
	hist_37_ht200_met_correction->Divide(hist_gt37_ht200_met);
	hist_37_ht200_lpt_correction->Add(hist_incl_ht200_lpt);
	hist_37_ht200_lpt_correction->Divide(hist_gt37_ht200_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (HT<400.) continue;
		//if (DPhi_METJetLeading<0.4) continue;
		//if (DPhi_METJetSecond<0.4) continue;
		hist_incl_ht400_met->Fill(MET,totalWeight);
		hist_incl_ht400_lpt->Fill(lep_pT->at(1),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_ht400_met->Fill(MET,totalWeight);
		hist_gt37_ht400_lpt->Fill(lep_pT->at(1),totalWeight);
	}
	hist_37_ht400_met_correction->Add(hist_incl_ht400_met);
	hist_37_ht400_met_correction->Divide(hist_gt37_ht400_met);
	hist_37_ht400_lpt_correction->Add(hist_incl_ht400_lpt);
	hist_37_ht400_lpt_correction->Divide(hist_gt37_ht400_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (HT<1200.) continue;
		//if (DPhi_METJetLeading<0.4) continue;
		//if (DPhi_METJetSecond<0.4) continue;
		hist_incl_ht1200_met->Fill(MET,totalWeight);
		hist_incl_ht1200_lpt->Fill(lep_pT->at(1),totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_ht1200_met->Fill(MET,totalWeight);
		hist_gt37_ht1200_lpt->Fill(lep_pT->at(1),totalWeight);
	}
	hist_37_ht1200_met_correction->Add(hist_incl_ht1200_met);
	hist_37_ht1200_met_correction->Divide(hist_gt37_ht1200_met);
	hist_37_ht1200_lpt_correction->Add(hist_incl_ht1200_lpt);
	hist_37_ht1200_lpt_correction->Divide(hist_gt37_ht1200_lpt);
	for (int entry=0;entry<tZ->GetEntries();entry++) {
		tZ->GetEntry(entry);
		if (jet_n==0) continue;
		if (jet_n==1) continue;
		if (bjet_n!=0) continue;
		if (lep_pT->at(0)<leading_lep_pt_cut) continue;
		if (lep_pT->at(1)<second_lep_pt_cut) continue;
		if (jet_pT->at(0)<30.) continue;
		if (jet_pT->at(1)<30.) continue;
		if (mj0j1<60.) continue;
		if (mj0j1>100.) continue;
		if (MT2W<100.) continue;
		hist_incl_srhigh_met->Fill(MET,totalWeight);
		if (Z_pt<37.) continue;
		if (Z_pt<50.) continue;
		hist_gt37_srhigh_met->Fill(MET,totalWeight);
	}
	hist_37_srhigh_met_correction->Add(hist_incl_srhigh_met);
	hist_37_srhigh_met_correction->Divide(hist_gt37_srhigh_met);
	fZ.Close();

	if (isData==1) {
		cout << "Opening file           : " << TString(outputPath)+"data/data_sf.root"  << endl;
		TFile fZ( TString(outputPath)+"data/data_sf.root" );
		TTree*  tZ              = (TTree*)fZ.Get("BaselineTree");
		tZ->SetBranchStatus("*", 0);
		tZ->SetBranchStatus("totalWeight", 1);
		tZ->SetBranchStatus("jet_n", 1);
		tZ->SetBranchStatus("bjet_n", 1);
		tZ->SetBranchStatus("Z_pt", 1);
		tZ->SetBranchStatus("DPhi_METJetLeading", 1);
		tZ->SetBranchStatus("DPhi_METJetSecond", 1);
		tZ->SetBranchStatus("HT", 1);
		tZ->SetBranchStatus("mll", 1);
		tZ->SetBranchStatus("lep_pT"                 ,1);
		tZ->SetBranchStatus("jet_pT"                 ,1);
		tZ->SetBranchStatus("mj0j1", 1);
		tZ->SetBranchStatus("MT2W", 1);
		tZ->SetBranchAddress("totalWeight" ,&totalWeight);
		tZ->SetBranchAddress("jet_n" ,&jet_n);
		tZ->SetBranchAddress("bjet_n" ,&bjet_n);
		tZ->SetBranchAddress("Z_pt" ,&Z_pt);
		tZ->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tZ->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tZ->SetBranchAddress("HT" ,&HT);
		tZ->SetBranchAddress("mll" ,&mll);
		tZ->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tZ->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tZ->SetBranchAddress("mj0j1" ,&mj0j1);
		tZ->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_z_njet->Fill(jet_n,totalWeight);
			hist_bveto_z_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_z_pt->Fill(Z_pt,totalWeight);
			hist_bveto_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_bveto_z_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Add(hist_bveto_z_njet,0.5);
		hist_bveto_nbjetrw_correction->Add(hist_bveto_z_nbjet,0.5);
		hist_bveto_ptrw_correction->Add(hist_bveto_z_pt,0.5);
		hist_bveto_ptsmrw_correction->Add(hist_bveto_z_pt,0.5);
		hist_bveto_etrw_correction->Add(hist_bveto_z_et,0.5);
		hist_bveto_etsmrw_correction->Add(hist_bveto_z_et,0.5);
		hist_bveto_htrw_correction->Add(hist_bveto_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_z_njet->Fill(jet_n,totalWeight);
			hist_2j30_z_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_z_pt->Fill(Z_pt,totalWeight);
			hist_2j30_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_2j30_z_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Add(hist_2j30_z_njet,0.5);
		hist_2j30_nbjetrw_correction->Add(hist_2j30_z_nbjet,0.5);
		hist_2j30_ptrw_correction->Add(hist_2j30_z_pt,0.5);
		hist_2j30_ptsmrw_correction->Add(hist_2j30_z_pt,0.5);
		hist_2j30_etrw_correction->Add(hist_2j30_z_et,0.5);
		hist_2j30_etsmrw_correction->Add(hist_2j30_z_et,0.5);
		hist_2j30_htrw_correction->Add(hist_2j30_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_z_njet->Fill(jet_n,totalWeight);
			hist_ht200_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_z_pt->Fill(Z_pt,totalWeight);
			hist_ht200_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht200_z_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Add(hist_ht200_z_njet,0.5);
		hist_ht200_nbjetrw_correction->Add(hist_ht200_z_nbjet,0.5);
		hist_ht200_ptrw_correction->Add(hist_ht200_z_pt,0.5);
		hist_ht200_ptsmrw_correction->Add(hist_ht200_z_pt,0.5);
		hist_ht200_etrw_correction->Add(hist_ht200_z_et,0.5);
		hist_ht200_etsmrw_correction->Add(hist_ht200_z_et,0.5);
		hist_ht200_htrw_correction->Add(hist_ht200_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_z_njet->Fill(jet_n,totalWeight);
			hist_ht400_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_z_pt->Fill(Z_pt,totalWeight);
			hist_ht400_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht400_z_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Add(hist_ht400_z_njet,0.5);
		hist_ht400_nbjetrw_correction->Add(hist_ht400_z_nbjet,0.5);
		hist_ht400_ptrw_correction->Add(hist_ht400_z_pt,0.5);
		hist_ht400_ptsmrw_correction->Add(hist_ht400_z_pt,0.5);
		hist_ht400_etrw_correction->Add(hist_ht400_z_et,0.5);
		hist_ht400_etsmrw_correction->Add(hist_ht400_z_et,0.5);
		hist_ht400_htrw_correction->Add(hist_ht400_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_z_njet->Fill(jet_n,totalWeight);
			hist_ht1200_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_z_pt->Fill(Z_pt,totalWeight);
			hist_ht1200_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_z_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Add(hist_ht1200_z_njet,0.5);
		hist_ht1200_nbjetrw_correction->Add(hist_ht1200_z_nbjet,0.5);
		hist_ht1200_ptrw_correction->Add(hist_ht1200_z_pt,0.5);
		hist_ht1200_ptsmrw_correction->Add(hist_ht1200_z_pt,0.5);
		hist_ht1200_etrw_correction->Add(hist_ht1200_z_et,0.5);
		hist_ht1200_etsmrw_correction->Add(hist_ht1200_z_et,0.5);
		hist_ht1200_htrw_correction->Add(hist_ht1200_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_z_njet->Fill(jet_n,totalWeight);
			hist_srhigh_z_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_z_pt->Fill(Z_pt,totalWeight);
			hist_srhigh_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_z_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Add(hist_srhigh_z_njet,0.5);
		hist_srhigh_nbjetrw_correction->Add(hist_srhigh_z_nbjet,0.5);
		hist_srhigh_ptrw_correction->Add(hist_srhigh_z_pt,0.5);
		hist_srhigh_ptsmrw_correction->Add(hist_srhigh_z_pt,0.5);
		hist_srhigh_etrw_correction->Add(hist_srhigh_z_et,0.5);
		hist_srhigh_etsmrw_correction->Add(hist_srhigh_z_et,0.5);
		hist_srhigh_htrw_correction->Add(hist_srhigh_z_ht,0.5);
		fZ.Close();
		cout << "Opening file           : " << TString(outputPath)+"tt/ttsf.root"        << endl;
		TFile ftt( TString(outputPath)+"tt/ttsf.root" );
		TTree*  ttt              = (TTree*)ftt.Get("BaselineTree");
		ttt->SetBranchStatus("*", 0);
		ttt->SetBranchStatus("totalWeight", 1);
		ttt->SetBranchStatus("jet_n", 1);
		ttt->SetBranchStatus("bjet_n", 1);
		ttt->SetBranchStatus("Z_pt", 1);
		ttt->SetBranchStatus("DPhi_METJetLeading", 1);
		ttt->SetBranchStatus("DPhi_METJetSecond", 1);
		ttt->SetBranchStatus("HT", 1);
		ttt->SetBranchStatus("mll", 1);
		ttt->SetBranchStatus("lep_pT"                 ,1);
		ttt->SetBranchStatus("jet_pT"                 ,1);
		ttt->SetBranchStatus("mj0j1", 1);
		ttt->SetBranchStatus("MT2W", 1);
		ttt->SetBranchAddress("totalWeight" ,&totalWeight);
		ttt->SetBranchAddress("jet_n" ,&jet_n);
		ttt->SetBranchAddress("bjet_n" ,&bjet_n);
		ttt->SetBranchAddress("Z_pt" ,&Z_pt);
		ttt->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		ttt->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		ttt->SetBranchAddress("HT" ,&HT);
		ttt->SetBranchAddress("mll" ,&mll);
		ttt->SetBranchAddress("lep_pT"          ,&lep_pT           );
		ttt->SetBranchAddress("jet_pT"          ,&jet_pT           );
		ttt->SetBranchAddress("mj0j1" ,&mj0j1);
		ttt->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<ttt->GetEntries();entry++) {
			ttt->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_tt_njet->Fill(jet_n,totalWeight);
			hist_bveto_tt_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_tt_pt->Fill(Z_pt,totalWeight);
			hist_bveto_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_bveto_tt_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Add(hist_bveto_tt_njet,-1.*lumi*0.5);
		hist_bveto_nbjetrw_correction->Add(hist_bveto_tt_nbjet,-1.*lumi*0.5);
		hist_bveto_ptrw_correction->Add(hist_bveto_tt_pt,-1.*lumi*0.5);
		hist_bveto_ptsmrw_correction->Add(hist_bveto_tt_pt,-1.*lumi*0.5);
		hist_bveto_etrw_correction->Add(hist_bveto_tt_et,-1.*lumi*0.5);
		hist_bveto_etsmrw_correction->Add(hist_bveto_tt_et,-1.*lumi*0.5);
		hist_bveto_htrw_correction->Add(hist_bveto_tt_ht,-1.*lumi*0.5);
		for (int entry=0;entry<ttt->GetEntries();entry++) {
			ttt->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_tt_njet->Fill(jet_n,totalWeight);
			hist_2j30_tt_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_tt_pt->Fill(Z_pt,totalWeight);
			hist_2j30_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_2j30_tt_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Add(hist_2j30_tt_njet,-1.*lumi*0.5);
		hist_2j30_nbjetrw_correction->Add(hist_2j30_tt_nbjet,-1.*lumi*0.5);
		hist_2j30_ptrw_correction->Add(hist_2j30_tt_pt,-1.*lumi*0.5);
		hist_2j30_ptsmrw_correction->Add(hist_2j30_tt_pt,-1.*lumi*0.5);
		hist_2j30_etrw_correction->Add(hist_2j30_tt_et,-1.*lumi*0.5);
		hist_2j30_etsmrw_correction->Add(hist_2j30_tt_et,-1.*lumi*0.5);
		hist_2j30_htrw_correction->Add(hist_2j30_tt_ht,-1.*lumi*0.5);
		for (int entry=0;entry<ttt->GetEntries();entry++) {
			ttt->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_tt_njet->Fill(jet_n,totalWeight);
			hist_ht200_tt_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_tt_pt->Fill(Z_pt,totalWeight);
			hist_ht200_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht200_tt_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Add(hist_ht200_tt_njet,-1.*lumi*0.5);
		hist_ht200_nbjetrw_correction->Add(hist_ht200_tt_nbjet,-1.*lumi*0.5);
		hist_ht200_ptrw_correction->Add(hist_ht200_tt_pt,-1.*lumi*0.5);
		hist_ht200_ptsmrw_correction->Add(hist_ht200_tt_pt,-1.*lumi*0.5);
		hist_ht200_etrw_correction->Add(hist_ht200_tt_et,-1.*lumi*0.5);
		hist_ht200_etsmrw_correction->Add(hist_ht200_tt_et,-1.*lumi*0.5);
		hist_ht200_htrw_correction->Add(hist_ht200_tt_ht,-1.*lumi*0.5);
		for (int entry=0;entry<ttt->GetEntries();entry++) {
			ttt->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_tt_njet->Fill(jet_n,totalWeight);
			hist_ht400_tt_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_tt_pt->Fill(Z_pt,totalWeight);
			hist_ht400_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht400_tt_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Add(hist_ht400_tt_njet,-1.*lumi*0.5);
		hist_ht400_nbjetrw_correction->Add(hist_ht400_tt_nbjet,-1.*lumi*0.5);
		hist_ht400_ptrw_correction->Add(hist_ht400_tt_pt,-1.*lumi*0.5);
		hist_ht400_ptsmrw_correction->Add(hist_ht400_tt_pt,-1.*lumi*0.5);
		hist_ht400_etrw_correction->Add(hist_ht400_tt_et,-1.*lumi*0.5);
		hist_ht400_etsmrw_correction->Add(hist_ht400_tt_et,-1.*lumi*0.5);
		hist_ht400_htrw_correction->Add(hist_ht400_tt_ht,-1.*lumi*0.5);
		for (int entry=0;entry<ttt->GetEntries();entry++) {
			ttt->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_tt_njet->Fill(jet_n,totalWeight);
			hist_ht1200_tt_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_tt_pt->Fill(Z_pt,totalWeight);
			hist_ht1200_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_tt_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Add(hist_ht1200_tt_njet,-1.*lumi*0.5);
		hist_ht1200_nbjetrw_correction->Add(hist_ht1200_tt_nbjet,-1.*lumi*0.5);
		hist_ht1200_ptrw_correction->Add(hist_ht1200_tt_pt,-1.*lumi*0.5);
		hist_ht1200_ptsmrw_correction->Add(hist_ht1200_tt_pt,-1.*lumi*0.5);
		hist_ht1200_etrw_correction->Add(hist_ht1200_tt_et,-1.*lumi*0.5);
		hist_ht1200_etsmrw_correction->Add(hist_ht1200_tt_et,-1.*lumi*0.5);
		hist_ht1200_htrw_correction->Add(hist_ht1200_tt_ht,-1.*lumi*0.5);
		for (int entry=0;entry<ttt->GetEntries();entry++) {
			ttt->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_tt_njet->Fill(jet_n,totalWeight);
			hist_srhigh_tt_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_tt_pt->Fill(Z_pt,totalWeight);
			hist_srhigh_tt_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_tt_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Add(hist_srhigh_tt_njet,-1.*lumi*0.5);
		hist_srhigh_nbjetrw_correction->Add(hist_srhigh_tt_nbjet,-1.*lumi*0.5);
		hist_srhigh_ptrw_correction->Add(hist_srhigh_tt_pt,-1.*lumi*0.5);
		hist_srhigh_ptsmrw_correction->Add(hist_srhigh_tt_pt,-1.*lumi*0.5);
		hist_srhigh_etrw_correction->Add(hist_srhigh_tt_et,-1.*lumi*0.5);
		hist_srhigh_etsmrw_correction->Add(hist_srhigh_tt_et,-1.*lumi*0.5);
		hist_srhigh_htrw_correction->Add(hist_srhigh_tt_ht,-1.*lumi*0.5);
		ftt.Close();
		cout << "Opening file           : " << TString(outputPath)+"vv/vvsf.root"       << endl;
		TFile fvv( TString(outputPath)+"vv/vvsf.root" );
		TTree*  tvv              = (TTree*)fvv.Get("BaselineTree");
		tvv->SetBranchStatus("*", 0);
		tvv->SetBranchStatus("totalWeight", 1);
		tvv->SetBranchStatus("jet_n", 1);
		tvv->SetBranchStatus("bjet_n", 1);
		tvv->SetBranchStatus("Z_pt", 1);
		tvv->SetBranchStatus("DPhi_METJetLeading", 1);
		tvv->SetBranchStatus("DPhi_METJetSecond", 1);
		tvv->SetBranchStatus("HT", 1);
		tvv->SetBranchStatus("mll", 1);
		tvv->SetBranchStatus("lep_pT"                 ,1);
		tvv->SetBranchStatus("jet_pT"                 ,1);
		tvv->SetBranchStatus("mj0j1", 1);
		tvv->SetBranchStatus("MT2W", 1);
		tvv->SetBranchAddress("totalWeight" ,&totalWeight);
		tvv->SetBranchAddress("jet_n" ,&jet_n);
		tvv->SetBranchAddress("bjet_n" ,&bjet_n);
		tvv->SetBranchAddress("Z_pt" ,&Z_pt);
		tvv->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tvv->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tvv->SetBranchAddress("HT" ,&HT);
		tvv->SetBranchAddress("mll" ,&mll);
		tvv->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tvv->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tvv->SetBranchAddress("mj0j1" ,&mj0j1);
		tvv->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tvv->GetEntries();entry++) {
			tvv->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_vv_njet->Fill(jet_n,totalWeight);
			hist_bveto_vv_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_vv_pt->Fill(Z_pt,totalWeight);
			hist_bveto_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_bveto_vv_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Add(hist_bveto_vv_njet,-1.*lumi*0.5);
		hist_bveto_nbjetrw_correction->Add(hist_bveto_vv_nbjet,-1.*lumi*0.5);
		hist_bveto_ptrw_correction->Add(hist_bveto_vv_pt,-1.*lumi*0.5);
		hist_bveto_ptsmrw_correction->Add(hist_bveto_vv_pt,-1.*lumi*0.5);
		hist_bveto_etrw_correction->Add(hist_bveto_vv_et,-1.*lumi*0.5);
		hist_bveto_etsmrw_correction->Add(hist_bveto_vv_et,-1.*lumi*0.5);
		hist_bveto_htrw_correction->Add(hist_bveto_vv_ht,-1.*lumi*0.5);
		for (int entry=0;entry<tvv->GetEntries();entry++) {
			tvv->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_vv_njet->Fill(jet_n,totalWeight);
			hist_2j30_vv_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_vv_pt->Fill(Z_pt,totalWeight);
			hist_2j30_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_2j30_vv_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Add(hist_2j30_vv_njet,-1.*lumi*0.5);
		hist_2j30_nbjetrw_correction->Add(hist_2j30_vv_nbjet,-1.*lumi*0.5);
		hist_2j30_ptrw_correction->Add(hist_2j30_vv_pt,-1.*lumi*0.5);
		hist_2j30_ptsmrw_correction->Add(hist_2j30_vv_pt,-1.*lumi*0.5);
		hist_2j30_etrw_correction->Add(hist_2j30_vv_et,-1.*lumi*0.5);
		hist_2j30_etsmrw_correction->Add(hist_2j30_vv_et,-1.*lumi*0.5);
		hist_2j30_htrw_correction->Add(hist_2j30_vv_ht,-1.*lumi*0.5);
		for (int entry=0;entry<tvv->GetEntries();entry++) {
			tvv->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_vv_njet->Fill(jet_n,totalWeight);
			hist_ht200_vv_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_vv_pt->Fill(Z_pt,totalWeight);
			hist_ht200_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht200_vv_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Add(hist_ht200_vv_njet,-1.*lumi*0.5);
		hist_ht200_nbjetrw_correction->Add(hist_ht200_vv_nbjet,-1.*lumi*0.5);
		hist_ht200_ptrw_correction->Add(hist_ht200_vv_pt,-1.*lumi*0.5);
		hist_ht200_ptsmrw_correction->Add(hist_ht200_vv_pt,-1.*lumi*0.5);
		hist_ht200_etrw_correction->Add(hist_ht200_vv_et,-1.*lumi*0.5);
		hist_ht200_etsmrw_correction->Add(hist_ht200_vv_et,-1.*lumi*0.5);
		hist_ht200_htrw_correction->Add(hist_ht200_vv_ht,-1.*lumi*0.5);
		for (int entry=0;entry<tvv->GetEntries();entry++) {
			tvv->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_vv_njet->Fill(jet_n,totalWeight);
			hist_ht400_vv_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_vv_pt->Fill(Z_pt,totalWeight);
			hist_ht400_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht400_vv_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Add(hist_ht400_vv_njet,-1.*lumi*0.5);
		hist_ht400_nbjetrw_correction->Add(hist_ht400_vv_nbjet,-1.*lumi*0.5);
		hist_ht400_ptrw_correction->Add(hist_ht400_vv_pt,-1.*lumi*0.5);
		hist_ht400_ptsmrw_correction->Add(hist_ht400_vv_pt,-1.*lumi*0.5);
		hist_ht400_etrw_correction->Add(hist_ht400_vv_et,-1.*lumi*0.5);
		hist_ht400_etsmrw_correction->Add(hist_ht400_vv_et,-1.*lumi*0.5);
		hist_ht400_htrw_correction->Add(hist_ht400_vv_ht,-1.*lumi*0.5);
		for (int entry=0;entry<tvv->GetEntries();entry++) {
			tvv->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_vv_njet->Fill(jet_n,totalWeight);
			hist_ht1200_vv_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_vv_pt->Fill(Z_pt,totalWeight);
			hist_ht1200_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_vv_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Add(hist_ht1200_vv_njet,-1.*lumi*0.5);
		hist_ht1200_nbjetrw_correction->Add(hist_ht1200_vv_nbjet,-1.*lumi*0.5);
		hist_ht1200_ptrw_correction->Add(hist_ht1200_vv_pt,-1.*lumi*0.5);
		hist_ht1200_ptsmrw_correction->Add(hist_ht1200_vv_pt,-1.*lumi*0.5);
		hist_ht1200_etrw_correction->Add(hist_ht1200_vv_et,-1.*lumi*0.5);
		hist_ht1200_etsmrw_correction->Add(hist_ht1200_vv_et,-1.*lumi*0.5);
		hist_ht1200_htrw_correction->Add(hist_ht1200_vv_ht,-1.*lumi*0.5);
		for (int entry=0;entry<tvv->GetEntries();entry++) {
			tvv->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_vv_njet->Fill(jet_n,totalWeight);
			hist_srhigh_vv_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_vv_pt->Fill(Z_pt,totalWeight);
			hist_srhigh_vv_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_vv_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Add(hist_srhigh_vv_njet,-1.*lumi*0.5);
		hist_srhigh_nbjetrw_correction->Add(hist_srhigh_vv_nbjet,-1.*lumi*0.5);
		hist_srhigh_ptrw_correction->Add(hist_srhigh_vv_pt,-1.*lumi*0.5);
		hist_srhigh_ptsmrw_correction->Add(hist_srhigh_vv_pt,-1.*lumi*0.5);
		hist_srhigh_etrw_correction->Add(hist_srhigh_vv_et,-1.*lumi*0.5);
		hist_srhigh_etsmrw_correction->Add(hist_srhigh_vv_et,-1.*lumi*0.5);
		hist_srhigh_htrw_correction->Add(hist_srhigh_vv_ht,-1.*lumi*0.5);
		fvv.Close();
		TFile fPhoton( TString(outputPath)+"gdata/gdata_"+TString(ch)+TString(photon_tag)+".root" );
		TTree*  tPhoton              = (TTree*)fPhoton.Get("BaselineTree");
		tPhoton->SetBranchStatus("*", 0);
		tPhoton->SetBranchStatus("totalWeight", 1);
		tPhoton->SetBranchStatus("jet_n", 1);
		tPhoton->SetBranchStatus("bjet_n", 1);
		tPhoton->SetBranchStatus("gamma_pt", 1);
		tPhoton->SetBranchStatus("Z_pt", 1);
		tPhoton->SetBranchStatus("DPhi_METJetLeading", 1);
		tPhoton->SetBranchStatus("DPhi_METJetSecond", 1);
		tPhoton->SetBranchStatus("HT", 1);
		tPhoton->SetBranchStatus("mll", 1);
		tPhoton->SetBranchStatus("lep_pT"                 ,1);
		tPhoton->SetBranchStatus("jet_pT"                 ,1);
		tPhoton->SetBranchStatus("mj0j1", 1);
		tPhoton->SetBranchStatus("MT2W", 1);
		tPhoton->SetBranchAddress("totalWeight" ,&totalWeight);
		tPhoton->SetBranchAddress("jet_n" ,&jet_n);
		tPhoton->SetBranchAddress("bjet_n" ,&bjet_n);
		tPhoton->SetBranchAddress("gamma_pt" ,&gamma_pt);
		tPhoton->SetBranchAddress("Z_pt" ,&gamma_pt_smear);
		tPhoton->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tPhoton->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tPhoton->SetBranchAddress("HT" ,&HT);
		tPhoton->SetBranchAddress("mll" ,&mll);
		tPhoton->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tPhoton->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tPhoton->SetBranchAddress("mj0j1" ,&mj0j1);
		tPhoton->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_photon_njet->Fill(jet_n,totalWeight);
			hist_bveto_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_photon_pt->Fill(gamma_pt,totalWeight);
			hist_bveto_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_bveto_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Divide(hist_bveto_photon_njet);
		hist_bveto_nbjetrw_correction->Divide(hist_bveto_photon_nbjet);
		hist_bveto_ptrw_correction->Divide(hist_bveto_photon_pt);
		hist_bveto_ptsmrw_correction->Divide(hist_bveto_photon_ptsm);
		hist_bveto_etrw_correction->Divide(hist_bveto_photon_et);
		hist_bveto_etsmrw_correction->Divide(hist_bveto_photon_etsm);
		hist_bveto_htrw_correction->Divide(hist_bveto_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_photon_njet->Fill(jet_n,totalWeight);
			hist_2j30_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_photon_pt->Fill(gamma_pt,totalWeight);
			hist_2j30_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_2j30_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_2j30_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_2j30_photon_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Divide(hist_2j30_photon_njet);
		hist_2j30_nbjetrw_correction->Divide(hist_2j30_photon_nbjet);
		hist_2j30_ptrw_correction->Divide(hist_2j30_photon_pt);
		hist_2j30_ptsmrw_correction->Divide(hist_2j30_photon_ptsm);
		hist_2j30_etrw_correction->Divide(hist_2j30_photon_et);
		hist_2j30_etsmrw_correction->Divide(hist_2j30_photon_etsm);
		hist_2j30_htrw_correction->Divide(hist_2j30_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_photon_njet->Fill(jet_n,totalWeight);
			hist_ht200_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht200_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht200_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht200_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht200_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Divide(hist_ht200_photon_njet);
		hist_ht200_nbjetrw_correction->Divide(hist_ht200_photon_nbjet);
		hist_ht200_ptrw_correction->Divide(hist_ht200_photon_pt);
		hist_ht200_ptsmrw_correction->Divide(hist_ht200_photon_ptsm);
		hist_ht200_etrw_correction->Divide(hist_ht200_photon_et);
		hist_ht200_etsmrw_correction->Divide(hist_ht200_photon_etsm);
		hist_ht200_htrw_correction->Divide(hist_ht200_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_photon_njet->Fill(jet_n,totalWeight);
			hist_ht400_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht400_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht400_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht400_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht400_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Divide(hist_ht400_photon_njet);
		hist_ht400_nbjetrw_correction->Divide(hist_ht400_photon_nbjet);
		hist_ht400_ptrw_correction->Divide(hist_ht400_photon_pt);
		hist_ht400_ptsmrw_correction->Divide(hist_ht400_photon_ptsm);
		hist_ht400_etrw_correction->Divide(hist_ht400_photon_et);
		hist_ht400_etsmrw_correction->Divide(hist_ht400_photon_etsm);
		hist_ht400_htrw_correction->Divide(hist_ht400_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_photon_njet->Fill(jet_n,totalWeight);
			hist_ht1200_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht1200_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht1200_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht1200_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Divide(hist_ht1200_photon_njet);
		hist_ht1200_nbjetrw_correction->Divide(hist_ht1200_photon_nbjet);
		hist_ht1200_ptrw_correction->Divide(hist_ht1200_photon_pt);
		hist_ht1200_ptsmrw_correction->Divide(hist_ht1200_photon_ptsm);
		hist_ht1200_etrw_correction->Divide(hist_ht1200_photon_et);
		hist_ht1200_etsmrw_correction->Divide(hist_ht1200_photon_etsm);
		hist_ht1200_htrw_correction->Divide(hist_ht1200_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_photon_njet->Fill(jet_n,totalWeight);
			hist_srhigh_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_photon_pt->Fill(gamma_pt,totalWeight);
			hist_srhigh_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_srhigh_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_srhigh_photon_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Divide(hist_srhigh_photon_njet);
		hist_srhigh_nbjetrw_correction->Divide(hist_srhigh_photon_nbjet);
		hist_srhigh_ptrw_correction->Divide(hist_srhigh_photon_pt);
		hist_srhigh_ptsmrw_correction->Divide(hist_srhigh_photon_ptsm);
		hist_srhigh_etrw_correction->Divide(hist_srhigh_photon_et);
		hist_srhigh_etsmrw_correction->Divide(hist_srhigh_photon_etsm);
		hist_srhigh_htrw_correction->Divide(hist_srhigh_photon_ht);
		fPhoton.Close();
	}
	else {
		TFile fZ( TString(outputPath)+"zjets/zjets_sf.root" );
		TTree*  tZ              = (TTree*)fZ.Get("BaselineTree");
		tZ->SetBranchStatus("*", 0);
		tZ->SetBranchStatus("totalWeight", 1);
		tZ->SetBranchStatus("jet_n", 1);
		tZ->SetBranchStatus("bjet_n", 1);
		tZ->SetBranchStatus("Z_pt", 1);
		tZ->SetBranchStatus("DPhi_METJetLeading", 1);
		tZ->SetBranchStatus("DPhi_METJetSecond", 1);
		tZ->SetBranchStatus("HT", 1);
		tZ->SetBranchStatus("mll", 1);
		tZ->SetBranchStatus("lep_pT"                 ,1);
		tZ->SetBranchStatus("jet_pT"                 ,1);
		tZ->SetBranchStatus("mj0j1", 1);
		tZ->SetBranchStatus("MT2W", 1);
		tZ->SetBranchAddress("totalWeight" ,&totalWeight);
		tZ->SetBranchAddress("jet_n" ,&jet_n);
		tZ->SetBranchAddress("bjet_n" ,&bjet_n);
		tZ->SetBranchAddress("Z_pt" ,&Z_pt);
		tZ->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tZ->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tZ->SetBranchAddress("HT" ,&HT);
		tZ->SetBranchAddress("mll" ,&mll);
		tZ->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tZ->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tZ->SetBranchAddress("mj0j1" ,&mj0j1);
		tZ->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_z_njet->Fill(jet_n,totalWeight);
			hist_bveto_z_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_z_pt->Fill(Z_pt,totalWeight);
			hist_bveto_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_bveto_z_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Add(hist_bveto_z_njet,0.5);
		hist_bveto_nbjetrw_correction->Add(hist_bveto_z_nbjet,0.5);
		hist_bveto_ptrw_correction->Add(hist_bveto_z_pt,0.5);
		hist_bveto_ptsmrw_correction->Add(hist_bveto_z_pt,0.5);
		hist_bveto_etrw_correction->Add(hist_bveto_z_et,0.5);
		hist_bveto_etsmrw_correction->Add(hist_bveto_z_et,0.5);
		hist_bveto_htrw_correction->Add(hist_bveto_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_z_njet->Fill(jet_n,totalWeight);
			hist_2j30_z_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_z_pt->Fill(Z_pt,totalWeight);
			hist_2j30_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_2j30_z_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Add(hist_2j30_z_njet,0.5);
		hist_2j30_nbjetrw_correction->Add(hist_2j30_z_nbjet,0.5);
		hist_2j30_ptrw_correction->Add(hist_2j30_z_pt,0.5);
		hist_2j30_ptsmrw_correction->Add(hist_2j30_z_pt,0.5);
		hist_2j30_etrw_correction->Add(hist_2j30_z_et,0.5);
		hist_2j30_etsmrw_correction->Add(hist_2j30_z_et,0.5);
		hist_2j30_htrw_correction->Add(hist_2j30_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_z_njet->Fill(jet_n,totalWeight);
			hist_ht200_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_z_pt->Fill(Z_pt,totalWeight);
			hist_ht200_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht200_z_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Add(hist_ht200_z_njet,0.5);
		hist_ht200_nbjetrw_correction->Add(hist_ht200_z_nbjet,0.5);
		hist_ht200_ptrw_correction->Add(hist_ht200_z_pt,0.5);
		hist_ht200_ptsmrw_correction->Add(hist_ht200_z_pt,0.5);
		hist_ht200_etrw_correction->Add(hist_ht200_z_et,0.5);
		hist_ht200_etsmrw_correction->Add(hist_ht200_z_et,0.5);
		hist_ht200_htrw_correction->Add(hist_ht200_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_z_njet->Fill(jet_n,totalWeight);
			hist_ht400_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_z_pt->Fill(Z_pt,totalWeight);
			hist_ht400_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht400_z_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Add(hist_ht400_z_njet,0.5);
		hist_ht400_nbjetrw_correction->Add(hist_ht400_z_nbjet,0.5);
		hist_ht400_ptrw_correction->Add(hist_ht400_z_pt,0.5);
		hist_ht400_ptsmrw_correction->Add(hist_ht400_z_pt,0.5);
		hist_ht400_etrw_correction->Add(hist_ht400_z_et,0.5);
		hist_ht400_etsmrw_correction->Add(hist_ht400_z_et,0.5);
		hist_ht400_htrw_correction->Add(hist_ht400_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_z_njet->Fill(jet_n,totalWeight);
			hist_ht1200_z_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_z_pt->Fill(Z_pt,totalWeight);
			hist_ht1200_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_z_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Add(hist_ht1200_z_njet,0.5);
		hist_ht1200_nbjetrw_correction->Add(hist_ht1200_z_nbjet,0.5);
		hist_ht1200_ptrw_correction->Add(hist_ht1200_z_pt,0.5);
		hist_ht1200_ptsmrw_correction->Add(hist_ht1200_z_pt,0.5);
		hist_ht1200_etrw_correction->Add(hist_ht1200_z_et,0.5);
		hist_ht1200_etsmrw_correction->Add(hist_ht1200_z_et,0.5);
		hist_ht1200_htrw_correction->Add(hist_ht1200_z_ht,0.5);
		for (int entry=0;entry<tZ->GetEntries();entry++) {
			tZ->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_z_njet->Fill(jet_n,totalWeight);
			hist_srhigh_z_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_z_pt->Fill(Z_pt,totalWeight);
			hist_srhigh_z_et->Fill(pow(Z_pt*Z_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_z_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Add(hist_srhigh_z_njet,0.5);
		hist_srhigh_nbjetrw_correction->Add(hist_srhigh_z_nbjet,0.5);
		hist_srhigh_ptrw_correction->Add(hist_srhigh_z_pt,0.5);
		hist_srhigh_ptsmrw_correction->Add(hist_srhigh_z_pt,0.5);
		hist_srhigh_etrw_correction->Add(hist_srhigh_z_et,0.5);
		hist_srhigh_etsmrw_correction->Add(hist_srhigh_z_et,0.5);
		hist_srhigh_htrw_correction->Add(hist_srhigh_z_ht,0.5);
		fZ.Close();
		TFile fPhoton( TString(outputPath)+"gmc/gmc_"+TString(ch)+TString(photon_tag)+".root" );
		TTree*  tPhoton              = (TTree*)fPhoton.Get("BaselineTree");
		tPhoton->SetBranchStatus("*", 0);
		tPhoton->SetBranchStatus("totalWeight", 1);
		tPhoton->SetBranchStatus("jet_n", 1);
		tPhoton->SetBranchStatus("bjet_n", 1);
		tPhoton->SetBranchStatus("gamma_pt", 1);
		tPhoton->SetBranchStatus("Z_pt", 1);
		tPhoton->SetBranchStatus("DPhi_METJetLeading", 1);
		tPhoton->SetBranchStatus("DPhi_METJetSecond", 1);
		tPhoton->SetBranchStatus("HT", 1);
		tPhoton->SetBranchStatus("mll", 1);
		tPhoton->SetBranchStatus("lep_pT"                 ,1);
		tPhoton->SetBranchStatus("jet_pT"                 ,1);
		tPhoton->SetBranchStatus("mj0j1", 1);
		tPhoton->SetBranchStatus("MT2W", 1);
		tPhoton->SetBranchAddress("totalWeight" ,&totalWeight);
		tPhoton->SetBranchAddress("jet_n" ,&jet_n);
		tPhoton->SetBranchAddress("bjet_n" ,&bjet_n);
		tPhoton->SetBranchAddress("gamma_pt" ,&gamma_pt);
		tPhoton->SetBranchAddress("Z_pt" ,&gamma_pt_smear);
		tPhoton->SetBranchAddress("DPhi_METJetLeading" ,&DPhi_METJetLeading);
		tPhoton->SetBranchAddress("DPhi_METJetSecond" ,&DPhi_METJetSecond);
		tPhoton->SetBranchAddress("HT" ,&HT);
		tPhoton->SetBranchAddress("mll" ,&mll);
		tPhoton->SetBranchAddress("lep_pT"          ,&lep_pT           );
		tPhoton->SetBranchAddress("jet_pT"          ,&jet_pT           );
		tPhoton->SetBranchAddress("mj0j1" ,&mj0j1);
		tPhoton->SetBranchAddress("MT2W" ,&MT2W);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			hist_bveto_photon_njet->Fill(jet_n,totalWeight);
			hist_bveto_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_bveto_photon_pt->Fill(gamma_pt,totalWeight);
			hist_bveto_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_bveto_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_bveto_photon_ht->Fill(HT,totalWeight);
		}
		hist_bveto_njetrw_correction->Divide(hist_bveto_photon_njet);
		hist_bveto_nbjetrw_correction->Divide(hist_bveto_photon_nbjet);
		hist_bveto_ptrw_correction->Divide(hist_bveto_photon_pt);
		hist_bveto_ptsmrw_correction->Divide(hist_bveto_photon_ptsm);
		hist_bveto_etrw_correction->Divide(hist_bveto_photon_et);
		hist_bveto_etsmrw_correction->Divide(hist_bveto_photon_etsm);
		hist_bveto_htrw_correction->Divide(hist_bveto_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			hist_2j30_photon_njet->Fill(jet_n,totalWeight);
			hist_2j30_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_2j30_photon_pt->Fill(gamma_pt,totalWeight);
			hist_2j30_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_2j30_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_2j30_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_2j30_photon_ht->Fill(HT,totalWeight);
		}
		hist_2j30_njetrw_correction->Divide(hist_2j30_photon_njet);
		hist_2j30_nbjetrw_correction->Divide(hist_2j30_photon_nbjet);
		hist_2j30_ptrw_correction->Divide(hist_2j30_photon_pt);
		hist_2j30_ptsmrw_correction->Divide(hist_2j30_photon_ptsm);
		hist_2j30_etrw_correction->Divide(hist_2j30_photon_et);
		hist_2j30_etsmrw_correction->Divide(hist_2j30_photon_etsm);
		hist_2j30_htrw_correction->Divide(hist_2j30_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht200_photon_njet->Fill(jet_n,totalWeight);
			hist_ht200_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht200_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht200_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht200_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht200_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht200_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht200_njetrw_correction->Divide(hist_ht200_photon_njet);
		hist_ht200_nbjetrw_correction->Divide(hist_ht200_photon_nbjet);
		hist_ht200_ptrw_correction->Divide(hist_ht200_photon_pt);
		hist_ht200_ptsmrw_correction->Divide(hist_ht200_photon_ptsm);
		hist_ht200_etrw_correction->Divide(hist_ht200_photon_et);
		hist_ht200_etsmrw_correction->Divide(hist_ht200_photon_etsm);
		hist_ht200_htrw_correction->Divide(hist_ht200_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<400.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht400_photon_njet->Fill(jet_n,totalWeight);
			hist_ht400_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht400_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht400_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht400_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht400_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht400_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht400_njetrw_correction->Divide(hist_ht400_photon_njet);
		hist_ht400_nbjetrw_correction->Divide(hist_ht400_photon_nbjet);
		hist_ht400_ptrw_correction->Divide(hist_ht400_photon_pt);
		hist_ht400_ptsmrw_correction->Divide(hist_ht400_photon_ptsm);
		hist_ht400_etrw_correction->Divide(hist_ht400_photon_et);
		hist_ht400_etsmrw_correction->Divide(hist_ht400_photon_etsm);
		hist_ht400_htrw_correction->Divide(hist_ht400_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (HT<1200.) continue;
			//if (DPhi_METJetLeading<0.4) continue;
			//if (DPhi_METJetSecond<0.4) continue;
			hist_ht1200_photon_njet->Fill(jet_n,totalWeight);
			hist_ht1200_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_ht1200_photon_pt->Fill(gamma_pt,totalWeight);
			hist_ht1200_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_ht1200_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_ht1200_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_ht1200_photon_ht->Fill(HT,totalWeight);
		}
		hist_ht1200_njetrw_correction->Divide(hist_ht1200_photon_njet);
		hist_ht1200_nbjetrw_correction->Divide(hist_ht1200_photon_nbjet);
		hist_ht1200_ptrw_correction->Divide(hist_ht1200_photon_pt);
		hist_ht1200_ptsmrw_correction->Divide(hist_ht1200_photon_ptsm);
		hist_ht1200_etrw_correction->Divide(hist_ht1200_photon_et);
		hist_ht1200_etsmrw_correction->Divide(hist_ht1200_photon_etsm);
		hist_ht1200_htrw_correction->Divide(hist_ht1200_photon_ht);
		for (int entry=0;entry<tPhoton->GetEntries();entry++) {
			tPhoton->GetEntry(entry);
			if (jet_n==0) continue;
			if (jet_n==1) continue;
			if (bjet_n!=0) continue;
			if (lep_pT->at(0)<leading_lep_pt_cut) continue;
			if (lep_pT->at(1)<second_lep_pt_cut) continue;
			if (jet_pT->at(0)<30.) continue;
			if (jet_pT->at(1)<30.) continue;
			if (mj0j1<60.) continue;
			if (mj0j1>100.) continue;
			if (MT2W<100.) continue;
			hist_srhigh_photon_njet->Fill(jet_n,totalWeight);
			hist_srhigh_photon_nbjet->Fill(bjet_n,totalWeight);
			hist_srhigh_photon_pt->Fill(gamma_pt,totalWeight);
			hist_srhigh_photon_et->Fill(pow(gamma_pt*gamma_pt+mll*mll,0.5),totalWeight);
			hist_srhigh_photon_ptsm->Fill(gamma_pt_smear,totalWeight);
			hist_srhigh_photon_etsm->Fill(pow(gamma_pt_smear*gamma_pt_smear+mll*mll,0.5),totalWeight);
			hist_srhigh_photon_ht->Fill(HT,totalWeight);
		}
		hist_srhigh_njetrw_correction->Divide(hist_srhigh_photon_njet);
		hist_srhigh_nbjetrw_correction->Divide(hist_srhigh_photon_nbjet);
		hist_srhigh_ptrw_correction->Divide(hist_srhigh_photon_pt);
		hist_srhigh_ptsmrw_correction->Divide(hist_srhigh_photon_ptsm);
		hist_srhigh_etrw_correction->Divide(hist_srhigh_photon_et);
		hist_srhigh_etsmrw_correction->Divide(hist_srhigh_photon_etsm);
		hist_srhigh_htrw_correction->Divide(hist_srhigh_photon_ht);
		fPhoton.Close();
	}

}
