bool trigMatch_1L2LTrig;
ULong64_t EventNumber;
Int_t RunNumber;
Int_t RandomRunNumber;
Float_t Mu;
Int_t nVtx;
Float_t mll;
//Float_t MT2Top;
//Float_t MT2W;
float MET;
float MET_phi;
float MET_softTerm;
float MET_softPhi;
//Float_t truthMET;
//Float_t truthMET_Phi;
Float_t DPhi_METJetLeading;
Float_t DPhi_METJetSecond;
float HT;
//float HTincl;
Float_t Z_pt;
//float Z_eta;
//float Z_phi;
// float SherpaNJetWeight;
// Int_t channel;
// Int_t is_OS;
// Int_t HLT_e60_lhmedium;
// Int_t HLT_2e17_lhvloose_nod0;
// Int_t HLT_mu50;
// Int_t HLT_mu18_mu8noL1;
// Int_t HLT_e17_lhloose_mu14;
// Int_t HLT_e7_lhmedium_mu24;
// Int_t eetrig;
// Int_t mmtrig;
// Int_t emtrig;
Int_t jet_n;
Int_t bjet_n;
//Int_t lep_n;
//Int_t el_n;
//Int_t mu_n;
Int_t nLep_signal;
Int_t nLep_base;
//std::vector<long>* lep_isPrompt = new std::vector<long>(10);
//std::vector<long>* lep_pdgId = new std::vector<long>(10);
std::vector<int>*    lepFlavor = new std::vector<int>(10);
std::vector<int>*    lepCharge = new std::vector<int>(10);
std::vector<int>*    lepSignal = new std::vector<int>(10);
std::vector<float>* lep_pT = new std::vector<float>(10);
std::vector<float>* lep_eta = new std::vector<float>(10);
std::vector<float>* lep_phi = new std::vector<float>(10);
std::vector<float>* jet_pT = new std::vector<float>(10);
std::vector<float>* jet_eta = new std::vector<float>(10);
std::vector<float>* jet_phi = new std::vector<float>(10);
std::vector<float>* jet_m = new std::vector<float>(10);
//std::vector<float>* jet_btag = new std::vector<float>(10);
//std::vector<int>* pass_trig_MET = new std::vector<int>(10);
//float sampleWeight;
//Float_t eventWeight;
//Float_t emtrigweight;
//Float_t eetrigweight;
//Float_t mmtrigweight;
//Float_t trig_sf;
Double_t genWeight;
Double_t eventWeight;
Double_t leptonWeight;
Double_t jvtWeight;
Double_t bTagWeight;
Double_t pileupWeight;
Double_t FFWeight;

// Float_t truth_ZpT;
// Float_t truth_Zphi;
// std::vector<float>* lep_truthPt = new std::vector<float>(10);
// std::vector<float>* lep_truthEta = new std::vector<float>(10);
// std::vector<float>* lep_truthPhi = new std::vector<float>(10);
// std::vector<float>* lep_truthGammaPt = new std::vector<float>(10);
// std::vector<float>* lep_weight = new std::vector<float>(10);
// Int_t truthJet_n;
// std::vector<float>* truthJet_pT = new std::vector<float>(10);
// std::vector<float>* truthJet_eta = new std::vector<float>(10);
// std::vector<float>* truthJet_phi = new std::vector<float>(10);

void GetBranches(TTree* inputTree, bool isData) {

	inputTree->SetBranchStatus("*", 0);
	inputTree->SetBranchStatus("EventNumber"            ,1);
	inputTree->SetBranchStatus("trigMatch_1L2LTrig"     ,1);
	inputTree->SetBranchStatus("RunNumber"              ,1);
	inputTree->SetBranchStatus("RandomRunNumber"              ,1);
	inputTree->SetBranchStatus("mu"                     ,1);
	inputTree->SetBranchStatus("nVtx"                   ,1);
	inputTree->SetBranchStatus("mll"                    ,1);
	//inputTree->SetBranchStatus("MT2Top"                 ,1);
	//inputTree->SetBranchStatus("MT2W"                   ,1);
	inputTree->SetBranchStatus("met_Et"                 ,1);
	inputTree->SetBranchStatus("met_Phi"                ,1);
	inputTree->SetBranchStatus("TST_Et"                 ,1); 
	inputTree->SetBranchStatus("TST_Phi"                ,1); 
	//inputTree->SetBranchStatus("truthMET"               ,1);
	//inputTree->SetBranchStatus("truthMET_Phi"           ,1);
	inputTree->SetBranchStatus("DPhiJ1Met"              ,1);
	inputTree->SetBranchStatus("DPhiJ2Met"              ,1);
	inputTree->SetBranchStatus("Ht30"                   ,1);
	//inputTree->SetBranchStatus("HTincl"                 ,1);
	inputTree->SetBranchStatus("Ptll"                   ,1);
	//inputTree->SetBranchStatus("Z_eta"                  ,1);
	//inputTree->SetBranchStatus("Z_phi"                  ,1);
	//inputTree->SetBranchStatus("SherpaNJetWeight"       ,1);
	//inputTree->SetBranchStatus("channel"                ,1);
	//inputTree->SetBranchStatus("is_OS"                  ,1);
	//inputTree->SetBranchStatus("HLT_e60_lhmedium"       ,1);
	//inputTree->SetBranchStatus("HLT_2e17_lhvloose_nod0" ,1);
	//inputTree->SetBranchStatus("HLT_mu50"               ,1);
	//inputTree->SetBranchStatus("HLT_mu18_mu8noL1"       ,1);
	//inputTree->SetBranchStatus("HLT_e17_lhloose_mu14"   ,1);
	//inputTree->SetBranchStatus("HLT_e7_lhmedium_mu24"   ,1);
	//inputTree->SetBranchStatus("eetrig"                 ,1);
	//inputTree->SetBranchStatus("mmtrig"                 ,1);
	//inputTree->SetBranchStatus("emtrig"                 ,1);
	inputTree->SetBranchStatus("nBJet30_MV2c10_FixedCutBEff_77"        ,1);
	//inputTree->SetBranchStatus("lep_n"                  ,1);
	inputTree->SetBranchStatus("nLep_signal"            ,1);
	inputTree->SetBranchStatus("nLep_base"              ,1);
	//inputTree->SetBranchStatus("el_n"                   ,1);
	//inputTree->SetBranchStatus("mu_n"                   ,1);
	inputTree->SetBranchStatus("lepSignal"              ,1);
	inputTree->SetBranchStatus("lepFlavor"              ,1);
	inputTree->SetBranchStatus("lepCharge"              ,1);
	inputTree->SetBranchStatus("lepPt"                  ,1);
	inputTree->SetBranchStatus("lepEta"                 ,1);
	inputTree->SetBranchStatus("lepPhi"                 ,1);
	inputTree->SetBranchStatus("nJet30"                 ,1);
	inputTree->SetBranchStatus("jetPt"                  ,1);
	inputTree->SetBranchStatus("jetEta"                 ,1);
	inputTree->SetBranchStatus("jetPhi"                 ,1);
	inputTree->SetBranchStatus("jetM"                   ,1);
	//inputTree->SetBranchStatus("jet_btag"               ,1);
	//inputTree->SetBranchStatus("pass_trig_MET"          ,1);
	if (!isData) {
	  //inputTree->SetBranchStatus("sampleWeight"        ,1);
	  //inputTree->SetBranchStatus("eventWeight"         ,1);
	  //inputTree->SetBranchStatus("emtrigweight"        ,1);
	  //inputTree->SetBranchStatus("eetrigweight"        ,1);
	  //inputTree->SetBranchStatus("mmtrigweight"        ,1);
	  
	  inputTree->SetBranchStatus("genWeight"          ,1);
	  inputTree->SetBranchStatus("eventWeight"        ,1);
	  inputTree->SetBranchStatus("leptonWeight"       ,1);
	  inputTree->SetBranchStatus("jvtWeight"          ,1);
	  inputTree->SetBranchStatus("bTagWeight"         ,1);
	  inputTree->SetBranchStatus("pileupWeight"       ,1);
	  inputTree->SetBranchStatus("FFWeight"           ,1);

	  //inputTree->SetBranchStatus("trig_sf"             ,1);
	  //inputTree->SetBranchStatus("lep_truthPt"         ,1);
	  //inputTree->SetBranchStatus("lep_truthEta"        ,1);
	  //inputTree->SetBranchStatus("lep_truthPhi"        ,1);
	  //inputTree->SetBranchStatus("lep_truthGammaPt"    ,1);
	  //inputTree->SetBranchStatus("lep_weight"          ,1);
	  //inputTree->SetBranchStatus("truth_ZpT"           ,1);
	  //inputTree->SetBranchStatus("truth_Zphi"          ,1);
	  //inputTree->SetBranchStatus("truthJet_n"          ,1);
	  //inputTree->SetBranchStatus("truthJet_pT"         ,1);
	  //inputTree->SetBranchStatus("truthJet_eta"        ,1);
	  //inputTree->SetBranchStatus("truthJet_phi"        ,1);
	}

	// see original code, cut-and-pasted at end of file
	
	inputTree->SetBranchAddress("trigMatch_1L2LTrig"    ,&trigMatch_1L2LTrig      );
	inputTree->SetBranchAddress("EventNumber"           ,&EventNumber             );
	inputTree->SetBranchAddress("RunNumber"             ,&RunNumber               );
	inputTree->SetBranchAddress("RandomRunNumber"       ,&RandomRunNumber         );
	inputTree->SetBranchAddress("mu"                    ,&Mu                      );
	inputTree->SetBranchAddress("nVtx"                  ,&nVtx                    );
	inputTree->SetBranchAddress("mll"                   ,&mll                     );
	//inputTree->SetBranchAddress("MT2Top"                ,&MT2Top                  );
	//inputTree->SetBranchAddress("MT2W"                  ,&MT2W                    );
	inputTree->SetBranchAddress("met_Et"                ,&MET                     );
	inputTree->SetBranchAddress("met_Phi"               ,&MET_phi                 );
	inputTree->SetBranchAddress("TST_Et"                ,&MET_softTerm            );
	inputTree->SetBranchAddress("TST_Phi"               ,&MET_softPhi             );
	//inputTree->SetBranchAddress("truthMET"              ,&truthMET                );
	//inputTree->SetBranchAddress("truthMET_Phi"          ,&truthMET_Phi            );
	inputTree->SetBranchAddress("DPhiJ1Met"             ,&DPhi_METJetLeading      );
	inputTree->SetBranchAddress("DPhiJ2Met"             ,&DPhi_METJetSecond       );
	inputTree->SetBranchAddress("Ht30"                  ,&HT                      );
	//inputTree->SetBranchAddress("HTincl"                ,&HTincl                  );
	inputTree->SetBranchAddress("Ptll"                  ,&Z_pt                    );
	//inputTree->SetBranchAddress("Z_eta"                 ,&Z_eta                   );
	//inputTree->SetBranchAddress("Z_phi"                 ,&Z_phi                   );
	//inputTree->SetBranchAddress("SherpaNJetWeight"      ,&SherpaNJetWeight        );
	//inputTree->SetBranchAddress("channel"               ,&channel                 );
	//inputTree->SetBranchAddress("is_OS"                 ,&is_OS                   );
	//inputTree->SetBranchAddress("HLT_e60_lhmedium"      ,&HLT_e60_lhmedium        );
	//inputTree->SetBranchAddress("HLT_2e17_lhvloose_nod0",&HLT_2e17_lhvloose_nod0  );
	//inputTree->SetBranchAddress("HLT_mu50"              ,&HLT_mu50                );
	//inputTree->SetBranchAddress("HLT_mu18_mu8noL1"      ,&HLT_mu18_mu8noL1        );
	//inputTree->SetBranchAddress("HLT_e17_lhloose_mu14"  ,&HLT_e17_lhloose_mu14    );
	//inputTree->SetBranchAddress("HLT_e7_lhmedium_mu24"  ,&HLT_e7_lhmedium_mu24    );
	//inputTree->SetBranchAddress("eetrig"                ,&eetrig                  );
	//inputTree->SetBranchAddress("mmtrig"                ,&mmtrig                  );
	//inputTree->SetBranchAddress("emtrig"                ,&emtrig                  );
	inputTree->SetBranchAddress("nBJet30_MV2c10_FixedCutBEff_77" ,&bjet_n                  );
	//inputTree->SetBranchAddress("lep_n"                 ,&lep_n                   );
	//inputTree->SetBranchAddress("el_n"                  ,&el_n                    );
	//inputTree->SetBranchAddress("mu_n"                  ,&mu_n                    );
	inputTree->SetBranchAddress("nLep_signal"           ,&nLep_signal             );
	inputTree->SetBranchAddress("nLep_base"             ,&nLep_base               );
	inputTree->SetBranchAddress("lepSignal"             ,&lepSignal               );
	//inputTree->SetBranchAddress("lepSignal"             ,&lep_isPrompt            );
	//inputTree->SetBranchAddress("lepFlavor"             ,&lep_pdgId               );
	inputTree->SetBranchAddress("lepPt"                 ,&lep_pT                  );
	inputTree->SetBranchAddress("lepFlavor"             ,&lepFlavor               );
	inputTree->SetBranchAddress("lepCharge"             ,&lepCharge               );
	inputTree->SetBranchAddress("lepEta"                ,&lep_eta                 );
	inputTree->SetBranchAddress("lepPhi"                ,&lep_phi                 );
	inputTree->SetBranchAddress("nJet30"                ,&jet_n                   );
	inputTree->SetBranchAddress("jetPt"                 ,&jet_pT                  );
	inputTree->SetBranchAddress("jetEta"                ,&jet_eta                 );
	inputTree->SetBranchAddress("jetPhi"                ,&jet_phi                 );
	inputTree->SetBranchAddress("jetM"                  ,&jet_m                   );
	//inputTree->SetBranchAddress("jet_btag"              ,&jet_btag                );
	//inputTree->SetBranchAddress("pass_trig_MET"         ,&pass_trig_MET           );

	if (!isData) {
	  inputTree->SetBranchAddress("genWeight"         ,&genWeight     );
	  inputTree->SetBranchAddress("eventWeight"       ,&eventWeight   );
	  inputTree->SetBranchAddress("leptonWeight"      ,&leptonWeight  );
	  inputTree->SetBranchAddress("jvtWeight"         ,&jvtWeight     );
	  inputTree->SetBranchAddress("bTagWeight"        ,&bTagWeight    );
	  inputTree->SetBranchAddress("pileupWeight"      ,&pileupWeight  );
	  inputTree->SetBranchAddress("FFWeight"          ,&FFWeight      );
		
	  //inputTree->SetBranchAddress("sampleWeight"     ,&sampleWeight);
	  //inputTree->SetBranchAddress("eventWeight"      ,&eventWeight);
	  //inputTree->SetBranchAddress("emtrigweight"     ,&emtrigweight);
	  //inputTree->SetBranchAddress("eetrigweight"     ,&eetrigweight);
	  //inputTree->SetBranchAddress("mmtrigweight"     ,&mmtrigweight);
	  //inputTree->SetBranchAddress("trig_sf",&trig_sf);
	  //inputTree->SetBranchAddress("lep_truthPt"      ,&lep_truthPt           );
	  //inputTree->SetBranchAddress("lep_truthEta"     ,&lep_truthEta           );
	  //inputTree->SetBranchAddress("lep_truthPhi"     ,&lep_truthPhi           );
	  //inputTree->SetBranchAddress("lep_truthGammaPt" ,&lep_truthGammaPt           );
	  //inputTree->SetBranchAddress("lep_weight"       ,&lep_weight);
	  //inputTree->SetBranchAddress("truth_ZpT"        ,&truth_ZpT);
	  //inputTree->SetBranchAddress("truth_Zphi"       ,&truth_Zphi);
	  //inputTree->SetBranchAddress("truthJet_n"       ,&truthJet_n       );
	  //inputTree->SetBranchAddress("truthJet_pT"      ,&truthJet_pT      );
	  //inputTree->SetBranchAddress("truthJet_eta"     ,&truthJet_eta     );
	  //inputTree->SetBranchAddress("truthJet_phi"     ,&truthJet_phi     );
	}


}









	// inputTree->SetBranchStatus("*", 0);
	// inputTree->SetBranchStatus("EventNumber"              ,1); 
	// inputTree->SetBranchStatus("RunNumber"              ,1); 
	// inputTree->SetBranchStatus("mu"              ,1); 
	// inputTree->SetBranchStatus("met_Et"             ,1); 
	// inputTree->SetBranchStatus("met_Phi"         ,1); 
	// inputTree->SetBranchStatus("TST_Et"         ,1); 
	// inputTree->SetBranchStatus("TST_Phi"         ,1); 
	// //inputTree->SetBranchStatus("truthMET"             ,1); 
	// //inputTree->SetBranchStatus("truthMET_Phi"         ,1); 
	// //inputTree->SetBranchStatus("DPhi_METJetLeading"         ,1); 
	// //inputTree->SetBranchStatus("DPhi_METJetSecond"          ,1); 
	// inputTree->SetBranchStatus("Ht30"              ,1); 
	// inputTree->SetBranchStatus("nBJet30_MV2c10_FixedCutBEff_77"          ,1); 
	// //inputTree->SetBranchStatus("nLep_signal"           ,1); 
	// inputTree->SetBranchStatus("lepPt"          ,1); 
	// inputTree->SetBranchStatus("lepEta"         ,1); 
	// inputTree->SetBranchStatus("lepPhi"         ,1); 
	// inputTree->SetBranchStatus("nJet30"           ,1); 
	// //inputTree->SetBranchStatus("jet_btag"          ,1); 
	// inputTree->SetBranchStatus("jetM"          ,1); 
	// inputTree->SetBranchStatus("jetPt"          ,1); 
	// inputTree->SetBranchStatus("jetEta"         ,1); 
	// inputTree->SetBranchStatus("jetPhi"         ,1); 
	// //inputTree->SetBranchStatus("photon_passAmbi", 1); 

	// inputTree->SetBranchAddress("EventNumber"              ,&EventNumber               );
	// inputTree->SetBranchAddress("RunNumber"              ,&RunNumber               );
	// inputTree->SetBranchAddress("mu"              ,&Mu               );
	// inputTree->SetBranchAddress("met_Et"             ,&MET              );
	// inputTree->SetBranchAddress("met_Phi"         ,&MET_phi          );
	// inputTree->SetBranchAddress("TST_Et"         ,&MET_softTerm          );
	// inputTree->SetBranchAddress("TST_Phi"         ,&MET_softPhi          );
	// //inputTree->SetBranchAddress("truthMET"             ,&truthMET              );
	// //inputTree->SetBranchAddress("truthMET_Phi"         ,&truthMET_Phi          );
	// //inputTree->SetBranchAddress("DPhi_METJetLeading"         ,&DPhi_METJetLeading          );
	// //inputTree->SetBranchAddress("DPhi_METJetSecond"          ,&DPhi_METJetSecond           );
	// inputTree->SetBranchAddress("Ht30"              ,&HT               );
	// inputTree->SetBranchAddress("nBJet30_MV2c10_FixedCutBEff_77"          ,&bjet_n            );
	// //inputTree->SetBranchAddress("nLep_signal"           ,&lep_n            );
	// //inputTree->SetBranchAddress("nLep_signal"           ,&nLep_signal            );
	// //inputTree->SetBranchAddress("nLep_base"             ,&nLep_base            );
	// inputTree->SetBranchAddress("lepPt"          ,&lep_pT           );
	// inputTree->SetBranchAddress("lepEta"         ,&lep_eta          );
	// inputTree->SetBranchAddress("lepPhi"         ,&lep_phi          );
	// inputTree->SetBranchAddress("nJet30"           ,&jet_n            );
	// //inputTree->SetBranchAddress("jet_btag"          ,&jet_btag           );
	// inputTree->SetBranchAddress("jetM"          ,&jet_m           );
	// inputTree->SetBranchAddress("jetPt"          ,&jet_pT           );
	// inputTree->SetBranchAddress("jetEta"         ,&jet_eta          );
	// inputTree->SetBranchAddress("jetPhi"         ,&jet_phi          );
	// //inputTree->SetBranchAddress("photon_passAmbi", &photon_passAmbi);

	// float sampleWeight;
	// Float_t eventWeight;
	// //std::vector<float>* truthPhoton_pT = new std::vector<float>(10);
	// //std::vector<float>* truthPhoton_eta = new std::vector<float>(10);
	// //std::vector<float>* truthPhoton_phi = new std::vector<float>(10);
	// //std::vector<float>* photon_truthPt = new std::vector<float>(10);
	// //std::vector<float>* photon_truthEta = new std::vector<float>(10);
	// //std::vector<float>* photon_truthPhi = new std::vector<float>(10);
	// if (isData!=1) {
	//   inputTree->SetBranchStatus("sampleWeight",1);
	//   inputTree->SetBranchStatus("eventWeight",1);
	//   //inputTree->SetBranchStatus("truthPhoton_pT", 1);
	//   //inputTree->SetBranchStatus("truthPhoton_eta", 1);
	//   //inputTree->SetBranchStatus("truthPhoton_phi", 1);
	//   //inputTree->SetBranchStatus("photon_truthPt", 1);
	//   //inputTree->SetBranchStatus("photon_truthEta", 1);
	//   //inputTree->SetBranchStatus("photon_truthPhi", 1);

	//   inputTree->SetBranchAddress("sampleWeight",&sampleWeight);
	//   inputTree->SetBranchAddress("eventWeight",&eventWeight);
	//   //inputTree->SetBranchAddress("truthPhoton_pT", &truthPhoton_pT);
	//   //inputTree->SetBranchAddress("truthPhoton_eta", &truthPhoton_eta);
	//   //inputTree->SetBranchAddress("truthPhoton_phi", &truthPhoton_phi);
	//   //inputTree->SetBranchAddress("photon_truthPt", &photon_truthPt);
	//   //inputTree->SetBranchAddress("photon_truthEta", &photon_truthEta);
	//   //inputTree->SetBranchAddress("photon_truthPhi", &photon_truthPhi);
	// }
