Long64_t EventNumber;
Int_t RunNumber;
Float_t Mu;
double mll;
Float_t MT2Top;
Float_t MT2W;
double MET;
double MET_phi;
double MET_softTerm;
double MET_softPhi;
Float_t truthMET;
Float_t truthMET_Phi;
double DPhi_METJetLeading;
double DPhi_METJetSecond;
double HT;
double HTincl;
double Z_pt;
double Z_eta;
double Z_phi;
double SherpaNJetWeight;
Int_t channel;
Int_t is_OS;
Int_t HLT_e60_lhmedium;
Int_t HLT_2e17_lhvloose_nod0;
Int_t HLT_mu50;
Int_t HLT_mu18_mu8noL1;
Int_t HLT_e17_lhloose_mu14;
Int_t HLT_e7_lhmedium_mu24;
Int_t eetrig;
Int_t mmtrig;
Int_t emtrig;
Int_t jet_n;
Int_t bjet_n;
Int_t lep_n;
Int_t el_n;
Int_t mu_n;
std::vector<long>* lep_isPrompt = new std::vector<long>(10);
std::vector<long>* lep_pdgId = new std::vector<long>(10);
std::vector<double>* lep_pT = new std::vector<double>(10);
std::vector<double>* lep_eta = new std::vector<double>(10);
std::vector<double>* lep_phi = new std::vector<double>(10);
std::vector<double>* jet_pT = new std::vector<double>(10);
std::vector<double>* jet_eta = new std::vector<double>(10);
std::vector<double>* jet_phi = new std::vector<double>(10);
std::vector<double>* jet_m = new std::vector<double>(10);
std::vector<double>* jet_btag = new std::vector<double>(10);
std::vector<int>* pass_trig_MET = new std::vector<int>(10);
double sampleWeight;
Float_t eventWeight;
//Float_t emtrigweight;
//Float_t eetrigweight;
//Float_t mmtrigweight;
Double_t trig_sf;
Float_t truth_ZpT;
Float_t truth_Zphi;
std::vector<double>* lep_truthPt = new std::vector<double>(10);
std::vector<double>* lep_truthEta = new std::vector<double>(10);
std::vector<double>* lep_truthPhi = new std::vector<double>(10);
std::vector<double>* lep_truthGammaPt = new std::vector<double>(10);
std::vector<double>* lep_weight = new std::vector<double>(10);
Int_t truthJet_n;
std::vector<double>* truthJet_pT = new std::vector<double>(10);
std::vector<double>* truthJet_eta = new std::vector<double>(10);
std::vector<double>* truthJet_phi = new std::vector<double>(10);

void GetBranches(TTree* inputTree, bool isData) {

	inputTree->SetBranchStatus("*", 0);
	inputTree->SetBranchStatus("EventNumber"            ,1);
	inputTree->SetBranchStatus("RunNumber"              ,1);
	inputTree->SetBranchStatus("Mu"                     ,1);
	inputTree->SetBranchStatus("mll"                    ,1);
	inputTree->SetBranchStatus("MT2Top"                    ,1);
	inputTree->SetBranchStatus("MT2W"                    ,1);
	inputTree->SetBranchStatus("MET"                    ,1);
	inputTree->SetBranchStatus("MET_phi"                ,1);
	inputTree->SetBranchStatus("MET_softTerm"         ,1); 
	inputTree->SetBranchStatus("MET_softPhi"         ,1); 
	inputTree->SetBranchStatus("truthMET"               ,1);
	inputTree->SetBranchStatus("truthMET_Phi"           ,1);
	inputTree->SetBranchStatus("DPhi_METJetLeading"     ,1);
	inputTree->SetBranchStatus("DPhi_METJetSecond"      ,1);
	inputTree->SetBranchStatus("HT"                     ,1);
	inputTree->SetBranchStatus("HTincl"                 ,1);
	inputTree->SetBranchStatus("Z_pt"                   ,1);
	inputTree->SetBranchStatus("Z_eta"                  ,1);
	inputTree->SetBranchStatus("Z_phi"                  ,1);
	inputTree->SetBranchStatus("SherpaNJetWeight"       ,1);
	inputTree->SetBranchStatus("channel"                ,1);
	inputTree->SetBranchStatus("is_OS"                  ,1);
	inputTree->SetBranchStatus("HLT_e60_lhmedium"       ,1);
	inputTree->SetBranchStatus("HLT_2e17_lhvloose_nod0" ,1);
	inputTree->SetBranchStatus("HLT_mu50"               ,1);
	inputTree->SetBranchStatus("HLT_mu18_mu8noL1"       ,1);
	inputTree->SetBranchStatus("HLT_e17_lhloose_mu14"   ,1);
	inputTree->SetBranchStatus("HLT_e7_lhmedium_mu24"   ,1);
	inputTree->SetBranchStatus("eetrig"                 ,1);
	inputTree->SetBranchStatus("mmtrig"                 ,1);
	inputTree->SetBranchStatus("emtrig"                 ,1);
	inputTree->SetBranchStatus("bjet_n"                 ,1);
	inputTree->SetBranchStatus("lep_n"                  ,1);
	inputTree->SetBranchStatus("el_n"                  ,1);
	inputTree->SetBranchStatus("mu_n"                  ,1);
	inputTree->SetBranchStatus("lep_isPrompt"           ,1);
	inputTree->SetBranchStatus("lep_pdgId"              ,1);
	inputTree->SetBranchStatus("lep_pT"                 ,1);
	inputTree->SetBranchStatus("lep_eta"                ,1);
	inputTree->SetBranchStatus("lep_phi"                ,1);
	inputTree->SetBranchStatus("jet_n"                  ,1);
	inputTree->SetBranchStatus("jet_pT"                 ,1);
	inputTree->SetBranchStatus("jet_eta"                ,1);
	inputTree->SetBranchStatus("jet_phi"                ,1);
	inputTree->SetBranchStatus("jet_m"                ,1);
	inputTree->SetBranchStatus("jet_btag"                ,1);
	inputTree->SetBranchStatus("pass_trig_MET"              ,1);
	if (!isData) {
		inputTree->SetBranchStatus("sampleWeight"        ,1);
		inputTree->SetBranchStatus("eventWeight"         ,1);
		//inputTree->SetBranchStatus("emtrigweight"        ,1);
		//inputTree->SetBranchStatus("eetrigweight"        ,1);
		//inputTree->SetBranchStatus("mmtrigweight"        ,1);
		inputTree->SetBranchStatus("trig_sf"        ,1);
		inputTree->SetBranchStatus("lep_truthPt"         ,1);
		inputTree->SetBranchStatus("lep_truthEta"        ,1);
		inputTree->SetBranchStatus("lep_truthPhi"        ,1);
		inputTree->SetBranchStatus("lep_truthGammaPt"    ,1);
		inputTree->SetBranchStatus("lep_weight"          ,1);
		inputTree->SetBranchStatus("truth_ZpT"           ,1);
		inputTree->SetBranchStatus("truth_Zphi"          ,1);
		inputTree->SetBranchStatus("truthJet_n"          ,1);
		inputTree->SetBranchStatus("truthJet_pT"          ,1);
		inputTree->SetBranchStatus("truthJet_eta"          ,1);
		inputTree->SetBranchStatus("truthJet_phi"          ,1);
	}

	inputTree->SetBranchAddress("EventNumber"              ,&EventNumber               );
	inputTree->SetBranchAddress("RunNumber"              ,&RunNumber               );
	inputTree->SetBranchAddress("Mu"              ,&Mu               );
	inputTree->SetBranchAddress("mll"             ,&mll              );
	inputTree->SetBranchAddress("MT2Top"             ,&MT2Top              );
	inputTree->SetBranchAddress("MT2W"             ,&MT2W              );
	inputTree->SetBranchAddress("MET"             ,&MET              );
	inputTree->SetBranchAddress("MET_phi"         ,&MET_phi          );
	inputTree->SetBranchAddress("MET_softTerm"         ,&MET_softTerm          );
	inputTree->SetBranchAddress("MET_softPhi"         ,&MET_softPhi          );
	inputTree->SetBranchAddress("truthMET"             ,&truthMET              );
	inputTree->SetBranchAddress("truthMET_Phi"         ,&truthMET_Phi          );
	inputTree->SetBranchAddress("DPhi_METJetLeading"         ,&DPhi_METJetLeading          );
	inputTree->SetBranchAddress("DPhi_METJetSecond"          ,&DPhi_METJetSecond           );
	inputTree->SetBranchAddress("HT"              ,&HT               );
	inputTree->SetBranchAddress("HTincl"          ,&HTincl           );
	inputTree->SetBranchAddress("Z_pt"            ,&Z_pt             );
	inputTree->SetBranchAddress("Z_eta"           ,&Z_eta            );
	inputTree->SetBranchAddress("Z_phi"           ,&Z_phi            );
	inputTree->SetBranchAddress("SherpaNJetWeight"           ,&SherpaNJetWeight            );
	inputTree->SetBranchAddress("channel"         ,&channel          );
	inputTree->SetBranchAddress("is_OS"           ,&is_OS            );
	inputTree->SetBranchAddress("HLT_e60_lhmedium"          ,&HLT_e60_lhmedium           );
	inputTree->SetBranchAddress("HLT_2e17_lhvloose_nod0"          ,&HLT_2e17_lhvloose_nod0           );
	inputTree->SetBranchAddress("HLT_mu50"          ,&HLT_mu50           );
	inputTree->SetBranchAddress("HLT_mu18_mu8noL1"          ,&HLT_mu18_mu8noL1           );
	inputTree->SetBranchAddress("HLT_e17_lhloose_mu14"          ,&HLT_e17_lhloose_mu14           );
	inputTree->SetBranchAddress("HLT_e7_lhmedium_mu24"          ,&HLT_e7_lhmedium_mu24           );
	inputTree->SetBranchAddress("eetrig"          ,&eetrig           );
	inputTree->SetBranchAddress("mmtrig"          ,&mmtrig           );
	inputTree->SetBranchAddress("emtrig"          ,&emtrig           );
	inputTree->SetBranchAddress("bjet_n"          ,&bjet_n            );
	inputTree->SetBranchAddress("lep_n"           ,&lep_n            );
	inputTree->SetBranchAddress("el_n"           ,&el_n            );
	inputTree->SetBranchAddress("mu_n"           ,&mu_n            );
	inputTree->SetBranchAddress("lep_isPrompt"          ,&lep_isPrompt           );
	inputTree->SetBranchAddress("lep_pdgId"          ,&lep_pdgId           );
	inputTree->SetBranchAddress("lep_pT"          ,&lep_pT           );
	inputTree->SetBranchAddress("lep_eta"         ,&lep_eta          );
	inputTree->SetBranchAddress("lep_phi"         ,&lep_phi          );
	inputTree->SetBranchAddress("jet_n"           ,&jet_n            );
	inputTree->SetBranchAddress("jet_pT"          ,&jet_pT           );
	inputTree->SetBranchAddress("jet_eta"         ,&jet_eta          );
	inputTree->SetBranchAddress("jet_phi"         ,&jet_phi          );
	inputTree->SetBranchAddress("jet_m"         ,&jet_m          );
	inputTree->SetBranchAddress("jet_btag"         ,&jet_btag          );
	inputTree->SetBranchAddress("pass_trig_MET"          ,&pass_trig_MET           );

	if (!isData) {
		inputTree->SetBranchAddress("sampleWeight",&sampleWeight);
		inputTree->SetBranchAddress("eventWeight",&eventWeight);
		//inputTree->SetBranchAddress("emtrigweight",&emtrigweight);
		//inputTree->SetBranchAddress("eetrigweight",&eetrigweight);
		//inputTree->SetBranchAddress("mmtrigweight",&mmtrigweight);
		inputTree->SetBranchAddress("trig_sf",&trig_sf);
		inputTree->SetBranchAddress("lep_truthPt"          ,&lep_truthPt           );
		inputTree->SetBranchAddress("lep_truthEta"          ,&lep_truthEta           );
		inputTree->SetBranchAddress("lep_truthPhi"          ,&lep_truthPhi           );
		inputTree->SetBranchAddress("lep_truthGammaPt"          ,&lep_truthGammaPt           );
		inputTree->SetBranchAddress("lep_weight",&lep_weight);
		inputTree->SetBranchAddress("truth_ZpT",&truth_ZpT);
		inputTree->SetBranchAddress("truth_Zphi",&truth_Zphi);
		inputTree->SetBranchAddress("truthJet_n"          ,&truthJet_n          );
		inputTree->SetBranchAddress("truthJet_pT"          ,&truthJet_pT          );
		inputTree->SetBranchAddress("truthJet_eta"          ,&truthJet_eta          );
		inputTree->SetBranchAddress("truthJet_phi"          ,&truthJet_phi          );
	}


}
