double MET_rel = 0.;
double METl = 0.;
double METt = 0.;
double truthMETl = 0.;
double truthMETt = 0.;
double DPhi_2Lep = 0.;
double DR_2Lep = 0.;
double DR_W80jj = 0.;
double DR_Wmin2Jet = 0.;
double DR_J0J1 = 0.;
double DR_J1J2 = 0.;
double DPhi_METPhoton = 0.;
double DPhi_METLepLeading = 0.;
double DPhi_METLepSecond = 0.;
double DPhi_METLepMin = 0.;
double DPhi_TSTLepLeading = 0.;
double DPhi_TSTLepSecond = 0.;
double DPhi_TSTLepMin = 0.;
double MinDR_Lep0Jet = 0.;
double MinDR_Lep1Jet = 0.;
double MinDR_PhotonJet = 0.;
double MinDPhi_PhotonJet = 0.;
double mj0j1 = 0.;
double mj1j2 = 0.;
double m80jj = 0.;
double W80_pt = 0.;
double DPhi_METW80 = 0.;
double DPhi_W80Z = 0.;
double mWmin = 0.;
double Wmin_pt = 0.;
double Wmin_eta = 0.;
double DPhi_METWmin = 0.;
double DPhi_WminZ = 0.;
double W01_pt = 0.;
double DPhi_METW01 = 0.;
double DPhi_W01Z = 0.;
double totalWeight = 0.;
double Z_truthPt= 0.;
double Z_truthEta = 0.;
double Z_truthPhi = 0.;
double lep0_truthPt= 0.;
double lep0_truthEta = 0.;
double lep0_truthPhi = 0.;
double lep0_truthGammaPt= 0.;
double lep1_truthPt= 0.;
double lep1_truthEta = 0.;
double lep1_truthPhi = 0.;
double lep1_truthGammaPt= 0.;
double FS_ee_weight = 0.;
double FS_mm_weight = 0.;
std::vector<int>* jet_isPrompt = new std::vector<int>(10);
// following are variables from Jigsaw
std::vector<int>* lep_MetHsph = new std::vector<int>(10);
std::vector<int>* jet_MetHsph = new std::vector<int>(10);
double DPhi_METISR = 0.;
double ISR_pT = 0.;
double ISR_eta = 0.;
double ISR_phi = 0.;
double Jigsaw_ZMass = 0.;
double Jigsaw_WMass = 0.;
double DPhi_METJigsawW = 0.;
// following are variables from dijet pair
std::vector<int>* jet_isW80 = new std::vector<int>(10);
std::vector<int>* jet_isW01 = new std::vector<int>(10);
std::vector<int>* jet_isW12 = new std::vector<int>(10);
std::vector<int>* jet_isWmin = new std::vector<int>(10);
std::vector<int>* jet_isWminJ0 = new std::vector<int>(10);
std::vector<int>* jet_isWminJ1 = new std::vector<int>(10);
double DPhi_METNonWJet = 0.;
double NonWJet_pT = 0.;
double DPhi_METNonW12Jet = 0.;
double NonW12Jet_pT = 0.;
double DPhi_METNonWminJet = 0.;
double NonWminJet_pT = 0.;

TH1D* hist_g37lphi15_low_met = new TH1D("hist_g37lphi15_low_met","",bin_size,met_bin);
TH1D* hist_g37lphi15_medium_met = new TH1D("hist_g37lphi15_medium_met","",bin_size,met_bin);
TH1D* hist_g37lphi15_high_met = new TH1D("hist_g37lphi15_high_met","",bin_size,met_bin);
TH1D* hist_g37lphi15_zmet_met = new TH1D("hist_g37lphi15_zmet_met","",bin_size,met_bin);
TH1D* hist_g37lphi15_bveto_met = new TH1D("hist_g37lphi15_bveto_met","",bin_size,met_bin);

TH1D* hist_g37gphi15_low_met = new TH1D("hist_g37gphi15_low_met","",bin_size,met_bin);
TH1D* hist_g37gphi15_medium_met = new TH1D("hist_g37gphi15_medium_met","",bin_size,met_bin);
TH1D* hist_g37gphi15_high_met = new TH1D("hist_g37gphi15_high_met","",bin_size,met_bin);
TH1D* hist_g37gphi15_zmet_met = new TH1D("hist_g37gphi15_zmet_met","",bin_size,met_bin);
TH1D* hist_g37gphi15_bveto_met = new TH1D("hist_g37gphi15_bveto_met","",bin_size,met_bin);

TH1D* hist_l37_low_met = new TH1D("hist_l37_low_met","",bin_size,met_bin);
TH1D* hist_l37_medium_met = new TH1D("hist_l37_medium_met","",bin_size,met_bin);
TH1D* hist_l37_high_met = new TH1D("hist_l37_high_met","",bin_size,met_bin);
TH1D* hist_l37_zmet_met = new TH1D("hist_l37_zmet_met","",bin_size,met_bin);
TH1D* hist_l37_bveto_met = new TH1D("hist_l37_bveto_met","",bin_size,met_bin);

TH1D* hist_low_dpt = new TH1D("hist_low_dpt","",dpt_bin_size,dpt_bin);
TH1D* hist_low_njet = new TH1D("hist_low_njet","",bin_size,njet_bin);
TH1D* hist_low_nbjet = new TH1D("hist_low_nbjet","",bin_size,njet_bin);
TH1D* hist_low_pt = new TH1D("hist_low_pt","",bin_size,pt_bin);
TH1D* hist_sm_pt = new TH1D("hist_sm_pt","",bin_size,sm_pt_bin);
TH1D* hist_low_et = new TH1D("hist_low_et","",bin_size,et_bin);
TH1D* hist_low_ht = new TH1D("hist_low_ht","",bin_size,ht_bin);
TH1D* hist_low_htincl = new TH1D("hist_low_htincl","",bin_size,ht_bin);
TH1D* hist_medium_njet = new TH1D("hist_medium_njet","",bin_size,njet_bin);
TH1D* hist_medium_nbjet = new TH1D("hist_medium_nbjet","",bin_size,njet_bin);
TH1D* hist_medium_pt = new TH1D("hist_medium_pt","",bin_size,pt_bin);
TH1D* hist_medium_et = new TH1D("hist_medium_et","",bin_size,et_bin);
TH1D* hist_medium_ht = new TH1D("hist_medium_ht","",bin_size,ht_bin);
TH1D* hist_medium_htincl = new TH1D("hist_medium_htincl","",bin_size,ht_bin);
TH1D* hist_high_njet = new TH1D("hist_high_njet","",bin_size,njet_bin);
TH1D* hist_high_nbjet = new TH1D("hist_high_nbjet","",bin_size,njet_bin);
TH1D* hist_high_pt = new TH1D("hist_high_pt","",bin_size,pt_bin);
TH1D* hist_high_et = new TH1D("hist_high_et","",bin_size,et_bin);
TH1D* hist_high_ht = new TH1D("hist_high_ht","",bin_size,ht_bin);
TH1D* hist_high_htincl = new TH1D("hist_high_htincl","",bin_size,ht_bin);
TH1D* hist_zmet_njet = new TH1D("hist_zmet_njet","",bin_size,njet_bin);
TH1D* hist_zmet_nbjet = new TH1D("hist_zmet_nbjet","",bin_size,njet_bin);
TH1D* hist_zmet_pt = new TH1D("hist_zmet_pt","",bin_size,pt_bin);
TH1D* hist_zmet_et = new TH1D("hist_zmet_et","",bin_size,et_bin);
TH1D* hist_zmet_ht = new TH1D("hist_zmet_ht","",bin_size,ht_bin);
TH1D* hist_zmet_htincl = new TH1D("hist_zmet_htincl","",bin_size,ht_bin);
TH1D* hist_bveto_njet = new TH1D("hist_bveto_njet","",bin_size,njet_bin);
TH1D* hist_bveto_nbjet = new TH1D("hist_bveto_nbjet","",bin_size,njet_bin);
TH1D* hist_bveto_pt = new TH1D("hist_bveto_pt","",bin_size,pt_bin);
TH1D* hist_bveto_et = new TH1D("hist_bveto_et","",bin_size,et_bin);
TH1D* hist_bveto_ht = new TH1D("hist_bveto_ht","",bin_size,ht_bin);
TH1D* hist_bveto_htincl = new TH1D("hist_bveto_htincl","",bin_size,ht_bin);
TH1D* hist_fsee_low_njet = new TH1D("hist_fsee_low_njet","",bin_size,njet_bin);
TH1D* hist_fsee_low_nbjet = new TH1D("hist_fsee_low_nbjet","",bin_size,njet_bin);
TH1D* hist_fsee_low_pt = new TH1D("hist_fsee_low_pt","",bin_size,pt_bin);
TH1D* hist_fsee_low_et = new TH1D("hist_fsee_low_et","",bin_size,et_bin);
TH1D* hist_fsee_low_ht = new TH1D("hist_fsee_low_ht","",bin_size,ht_bin);
TH1D* hist_fsee_low_htincl = new TH1D("hist_fsee_low_htincl","",bin_size,ht_bin);
TH1D* hist_fsee_medium_njet = new TH1D("hist_fsee_medium_njet","",bin_size,njet_bin);
TH1D* hist_fsee_medium_nbjet = new TH1D("hist_fsee_medium_nbjet","",bin_size,njet_bin);
TH1D* hist_fsee_medium_pt = new TH1D("hist_fsee_medium_pt","",bin_size,pt_bin);
TH1D* hist_fsee_medium_et = new TH1D("hist_fsee_medium_et","",bin_size,et_bin);
TH1D* hist_fsee_medium_ht = new TH1D("hist_fsee_medium_ht","",bin_size,ht_bin);
TH1D* hist_fsee_medium_htincl = new TH1D("hist_fsee_medium_htincl","",bin_size,ht_bin);
TH1D* hist_fsee_high_njet = new TH1D("hist_fsee_high_njet","",bin_size,njet_bin);
TH1D* hist_fsee_high_nbjet = new TH1D("hist_fsee_high_nbjet","",bin_size,njet_bin);
TH1D* hist_fsee_high_pt = new TH1D("hist_fsee_high_pt","",bin_size,pt_bin);
TH1D* hist_fsee_high_et = new TH1D("hist_fsee_high_et","",bin_size,et_bin);
TH1D* hist_fsee_high_ht = new TH1D("hist_fsee_high_ht","",bin_size,ht_bin);
TH1D* hist_fsee_high_htincl = new TH1D("hist_fsee_high_htincl","",bin_size,ht_bin);
TH1D* hist_fsee_zmet_njet = new TH1D("hist_fsee_zmet_njet","",bin_size,njet_bin);
TH1D* hist_fsee_zmet_nbjet = new TH1D("hist_fsee_zmet_nbjet","",bin_size,njet_bin);
TH1D* hist_fsee_zmet_pt = new TH1D("hist_fsee_zmet_pt","",bin_size,pt_bin);
TH1D* hist_fsee_zmet_et = new TH1D("hist_fsee_zmet_et","",bin_size,et_bin);
TH1D* hist_fsee_zmet_ht = new TH1D("hist_fsee_zmet_ht","",bin_size,ht_bin);
TH1D* hist_fsee_zmet_htincl = new TH1D("hist_fsee_zmet_htincl","",bin_size,ht_bin);
TH1D* hist_fsee_bveto_njet = new TH1D("hist_fsee_bveto_njet","",bin_size,njet_bin);
TH1D* hist_fsee_bveto_nbjet = new TH1D("hist_fsee_bveto_nbjet","",bin_size,njet_bin);
TH1D* hist_fsee_bveto_pt = new TH1D("hist_fsee_bveto_pt","",bin_size,pt_bin);
TH1D* hist_fsee_bveto_et = new TH1D("hist_fsee_bveto_et","",bin_size,et_bin);
TH1D* hist_fsee_bveto_ht = new TH1D("hist_fsee_bveto_ht","",bin_size,ht_bin);
TH1D* hist_fsee_bveto_htincl = new TH1D("hist_fsee_bveto_htincl","",bin_size,ht_bin);

TH1D* hist_fsmm_low_njet = new TH1D("hist_fsmm_low_njet","",bin_size,njet_bin);
TH1D* hist_fsmm_low_nbjet = new TH1D("hist_fsmm_low_nbjet","",bin_size,njet_bin);
TH1D* hist_fsmm_low_pt = new TH1D("hist_fsmm_low_pt","",bin_size,pt_bin);
TH1D* hist_fsmm_low_et = new TH1D("hist_fsmm_low_et","",bin_size,et_bin);
TH1D* hist_fsmm_low_ht = new TH1D("hist_fsmm_low_ht","",bin_size,ht_bin);
TH1D* hist_fsmm_low_htincl = new TH1D("hist_fsmm_low_htincl","",bin_size,ht_bin);
TH1D* hist_fsmm_medium_njet = new TH1D("hist_fsmm_medium_njet","",bin_size,njet_bin);
TH1D* hist_fsmm_medium_nbjet = new TH1D("hist_fsmm_medium_nbjet","",bin_size,njet_bin);
TH1D* hist_fsmm_medium_pt = new TH1D("hist_fsmm_medium_pt","",bin_size,pt_bin);
TH1D* hist_fsmm_medium_et = new TH1D("hist_fsmm_medium_et","",bin_size,et_bin);
TH1D* hist_fsmm_medium_ht = new TH1D("hist_fsmm_medium_ht","",bin_size,ht_bin);
TH1D* hist_fsmm_medium_htincl = new TH1D("hist_fsmm_medium_htincl","",bin_size,ht_bin);
TH1D* hist_fsmm_high_njet = new TH1D("hist_fsmm_high_njet","",bin_size,njet_bin);
TH1D* hist_fsmm_high_nbjet = new TH1D("hist_fsmm_high_nbjet","",bin_size,njet_bin);
TH1D* hist_fsmm_high_pt = new TH1D("hist_fsmm_high_pt","",bin_size,pt_bin);
TH1D* hist_fsmm_high_et = new TH1D("hist_fsmm_high_et","",bin_size,et_bin);
TH1D* hist_fsmm_high_ht = new TH1D("hist_fsmm_high_ht","",bin_size,ht_bin);
TH1D* hist_fsmm_high_htincl = new TH1D("hist_fsmm_high_htincl","",bin_size,ht_bin);
TH1D* hist_fsmm_zmet_njet = new TH1D("hist_fsmm_zmet_njet","",bin_size,njet_bin);
TH1D* hist_fsmm_zmet_nbjet = new TH1D("hist_fsmm_zmet_nbjet","",bin_size,njet_bin);
TH1D* hist_fsmm_zmet_pt = new TH1D("hist_fsmm_zmet_pt","",bin_size,pt_bin);
TH1D* hist_fsmm_zmet_et = new TH1D("hist_fsmm_zmet_et","",bin_size,et_bin);
TH1D* hist_fsmm_zmet_ht = new TH1D("hist_fsmm_zmet_ht","",bin_size,ht_bin);
TH1D* hist_fsmm_zmet_htincl = new TH1D("hist_fsmm_zmet_htincl","",bin_size,ht_bin);
TH1D* hist_fsmm_bveto_njet = new TH1D("hist_fsmm_bveto_njet","",bin_size,njet_bin);
TH1D* hist_fsmm_bveto_nbjet = new TH1D("hist_fsmm_bveto_nbjet","",bin_size,njet_bin);
TH1D* hist_fsmm_bveto_pt = new TH1D("hist_fsmm_bveto_pt","",bin_size,pt_bin);
TH1D* hist_fsmm_bveto_et = new TH1D("hist_fsmm_bveto_et","",bin_size,et_bin);
TH1D* hist_fsmm_bveto_ht = new TH1D("hist_fsmm_bveto_ht","",bin_size,ht_bin);
TH1D* hist_fsmm_bveto_htincl = new TH1D("hist_fsmm_bveto_htincl","",bin_size,ht_bin);

TH1D* hist_cutflow_raw = new TH1D("hist_cutflow_raw","",8,0,8);
TH1D* hist_cutflow_weight = new TH1D("hist_cutflow_weight","",8,0,8);

TH1D* hist_dPt_Pt[bin_size];
TH1D* hist_dPhi_Pt[bin_size];
TH1D* hist_METl_Pt[bin_size];
TH1D* hist_METt_Pt[bin_size];
TH1D* hist_JetMETl_Pt[bin_size];
TH1D* hist_2LPt_Pt[bin_size];
TH1D* hist_Mll_dPt[dpt_bin_size];
TH1D* hist_fsee_METl_Pt[bin_size];
TH1D* hist_fsmm_METl_Pt[bin_size];

TH1D* hist_low_pt_fullmll = new TH1D("hist_low_pt_fullmll","",bin_size,pt_bin);
TH1D* hist_medium_pt_fullmll = new TH1D("hist_medium_pt_fullmll","",bin_size,pt_bin);
TH1D* hist_high_pt_fullmll = new TH1D("hist_high_pt_fullmll","",bin_size,pt_bin);
TH1D* hist_zmet_pt_fullmll = new TH1D("hist_zmet_pt_fullmll","",bin_size,pt_bin);
TH1D* hist_bveto_pt_fullmll = new TH1D("hist_bveto_pt_fullmll","",bin_size,pt_bin);
TH1D* hist_low_pt_onz = new TH1D("hist_low_pt_onz","",bin_size,pt_bin);
TH1D* hist_medium_pt_onz = new TH1D("hist_medium_pt_onz","",bin_size,pt_bin);
TH1D* hist_high_pt_onz = new TH1D("hist_high_pt_onz","",bin_size,pt_bin);
TH1D* hist_zmet_pt_onz = new TH1D("hist_zmet_pt_onz","",bin_size,pt_bin);
TH1D* hist_bveto_pt_onz = new TH1D("hist_bveto_pt_onz","",bin_size,pt_bin);
TH1D* hist_low_met_fullmll = new TH1D("hist_low_met_fullmll","",bin_size,met_bin);
TH1D* hist_medium_met_fullmll = new TH1D("hist_medium_met_fullmll","",bin_size,met_bin);
TH1D* hist_high_met_fullmll = new TH1D("hist_high_met_fullmll","",bin_size,met_bin);
TH1D* hist_zmet_met_fullmll = new TH1D("hist_zmet_met_fullmll","",bin_size,met_bin);
TH1D* hist_bveto_met_fullmll = new TH1D("hist_bveto_met_fullmll","",bin_size,met_bin);
TH1D* hist_low_met_onz = new TH1D("hist_low_met_onz","",bin_size,met_bin);
TH1D* hist_medium_met_onz = new TH1D("hist_medium_met_onz","",bin_size,met_bin);
TH1D* hist_high_met_onz = new TH1D("hist_high_met_onz","",bin_size,met_bin);
TH1D* hist_zmet_met_onz = new TH1D("hist_zmet_met_onz","",bin_size,met_bin);
TH1D* hist_bveto_met_onz = new TH1D("hist_bveto_met_onz","",bin_size,met_bin);
TH1D* hist_low_dphi_fullmll = new TH1D("hist_low_dphi_fullmll","",bin_size,dphi_bin);
TH1D* hist_medium_dphi_fullmll = new TH1D("hist_medium_dphi_fullmll","",bin_size,dphi_bin);
TH1D* hist_high_dphi_fullmll = new TH1D("hist_high_dphi_fullmll","",bin_size,dphi_bin);
TH1D* hist_zmet_dphi_fullmll = new TH1D("hist_zmet_dphi_fullmll","",bin_size,dphi_bin);
TH1D* hist_bveto_dphi_fullmll = new TH1D("hist_bveto_dphi_fullmll","",bin_size,dphi_bin);
TH1D* hist_low_dphi_onz = new TH1D("hist_low_dphi_onz","",bin_size,dphi_bin);
TH1D* hist_medium_dphi_onz = new TH1D("hist_medium_dphi_onz","",bin_size,dphi_bin);
TH1D* hist_high_dphi_onz = new TH1D("hist_high_dphi_onz","",bin_size,dphi_bin);
TH1D* hist_zmet_dphi_onz = new TH1D("hist_zmet_dphi_onz","",bin_size,dphi_bin);
TH1D* hist_bveto_dphi_onz = new TH1D("hist_bveto_dphi_onz","",bin_size,dphi_bin);

void AddBranches(TTree* BaselineTree, bool isData) {

	//BaselineTree->Branch("jet_isPrompt","std::vector<int>",&jet_isPrompt);
	//BaselineTree->Branch("lep_MetHsph","std::vector<int>",&lep_MetHsph);
	//BaselineTree->Branch("jet_MetHsph","std::vector<int>",&jet_MetHsph);
	//BaselineTree->Branch("DPhi_METISR",&DPhi_METISR,"DPhi_METISR/D");
	//BaselineTree->Branch("ISR_pT",&ISR_pT,"ISR_pT/D");
	//BaselineTree->Branch("ISR_eta",&ISR_eta,"ISR_eta/D");
	//BaselineTree->Branch("ISR_phi",&ISR_phi,"ISR_phi/D");
	//BaselineTree->Branch("Jigsaw_ZMass",&Jigsaw_ZMass,"Jigsaw_ZMass/D");
	//BaselineTree->Branch("Jigsaw_WMass",&Jigsaw_WMass,"Jigsaw_WMass/D");
	//BaselineTree->Branch("DPhi_METJigsawW",&DPhi_METJigsawW,"DPhi_METJigsawW/D");

	//BaselineTree->Branch("jet_isW80","std::vector<int>",&jet_isW80);
	//BaselineTree->Branch("jet_isW01","std::vector<int>",&jet_isW01);
	//BaselineTree->Branch("jet_isW12","std::vector<int>",&jet_isW12);
	//BaselineTree->Branch("jet_isWmin","std::vector<int>",&jet_isWmin);
	//BaselineTree->Branch("jet_isWminJ0","std::vector<int>",&jet_isWminJ0);
	//BaselineTree->Branch("jet_isWminJ1","std::vector<int>",&jet_isWminJ1);
	BaselineTree->Branch("DPhi_METNonWJet",&DPhi_METNonWJet,"DPhi_METNonWJet/D");
	BaselineTree->Branch("NonWJet_pT",&NonWJet_pT,"NonWJet_pT/D");
	//BaselineTree->Branch("DPhi_METNonW12Jet",&DPhi_METNonW12Jet,"DPhi_METNonW12Jet/D");
	//BaselineTree->Branch("NonW12Jet_pT",&NonW12Jet_pT,"NonW12Jet_pT/D");
	BaselineTree->Branch("DPhi_METNonWminJet",&DPhi_METNonWminJet,"DPhi_METNonWminJet/D");
	BaselineTree->Branch("NonWminJet_pT",&NonWminJet_pT,"NonWminJet_pT/D");
	BaselineTree->Branch("lep_pT","std::vector<double>",&lep_pT);
	BaselineTree->Branch("lep_phi","std::vector<double>",&lep_phi);
	BaselineTree->Branch("lep_eta","std::vector<double>",&lep_eta);
	BaselineTree->Branch("jet_pT","std::vector<double>",&jet_pT);
	BaselineTree->Branch("jet_phi","std::vector<double>",&jet_phi);
	BaselineTree->Branch("jet_eta","std::vector<double>",&jet_eta);
	BaselineTree->Branch("jet_m","std::vector<double>",&jet_m);
	BaselineTree->Branch("jet_btag","std::vector<double>",&jet_btag);
	BaselineTree->Branch("Mu",&Mu,"Mu/Float_t");
	BaselineTree->Branch("mll",&mll,"mll/D");
	//BaselineTree->Branch("MT2Top",&MT2Top,"MT2Top/Float_t");
	BaselineTree->Branch("MT2W",&MT2W,"MT2W/Float_t");
	BaselineTree->Branch("MET",&MET,"MET/D");
	//BaselineTree->Branch("MET_rel",&MET_rel,"MET_rel/D");
	BaselineTree->Branch("METl",&METl,"METl/D");
	BaselineTree->Branch("METt",&METt,"METt/D");
	BaselineTree->Branch("MET_phi",&MET_phi,"MET_phi/D");
	BaselineTree->Branch("MET_softTerm",&MET_softTerm,"MET_softTerm/D");
	BaselineTree->Branch("MET_softPhi",&MET_softPhi,"MET_softPhi/D");
	//BaselineTree->Branch("truthMET",&truthMET,"truthMET/Float_t");
	//BaselineTree->Branch("truthMETl",&truthMETl,"truthMETl/D");
	//BaselineTree->Branch("truthMETt",&truthMETt,"truthMETt/D");
	//BaselineTree->Branch("truthMET_Phi",&MET_phi,"MET_phi/Float_t");
	BaselineTree->Branch("DPhi_2Lep",&DPhi_2Lep,"DPhi_2Lep/D");
	BaselineTree->Branch("DR_2Lep",&DR_2Lep,"DR_2Lep/D");
	//BaselineTree->Branch("DR_W80jj",&DR_W80jj,"DR_W80jj/D");
	BaselineTree->Branch("DR_Wmin2Jet",&DR_Wmin2Jet,"DR_Wmin2Jet/D");
	BaselineTree->Branch("DR_J0J1",&DR_J0J1,"DR_J0J1/D");
	//BaselineTree->Branch("DR_J1J2",&DR_J1J2,"DR_J1J2/D");
	BaselineTree->Branch("DPhi_METJetLeading",&DPhi_METJetLeading,"DPhi_METJetLeading/D");
	BaselineTree->Branch("DPhi_METJetSecond",&DPhi_METJetSecond,"DPhi_METJetSecond/D");
	BaselineTree->Branch("DPhi_METPhoton",&DPhi_METPhoton,"DPhi_METPhoton/D");
	BaselineTree->Branch("DPhi_METLepLeading",&DPhi_METLepLeading,"DPhi_METLepLeading/D");
	BaselineTree->Branch("DPhi_METLepSecond",&DPhi_METLepSecond,"DPhi_METLepSecond/D");
	BaselineTree->Branch("DPhi_METLepMin",&DPhi_METLepMin,"DPhi_METLepMin/D");
	//BaselineTree->Branch("DPhi_TSTLepLeading",&DPhi_TSTLepLeading,"DPhi_TSTLepLeading/D");
	//BaselineTree->Branch("DPhi_TSTLepSecond",&DPhi_TSTLepSecond,"DPhi_TSTLepSecond/D");
	//BaselineTree->Branch("DPhi_TSTLepMin",&DPhi_TSTLepMin,"DPhi_TSTLepMin/D");
	//BaselineTree->Branch("MinDR_Lep0Jet",&MinDR_Lep0Jet,"MinDR_Lep0Jet/D");
	//BaselineTree->Branch("MinDR_Lep1Jet",&MinDR_Lep1Jet,"MinDR_Lep1Jet/D");
	//BaselineTree->Branch("MinDR_PhotonJet",&MinDR_PhotonJet,"MinDR_PhotonJet/D");
	//BaselineTree->Branch("MinDPhi_PhotonJet",&MinDPhi_PhotonJet,"MinDPhi_PhotonJet/D");
	BaselineTree->Branch("HT",&HT,"HT/D");
	//BaselineTree->Branch("HTincl",&HTincl,"HTincl/D");
	BaselineTree->Branch("Z_pt",&Z_pt,"Z_pt/D");
	BaselineTree->Branch("Z_eta",&Z_eta,"Z_eta/D");
	//BaselineTree->Branch("Z_phi",&Z_phi,"Z_phi/D");
	BaselineTree->Branch("SherpaNJetWeight",&SherpaNJetWeight,"SherpaNJetWeight/D");
	BaselineTree->Branch("channel",&channel,"channel/Int_t");
	//BaselineTree->Branch("is_OS",&is_OS,"is_OS/Int_t");
	//BaselineTree->Branch("eetrig",&eetrig,"eetrig/Int_t");
	//BaselineTree->Branch("mmtrig",&mmtrig,"mmtrig/Int_t");
	//BaselineTree->Branch("emtrig",&emtrig,"emtrig/Int_t");
	BaselineTree->Branch("bjet_n",&bjet_n,"bjet_n/Int_t");
	BaselineTree->Branch("jet_n",&jet_n,"jet_n/Int_t");
	BaselineTree->Branch("lep_n",&lep_n,"lep_n/Int_t");
	//BaselineTree->Branch("el_n",&el_n,"el_n/Int_t");
	//BaselineTree->Branch("mu_n",&mu_n,"mu_n/Int_t");
	BaselineTree->Branch("mj0j1",&mj0j1,"mj0j1/D");
	//BaselineTree->Branch("mj1j2",&mj1j2,"mj1j2/D");
	//BaselineTree->Branch("m80jj",&m80jj,"m80jj/D");
	//BaselineTree->Branch("W80_pt",&W80_pt,"W80_pt/D");
	//BaselineTree->Branch("DPhi_METW80",&DPhi_METW80,"DPhi_METW80/D");
	//BaselineTree->Branch("DPhi_W80Z",&DPhi_W80Z,"DPhi_W80Z/D");
	BaselineTree->Branch("W01_pt",&W01_pt,"W01_pt/D");
	BaselineTree->Branch("DPhi_METW01",&DPhi_METW01,"DPhi_METW01/D");
	BaselineTree->Branch("DPhi_W01Z",&DPhi_W01Z,"DPhi_W01Z/D");
	BaselineTree->Branch("mWmin",&mWmin,"mWmin/D");
	BaselineTree->Branch("Wmin_pt",&Wmin_pt,"Wmin_pt/D");
	BaselineTree->Branch("Wmin_eta",&Wmin_eta,"Wmin_eta/D");
	BaselineTree->Branch("DPhi_METWmin",&DPhi_METWmin,"DPhi_METWmin/D");
	BaselineTree->Branch("DPhi_WminZ",&DPhi_WminZ,"DPhi_WminZ/D");
	BaselineTree->Branch("EventNumber",&EventNumber,"EventNumber/Long64_t");
	BaselineTree->Branch("RunNumber",&RunNumber,"RunNumber/Int_t");
	BaselineTree->Branch("totalWeight",&totalWeight,"totalWeight/D");
	if (!isData) {
		BaselineTree->Branch("Z_truthPt",&Z_truthPt,"Z_truthPt/D");
		BaselineTree->Branch("Z_truthEta",&Z_truthEta,"Z_truthEta/D");
		BaselineTree->Branch("Z_truthPhi",&Z_truthPhi,"Z_truthPhi/D");
		//BaselineTree->Branch("lep0_truthPt",&lep0_truthPt,"lep0_truthPt/D");
		//BaselineTree->Branch("lep0_truthEta",&lep0_truthEta,"lep0_truthEta/D");
		//BaselineTree->Branch("lep0_truthPhi",&lep0_truthPhi,"lep0_truthPhi/D");
		//BaselineTree->Branch("lep0_truthGammaPt",&lep0_truthGammaPt,"lep0_truthGammaPt/D");
		//BaselineTree->Branch("lep1_truthPt",&lep1_truthPt,"lep1_truthPt/D");
		//BaselineTree->Branch("lep1_truthEta",&lep1_truthEta,"lep1_truthEta/D");
		//BaselineTree->Branch("lep1_truthPhi",&lep1_truthPhi,"lep1_truthPhi/D");
		//BaselineTree->Branch("lep1_truthGammaPt",&lep1_truthGammaPt,"lep1_truthGammaPt/D");
	}
	//BaselineTree->Branch("FS_ee_weight",&FS_ee_weight,"FS_ee_weight/D");
	//BaselineTree->Branch("FS_mm_weight",&FS_mm_weight,"FS_mm_weight/D");

	hist_cutflow_raw->SetStats(0);
	hist_cutflow_raw->GetXaxis()->SetBinLabel(1, "2lep");
	hist_cutflow_raw->GetXaxis()->SetBinLabel(2, "flavor");
	hist_cutflow_raw->GetXaxis()->SetBinLabel(3, "trigger");
	hist_cutflow_raw->GetXaxis()->SetBinLabel(4, "OS");
	hist_cutflow_raw->GetXaxis()->SetBinLabel(5, "lep pT");
	hist_cutflow_raw->GetXaxis()->SetBinLabel(6, "njet");
	hist_cutflow_raw->GetXaxis()->SetBinLabel(7, "mll");
	hist_cutflow_raw->GetXaxis()->SetBinLabel(8, "prompt");

	hist_cutflow_weight->SetStats(0);
	hist_cutflow_weight->GetXaxis()->SetBinLabel(1, "2lep");
	hist_cutflow_weight->GetXaxis()->SetBinLabel(2, "flavor");
	hist_cutflow_weight->GetXaxis()->SetBinLabel(3, "trigger");
	hist_cutflow_weight->GetXaxis()->SetBinLabel(4, "OS");
	hist_cutflow_weight->GetXaxis()->SetBinLabel(5, "lep pT");
	hist_cutflow_weight->GetXaxis()->SetBinLabel(6, "njet");
	hist_cutflow_weight->GetXaxis()->SetBinLabel(7, "mll");
	hist_cutflow_weight->GetXaxis()->SetBinLabel(8, "prompt");

	for (int bin=0;bin<bin_size;bin++) {
		hist_METl_Pt[bin] = new TH1D(TString("hist_METl_Pt_")+TString::Itoa(bin,10),"",40000,-30000,10000);
		hist_METl_Pt[bin]->SetStats(0);
		hist_METt_Pt[bin] = new TH1D(TString("hist_METt_Pt_")+TString::Itoa(bin,10),"",40000,-30000,10000);
		hist_METt_Pt[bin]->SetStats(0);
	}

}
