
Long64_t EventNumber;
Int_t RunNumber;
float totalWeight = 0.;
int pt = 0; // pT bin for reweighting
int smpt = 0; // pT bin for smearing
int ht = 0;
int njet = 0;
int nbjet = 0;
Int_t jet_n;
Int_t bjet_n;
float HT = 0.;
float truthGamma_pt = 0.;
float truthGamma_phi = 0.;
float truthGamma_eta = 0.;
float gamma_pt = 0.;
float gamma_eta = 0.;
float gamma_phi = 0.;
float gamma_dR = 0.;
float MET;
float METl;
float METt;
float MET_phi;
float DPhi_METJetLeading;
float DPhi_METJetSecond;
float MinDPhi_PhotonJet;
std::vector<float>* jet_pT = new std::vector<float>(10);
std::vector<float>* jet_eta = new std::vector<float>(10);
std::vector<float>* jet_phi = new std::vector<float>(10);
std::vector<float>* jet_m = new std::vector<float>(10);
std::vector<float>* jet_btag = new std::vector<float>(10);

// new variables to be added to ntuple
int lep_n = 0;
int dpt = 0;
int pt_smear = 0;
int met_smear = 0;
int dphi_smear = 0;
float HTincl = 0.;
float mll = 0.;
float smear_shift = 0.;
float gamma_pt_smear = 0.;
float gamma_phi_smear = 0.;
float MET_smear;
float MET_phi_smear;
float DPhi_METJetLeading_smear;
float DPhi_METJetSecond_smear;
float DPhi_METLepLeading_smear;
float DPhi_METLepSecond_smear;
float METl_smear = 0.;
float METt_smear = 0.;
float DPhi_METPhoton_smear = 0.;
float mj1j2 = 0.;
float DR_J1J2 = 0.;
float DR_Wmin2Jet = 0.;
float DR_J0J1 = 0.;
float DR_W80jj = 0.;
float mWmin = 0.;
float Wmin_pt = 0.;
float Wmin_eta = 0.;
float DPhi_METWmin = 0.;
float DPhi_WminZ = 0.;
float mj0j1 = 0.;
float m80jj = 0.;
float W01_pt = 0.;
float DPhi_METW01 = 0.;
float DPhi_W01Z = 0.;
float DPhi_W80Z = 0.;
float DPhi_METNonWminJet = 0.;
float NonWminJet_pT = 0.;
float W80_pt = 0.;
float DPhi_METW80 = 0.;
std::vector<int>* jet_isW80 = new std::vector<int>(10);
std::vector<int>* jet_isW01 = new std::vector<int>(10);
std::vector<int>* jet_isW12 = new std::vector<int>(10);
std::vector<int>* jet_isWmin = new std::vector<int>(10);
std::vector<int>* jet_isWminJ0 = new std::vector<int>(10);
std::vector<int>* jet_isWminJ1 = new std::vector<int>(10);
float DPhi_METNonWJet = 0.;
float NonWJet_pT = 0.;
float DPhi_METNonW12Jet = 0.;
float NonW12Jet_pT = 0.;

std::vector<float>* lep_pT = new std::vector<float>(10);
std::vector<float>* lep_eta = new std::vector<float>(10);
std::vector<float>* lep_phi = new std::vector<float>(10);

float MT2W;
float DR_2Lep = 0.;

